openshift/insights-operator

- Dockerfile
- Makefile
- README.md
- cmd/insights-operator/main.go
- config/pod.yaml
- glide.yaml
- manifests/05-deployment.yaml
- manifests/image-references
- pkg/authorizer/clusterauthorizer/clusterauthorizer.go
- pkg/cmd/start/start.go
- pkg/config/configobserver/configobserver.go
- pkg/controller/operator.go
- pkg/controller/periodic/periodic.go
- pkg/controller/status/status.go
- pkg/gather/clusterconfig/clusterconfig.go
- pkg/gather/interface.go
- pkg/insights/insightsclient/insightsclient.go
- pkg/insights/insightsuploader/insightsuploader.go
- pkg/record/diskrecorder/diskrecorder.go
Add slightly more information to README.md
> rename: Rename support-operator to insights-operator

- OWNERS
@smarterclayton as I will probably spend more time in this repo in near future :-)
> Add mfojtik to OWNERS file

- OWNERS
Perhaps it's a good time to move my realtionship with this project to the next level :)
> Add inecas to OWNERS

- go.mod
- go.sum
- manifests/03-clusterrole.yaml
- pkg/cmd/start/start.go
- pkg/controller/operator.go
- pkg/controller/periodic/periodic.go
- pkg/gather/clusterconfig/clusterconfig.go
- pkg/record/interface.go
- vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer.go
- vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer_polling.go
- vendor/github.com/openshift/library-go/pkg/controller/metrics/client_metrics.go
- vendor/github.com/openshift/library-go/pkg/controller/metrics/workqueue_metrics.go
- vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
- vendor/modules.txt
Grab running alerts from /federate using the gather client. More
metrics will be added later.
> gather: Collect some prometheus metrics for the cluster

- pkg/insights/insightsclient/insightsclient.go
Allow us to judge from logs how much we are sending.
> insightsclient: Report the amount of data written

- test/integration/basic_test.go
- test/integration/bugs_test.go
- test/integration/main_test.go
Added new test to verify that insights operator opt-in/opt-out works
> added TestOptOutOptIn and moved some code to functions

- test/integration/bugs_test.go
- test/integration/main_test.go
same as https://github.com/openshift/insights-operator/pull/50
> Bug 1788118: initial commit for tests for release 4.3

- pkg/gather/clusterconfig/clusterconfig.go
We are currently returning all of them and it is confusing.
> gather: Only return pods that have been pending more than 2m

- test/integration/bugs_test.go
- test/integration/main_test.go
just the backport of https://github.com/openshift/insights-operator/pull/50
> Bug 1798889: initial commit for tests for release 4.2

- test/integration/bugs_test.go
- test/integration/main_test.go
New test to cover https://bugzilla.redhat.com/show_bug.cgi?id=1782151
> add new test TestClusterDefaultNodeSelector

- OWNERS
For better integration, per ART team request.
> Specify bugzilla component in OWNERS

- go.mod
- pkg/authorizer/clusterauthorizer/clusterauthorizer.go
- pkg/authorizer/clusterauthorizer/clusterauthorizer_test.go
- pkg/config/config.go
- pkg/config/configobserver/configobserver.go
- pkg/insights/insightsclient/insightsclient.go
- pkg/insights/insightsclient/insightsclient_test.go
- vendor/golang.org/x/net/http/httpproxy/proxy.go
- vendor/modules.txt
Applied same commits as in #87
> Bug 1821149: Cherry-pick release 4.3 Support for specific http proxy for the service

- pkg/gather/clusterconfig/clusterconfig.go
- pkg/gather/clusterconfig/clusterconfig_test.go
- pkg/gather/clusterconfig/csr.go
- pkg/gather/clusterconfig/testdata/configmaps.json
- pkg/utils/testlog.go
cherry-pick e589926e750599f47a8b67c24af4893e6b407314  Collecting config maps 
cherry-pick 21fcdc88e5cbe785ed47ea84d86ff71fb9f2eee1 Gather BinaryData ConfigMap ecoded in base64. Add tests for for configmaps anonymizer
cherry-pick 1d33a3b3816fe4ead709ddb3ed681c73e2f287fe Gather BinaryData ConfigMap encoded in base64.
> Bug 1825757: Collecting config maps

- pkg/gather/clusterconfig/clusterconfig.go
If the pod is not healthy Insights operator should collect
previous/current logs for the pod containers. Only last 100 lines
is being kept to prevent the archive from growing large.
> Bug 1838973: GatherClusterOperators: store pod logs

- pkg/gather/clusterconfig/clusterconfig.go
- pkg/gather/clusterconfig/clusterconfig_test.go
This PR is based on an enhancement request. No entirely new data are collected. The real difference is that data that were previously only collected for unhealthy nodes/pods/containers are now collected for all; however, in a significantly minimalized format.
One potential use case for this data is to be able to warn the user about running a potentially vulnerable container/node image. There are other use cases as well, but I don't remember them from the top of my head anymore.
Only information about images related to Red Hat will be collected in order to further lower the data size, but most importantly in order to maintain data privacy.
- Set of running images
- Number of container instances per image
- Approximate age of pods
- ~~Provider of a cluster node and the OS image~~ (already …
> Bug 1860032: Running Red Hat images and crashlooping OpenShift pods should be gathered

- test/integration/bugs_test.go
- test/integration/main_test.go
Check if event folder/files appear in the archive after degrading an operator.
Added TestCollectEvents and merged it with TestPodsLogCollected.
https://bugzilla.redhat.com/show_bug.cgi?id=1767719
note: extracting restartInsightsOperator and generalizing it to deleteAllPods is now kinda unrelated to this PR, I needed to restart more operators, but then test steps changed and it wasn’t needed anymore, but I expect it will be useful in the future
> TestCollectingAfterDegradingOperator

- test/integration/bugs_test.go
- test/integration/main_test.go
Added 2 BZs and extracted some patterns of 5 related test cases inside TestArchiveContains
BZ - config maps
https://bugzilla.redhat.com/show_bug.cgi?id=1825756
BZ - image registry
https://bugzilla.redhat.com/show_bug.cgi?id=1834677
> Tests e2e: Automate 2 BZ tests & generalize TestArchiveContainsFiles

- OWNERS
> [release-4.4] Bug 1870512: Add @natiiix to OWNERS

- OWNERS
> [release-4.3] Bug 1874427: Add @natiiix to OWNERS

- README.md
> Bug 1882714: Updates readme

- test/integration/bugs_test.go
https://bugzilla.redhat.com/show_bug.cgi?id=1879068
https://bugzilla.redhat.com/show_bug.cgi?id=1881816
https://bugzilla.redhat.com/show_bug.cgi?id=1873101
> Bug 1882858: Automate TestArchiveContains::HostsSubnet & 2 more

- test/integration/basic_test.go
- test/integration/bugs_test.go
- test/integration/log_checker.go
- test/integration/main_test.go
Added log checker, which is more flexible than old function
> Bug 1882685: Log checker

- Makefile
- pkg/config/configobserver/configobserver_test.go
Picks #103 and updates dependencies
> [release-4.3] Bug 1836815: Gather image registry config

- OWNERS
> Bug 1883160: Add new team members to OWNERS

- OWNERS
Backport of #194, #191 and #187
> Bug 1885261: Add new team members to OWNERS

- manifests/02-namespace.yaml
- manifests/03-clusterrole.yaml
- manifests/03-prometheus_role.yaml
- manifests/03-prometheus_rolebinding.yaml
- manifests/04-proxy-cert-configmap.yaml
- manifests/04-service-ca-configmap.yaml
- manifests/04-serviceaccount.yaml
This matches https://github.com/openshift/enhancements/pull/445 and does
not change behavior.
> Add IBM Cloud managed annotations to CVO manifests

- pkg/record/diskrecorder/diskrecorder.go
This is just an idea how to simplify diskrecorder.go. I believe we don't want to merge existing tar files together and most importantly, there is nothing to merge IMO, because the length of merged slice (https://github.com/openshift/insights-operator/blob/master/pkg/record/diskrecorder/diskrecorder.go#L293) will always be 0 or 1 (due to https://github.com/openshift/insights-operator/blob/master/pkg/record/diskrecorder/diskrecorder.go#L301-L307 note the slice is initialized in the for loop) if I am not mistaken.
> Diskrecorder simplify the Summary function

- test/integration/basic_test.go
Signed-off-by: Pavel Simovec <psimovec@redhat.com>
This PR skips a test that causes CI failures. We check it manually for now.
> Skip TestArchiveUploadedAndResultReceived

- pkg/record/diskrecorder/diskrecorder.go
This is a backport of #246 
[CCXDEV-3429](https://issues.redhat.com/browse/CCXDEV-3429)
> [release-4.6] Bug 1894244: Fixes records index on diskrecorder

- docs/insights-archive-sample/config/hostsubnet/ci-ln-h9vpcgk-f76d1-8zsf5-master-0.json
- docs/insights-archive-sample/config/hostsubnet/ci-ln-h9vpcgk-f76d1-8zsf5-master-1.json
- docs/insights-archive-sample/config/hostsubnet/ci-ln-h9vpcgk-f76d1-8zsf5-master-2.json
- docs/insights-archive-sample/config/hostsubnet/ci-ln-h9vpcgk-f76d1-8zsf5-worker-b-q59xn.json
- docs/insights-archive-sample/config/hostsubnet/ci-ln-h9vpcgk-f76d1-8zsf5-worker-c-7wf2t.json
- docs/insights-archive-sample/config/hostsubnet/ci-ln-h9vpcgk-f76d1-8zsf5-worker-d-7jz4q.json
- pkg/gather/clusterconfig/host_subnets.go
- pkg/gather/clusterconfig/host_subnets_test.go
Remove the HostSubnet anonymization since the decision was no IP anonymization by default to help network troubleshooting. 
- Updated - see `docs/insights-archive-sample/config/hostsubnet/ci-ln-h9vpcgk-f76d1-8zsf5-worker-c-7wf2t.json` and other json files.
No need to update
- Test `host_subnets_test.go` updated
No need to add this to changelog
> Bug 1915188: Remove HostSubnet anonymization

- README.md
Adds docs for using the profiler within IO.
Just docs update
- yeeeeep
Just docs update
Just docs update
Not necessary
none
> Bug 1917371: Adds docs for using the profiler

- Makefile
This PR improves the Makefile maintainability allowing us to quickly replace commands.
No.
No.
None.
It PR doesn't change or collect any data.
No.
> Some charms to Makefile

- cmd/changelog/main.go
This PR fixes some code style and removes some code smells from the changelog tool.
No.
No.
No.
Not applicable.
No.
Not applicable.
> Fixes changelog script code styling

- pkg/controller/periodic/periodic.go
It doesn't make sense to run gathering if the IO is disabled (it will upload nothing).
No new data
No update
We will need a new integration test for this. 
https://issues.redhat.com/browse/CCXDEV-3988
> Do not run gathering when IO is disabled

- pkg/gather/clusterconfig/0_gatherer.go
This PR reduces the `0_gatherer.go` code complexity.
No.
No.
No.
Not applicable.
No.
Not applicable.
> Reduce Gatherer's code complexity

- CHANGELOG.md
- cmd/changelog/main.go
Since we moved to squashing the commits in the PRs the structure of the git log changed a bit, so the changelog script needed a bit of an adjustment.
- none
- none
- none
> Makes changelog script compatible with squash

- pkg/gather/clusterconfig/openshift_authentication_logs.go
> Do not scan all the pod logs in the "GatherOpenshiftAuthenticationLogs"

- cmd/insights-operator/main.go
- pkg/cmd/start/start.go
- pkg/config/config.go
- pkg/controller/gather_job.go
- pkg/controller/operator.go
Introduces a new `gather` command that will run a single gather without any uploading or anything.
- none
- Updated/created docs strings, the actual user documentation is a separate task
-none
> Introduce quick gather command

- docs/gathered-data.md
- pkg/gather/clusterconfig/0_gatherer.go
- pkg/gather/clusterconfig/sap_pods.go
- pkg/gather/clusterconfig/sap_pods_test.go
This is a backport of #347 and #360. It is necessary to get this enhancement to 4.6.z in order to see useful results in a reasonable time because it is the latest OCP release support by the SAP team. The next support release will be 4.8, which may take a considerable amount of time to get to customers' production clusters.
N/A; just like with #347:
> The newly gathered data are JSON pod dumps, which are no different from all the other currently gathered pods. Due to the challenging nature of the SAP enhancement development, it was not possible to properly anonymous sample data.
- `docs/gathered-data.md` - "SAPPods" section
- `pkg/gather/clusterconfig/sap_pods_test.go`
This is just a backport, so it is no different form …
> [release-4.6] Bug 1935775: Gather info about unhealthy SAP pods

- docs/gathered-data.md
- docs/insights-archive-sample/customresources/installers.datahub.sap.com/datahubs/sdi/default.json
- pkg/gather/clusterconfig/0_gatherer.go
- pkg/gather/clusterconfig/sap_datahubs.go
- pkg/gather/clusterconfig/sap_datahubs_test.go
This PR is a backport of #376 and #383, which is another SAP enhancement. Much like the others, this one also has to be backported to 4.6.z for us to see any useful results in a reasonable amount of time.
The presence of the Datahubs resource(s) is used for the identification of SAP (SDI) clusters. As such, it has been decided that it should be collected from all of them in order for the team processing the IO archives to be able to tell SAP clusters apart from the remaining clusters. It is possible that all of the data gathered exclusively from SAP clusters could be missing, in which case it would be impossible to determine if a cluster has an SDI installation or not. This enhancement fixes that issue by gathering a resource that should, universally, be present on all SAP clusters. By …
> [release-4.6] Bug 1942907: Gather datahubs.installers.datahub.sap.com resources from SAP clusters

- pkg/gather/clusterconfig/config_maps.go
- pkg/gather/clusterconfig/config_maps_test.go
No sample archive update.
No documentation
New test added in:
-`pkg/gather/clusterconfig/config_maps_test.go`
> Bug 1951412: Update configmap gatherer to not fail in case of invalid yaml

- .golangci.precommit.yml
- .golangci.yml
- pkg/anonymization/anonymizer.go
- pkg/authorizer/clusterauthorizer/clusterauthorizer.go
- pkg/authorizer/clusterauthorizer/clusterauthorizer_test.go
- pkg/cmd/start/receiver.go
- pkg/cmd/start/start.go
- pkg/config/config.go
- pkg/config/configobserver/configobserver.go
- pkg/config/configobserver/configobserver_test.go
- pkg/controller/operator.go
- pkg/controller/periodic/periodic.go
- pkg/controller/status/status.go
- pkg/controller/status/status_test.go
- pkg/controllerstatus/controllerstatus.go
- pkg/record/memory.go
- pkg/record/record.go
- pkg/recorder/diskrecorder/diskrecorder.go
- pkg/recorder/diskrecorder/diskrecorder_test.go
- pkg/recorder/recorder.go
Goes through the codebase and adds/updates the docs for public functions and fixes the linting issues
- none
- none
- none
> Bug 1951456: Docs and lint fixes

- docs/gathered-data.md
- docs/insights-archive-sample/config/persistentvolumes/task-pv-volume.json
- pkg/gather/clusterconfig/image_registries.go
- pkg/gather/clusterconfig/operators_pods_and_events.go
- pkg/gather/clusterconfig/sap_config.go
- pkg/gather/clusterconfig/sap_pods.go
- pkg/gather/clusterconfig/sap_vsystem_iptables_logs.go
- pkg/gather/clusterconfig/workloads.go
- ` docs/insights-archive-sample/config/persistentvolumes/task-pv-volume.json`
No new test
> Bug 1953543: Add missing sample archive data

- Dockerfile.debug
- Makefile
- pkg/anonymization/anonymizer.go
- pkg/controller/gather_job.go
- pkg/controller/operator.go
Fixed a bug with permissions in obfuscation
https://issues.redhat.com/browse/CCXDEV-4615
> Bug 1960255: fixed obfuscation permissions

- .github/pull_request_template.md
Add a checkmark in the PR template.
> Bug 1960257: breaking changes in pr template

- pkg/gatherers/workloads/workloads_info.go
No new data
No doc update
No test
No
> Bug 1967403: Workloads gatherer - increase the pods limit

- pkg/gatherers/clusterconfig/gather_logs.go
This PR fixes a nil reference to a variable at the `gather_logs.go` that could cause some issues.
No.
No.
No.
No.
https://bugzilla.redhat.com/show_bug.cgi?id=1967843
> Bug 1967843: Fixes one small bug

- docs/gathered-data.md
- pkg/gatherers/clusterconfig/recent_metrics.go
No new data
Updating:
No new test
No
> Update versions in the metrics gather documentation

- manifests/03-clusterrole.yaml
- pkg/anonymization/anonymizer.go
- pkg/anonymization/anonymizer_test.go
- pkg/controller/gather_job.go
- pkg/controller/operator.go
- pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
- [] Enhancement
No changes
No changes
No changes
No changes
No changes
No
https://issues.redhat.com/browse/CCXDEV-4481
> fix obfuscation translation table secret

- OWNERS
Bye bye Marcell!!!
No new data
No doc
No new tests
No
> Updating the owners list

- .openshiftci/check-coverage.sh
- Makefile
- check-coverage.sh
- pkg/gather/tasks_processing_test.go
just a few unit tests
No changes
No changes
- `pkg/gather/tasks_processing_test.go`
No new data was collected, it's just unit tests. 
No
No
https://issues.redhat.com/browse/CCXDEV-4868
> cover tasks_processing.go better

- .editorconfig
- manifests/03-clusterrole.yaml
- manifests/image-references
Fixed manifests and tested by doing `oc apply -f 03-clusterrole.yaml` and deploying my own image with the latest version of the code.
No
No
No
No
No
No
https://issues.redhat.com/browse/CCXDEV-4481
> fix obfuscation translation table secret manifest

- OWNERS
> Bye bye Pavel

- manifests/03-clusterrole.yaml
No new data
No update
No new test
No
https://bugzilla.redhat.com/show_bug.cgi?id=1975542
> Bug 1975542: remove the redundant role & rolebinding definition

- pkg/gatherers/clusterconfig/const.go
- pkg/gatherers/clusterconfig/operators_pods_and_events.go
- pkg/gatherers/clusterconfig/operators_pods_and_events_test.go
- pkg/utils/math.go
No
https://issues.redhat.com/browse/CCXDEV-5416
> Reduce stacktrace size in logs

- docs/gathered-data.md
- docs/insights-archive-sample/config/cost_management_metrics_configs/00-basic.json
- docs/insights-archive-sample/config/cost_management_metrics_configs/00-token.json
- manifests/03-clusterrole.yaml
- pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
- pkg/gatherers/clusterconfig/const.go
- pkg/gatherers/clusterconfig/cost_management_metrics_configs.go
- pkg/gatherers/clusterconfig/cost_management_metrics_configs_test.go
This PR gathers all the CostManagementMetricsConfigs custom resources.
TBD
Updated in docs/gathered-data.md
Add in:
pkg/gatherers/clusterconfig/cost_management_metrics_configs_test.go
No
https://issues.redhat.com/browse/CCXDEV-6197
> Gather all CostManagementMericsConfig definitions.

- manifests/03-clusterrole.yaml
No new data
No doc update
No new test
Yes/No
> Fix cost management metric resource name

- docs/gathered-data.md
- pkg/gatherers/clusterconfig/pod_security_policies.go
Minor doc fix
No new data
Minor update in
Not needed
No
> Update documentation for PSP gatherer

- pkg/gatherers/workloads/workloads_info.go
This increases the original limit  for 6000 pods to 8000 pods
No update
No docs
No new test
Yes/No
https://issues.redhat.com/browse/CCXDEV-6203
> workloads info - increase the pods limit a bit

- pkg/gather/clusterconfig/pod_disruption_budgets.go
Fix serialization of the PDBs so that the content of the last PDB doesn't repeat in every PDB record.
No new data
No update
No new test
Yes/No
https://bugzilla.redhat.com/show_bug.cgi?id=2026410
> [release-4.7] Bug 2026410: Fix PDB gatherer

- docs/gathered-data.md
- pkg/gatherers/clusterconfig/cost_management_metrics_configs.go
Updating OCP versions for the cost metrics gatherer
No new data
No new test
No
> Minor gathering docs update

- docs/gathered-data.md
- pkg/gatherers/clusterconfig/feature_gates.go
- pkg/gatherers/clusterconfig/ingresses.go
- pkg/gatherers/clusterconfig/proxies.go
> fix some docs

- docs/gathered-data.md
- pkg/gatherers/clusterconfig/image.go
- pkg/gatherers/clusterconfig/kube_controller_manager_logs.go
> Minor gatherer documentation update

- docs/gathered-data.md
- pkg/gatherers/clusterconfig/namespaces_with_overlapping_uids.go
Minor update of the OCP version in new gatherer
No new data
- [gathering docs updated](https://github.com/openshift/insights-operator/compare/master...tremes:doc_versions?expand=1#diff-af75e5b22f25c37be5653ee0c3ac041d589e78c78e5c5c7b651c923055bf55b5l)
No
No
> Update new gatherer OCP versions

- Makefile
- docs/gathered-data.md
- pkg/gatherers/clusterconfig/machine_healthcheck.go
- pkg/gatherers/clusterconfig/machine_sets.go
* Updates links to machine-api types, current links are not actual anymore and leads to 404
*  fixes `make help`.
No
None
No changes there
No
No
None
> Update links to machine-api types

- docs/gathered-data.md
- docs/insights-archive-sample/config/secrets/openshift-config/support/data.json
- pkg/config/configobserver/configobserver.go
- pkg/gather/gather.go
- pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
- pkg/gatherers/clusterconfig/clusterconfig_gatherer_test.go
- pkg/gatherers/clusterconfig/support_secret.go
- pkg/gatherers/clusterconfig/support_secret_test.go
- pkg/utils/anonymize/string.go
- `docs/insights-archive-sample/config/secrets/openshift-config/support/data.json`
- `docs/insights-archive-sample/insights-operator/config/combined.json`
- `docs/insights-archive-sample/insights-operator/config/from_secret.json`
Yes. The data is anonymized.
No
No
https://issues.redhat.com/browse/CCXDEV-7877
> gather io configuration

- pkg/insights/insightsclient/insightsclient.go
Minor fix of error message formatting
No new data
No docs
No
> insightsclient - do not format OCM error message twice

- README.md
- docs/arch.md
- pkg/insights/insightsclient/insightsclient.go
This PR improves the documentation about metrics and alerts for Insights.
N/A
- `README.md`
- `docs/arch.md`
N/A
N/A
No
https://issues.redhat.com/browse/CCXDEV-7975
> chore(docs): adding list of insights generated metrics

- OWNERS
- docs/gathered-data.md
- pkg/gatherers/clusterconfig/namespaces_with_overlapping_uids.go
No new data
Minor version update
No test
Yes/No
> Minor gatherer's docs & OWNERS update

- pkg/config/config.go
- pkg/config/configobserver/config.go
- pkg/insights/insightsreport/insightsreport.go
..
No new data
This will require new OCP docs
No
> Enable Insights recommendations as alerts by default

- manifests/02-namespace.yaml
- manifests/03-clusterrole.yaml
- manifests/03-prometheus_role.yaml
- manifests/03-prometheus_rolebinding.yaml
- manifests/04-proxy-cert-configmap.yaml
- manifests/04-service-ca-configmap.yaml
- manifests/04-serviceaccount.yaml
- manifests/05-service.yaml
- manifests/06-deployment-ibm-cloud-managed.yaml
- manifests/06-deployment.yaml
- manifests/07-cluster-operator.yaml
- manifests/07-servicemonitor.yaml
- manifests/08-prometheus_rule.yaml
This PR modifies the manifests by adding the capability annotations to it.
n/a
n/a
n/a
n/a
No
https://issues.redhat.com/browse/CCXDEV-8504
> chore(manifests): adding insights capability annotations

- docs/conditional-gatherer/README.md
- pkg/gatherers/conditional/conditional_gatherer.go
- pkg/gatherers/conditional/validation.go
- pkg/gatherers/conditional/validation_test.go
- `pkg/gatherers/conditional/validation_test.go`
No
https://issues.redhat.com/browse/CCXDEV-8548
> updated conditional gathering rules checking

- OWNERS
> Update owners list

- pkg/gatherers/conditional/gathering_rule.schema.json
no new data
no docs update
will be tested in the integration tests
No
> OCPBUGS-2249: fix the schema checking conditional gathering rules

- pkg/gatherers/workloads/workloads_info.go
> refactor(workloads_info): reduce cognitive complexity

- pkg/gather/gather.go
> Use cgroups memory usage data in the archive metadata

- pkg/gather/gather.go
- pkg/gatherers/conditional/gathering_rule.schema.json
- pkg/gatherers/workloads/workloads_info.go
- pkg/insights/insightsclient/insightsclient.go
- pkg/insights/insightsclient/requests.go
- pkg/insights/insightsreport/insightsreport.go
- pkg/insights/insightsreport/insightsreport_test.go
- pkg/insights/metrics.go
> Updating stage branch

- .github/pull_request_template.md
- CHANGELOG.md
- README.md
- cmd/changelog/main.go
This PR implements a new PR template and updates CHANGELOG
There are no sensitive data in the newly collected information.
No
https://issues.redhat.com/browse/CCXDEV-9402
> PR template preview and changelog update

- OWNERS
> Update operator name in the OWNERS file

- pkg/controller/status/controller.go
- pkg/controller/status/controller_test.go
Reverts openshift/insights-operator#716 ; tracked by [TRT-776](https://issues.redhat.com//browse/TRT-776)
Per [OpenShift policy](https://github.com/openshift/enhancements/blob/master/enhancements/release/improving-ci-signal.md#quick-revert), we are reverting this breaking change to get CI and/or nightly payloads flowing again.
This change is breaking nightly 4.13 payloads:
https://amd64.ocp.releases.ci.openshift.org/releasestream/4.13.0-0.nightly/release/4.13.0-0.nightly-2023-01-12-061342 
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ipi-ovn-ipv6/1613507709083062272 
To unrevert this, revert this PR, and layer an additional separate commit on top that addresses the problem. Before merging the unrevert, please run …
> Revert "OCPBUGS-5347: additional fix"

- Makefile
- pkg/controller/periodic/periodic_test.go
Updates `periodic_test.go` to be more robust and readable and also adds `-race` param to unit tests make target.
- no new data
- `pkg/controller/periodic/periodic_test.go`
Yes/No
> update periodic_test.go & run unit tests with -race param

- pkg/cmd/start/start.go
- pkg/config/config.go
- pkg/config/config_test.go
- [ X) Bugfix
no new data
added
- `pkg/config/config_test.go`
No
https://issues.redhat.com/browse/OCPBUGS-14937
> OCPBUGS-14937: fix the config serialization & add test

- pkg/controller/gather_commands.go
- pkg/controller/periodic/periodic.go
- pkg/ocm/sca/sca.go
Minor fixes for the techpreview data gathering 
no new data
no update
no update
No
> Minor fixes for the techpreview

- pkg/insights/insightsreport/insightsreport.go
Do not log the complete config
No
https://issues.redhat.com/browse/OCPBUGS-19476
> OCPBUGS-19476: update Insights report config logging

- docs/insights-archive-sample/config/workload_info.json
- pkg/gatherers/workloads/types.go
- pkg/gatherers/workloads/workloads_info.go
- pkg/gatherers/workloads/workloads_info_test.go
This is manual cherry-pick of #811
> [release-4.11] OCPBUGS-19946: workload info gatherer, add external image repo

- .openshiftci/install-golangci-lint.sh
- docs/gathered-data.md
- docs/insights-archive-sample/config/apiserver.json
- pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
- pkg/gatherers/clusterconfig/gather_cluster_apiserver.go
- pkg/gatherers/clusterconfig/gather_cluster_apiserver_test.go
This is a manual cherry-pick of #825
> [release-4.14] OCPBUGS-20590: gather APIServer.config.openshift.io resource

- manifests/03-clusterrole.yaml
- pkg/config/configobserver/config_aggregator.go
- pkg/config/configobserver/config_aggregator_test.go
- pkg/config/configobserver/configmapobserver.go
- pkg/config/mock_configurator.go
- pkg/config/types.go
- pkg/controller/gather_commands.go
- pkg/controller/gather_commands_test.go
- pkg/controller/operator.go
- pkg/controller/periodic/periodic.go
- pkg/controller/periodic/periodic_test.go
- pkg/gather/gather.go
- pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
- pkg/gatherers/clusterconfig/gather_support_secret.go
- pkg/gatherers/clusterconfig/gather_support_secret_test.go
- pkg/gatherers/conditional/conditional_gatherer.go
- pkg/gatherers/conditional/conditional_gatherer_test.go
- pkg/insights/insightsuploader/insightsuploader.go
> fix the reverted configmap PR

- docs/gathered-data.md
- docs/insights-archive-sample/config/apiserver.json
- pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
- pkg/gatherers/clusterconfig/gather_cluster_apiserver.go
- pkg/gatherers/clusterconfig/gather_cluster_apiserver_test.go
This is a manual cherry-pick of #825
> [release-4.13] OCPBUGS-22330: gather APIServer.config.openshift.io resource

- manifests/03-clusterrole.yaml
- pkg/config/configobserver/config_aggregator.go
- pkg/config/configobserver/config_aggregator_test.go
- pkg/config/configobserver/configmapobserver.go
- pkg/config/mock_configurator.go
- pkg/config/types.go
- pkg/controller/gather_commands.go
- pkg/controller/gather_commands_test.go
- pkg/controller/operator.go
- pkg/controller/periodic/periodic.go
- pkg/controller/periodic/periodic_test.go
- pkg/gather/gather.go
- pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
- pkg/gatherers/clusterconfig/gather_support_secret.go
- pkg/gatherers/clusterconfig/gather_support_secret_test.go
- pkg/gatherers/conditional/conditional_gatherer.go
- pkg/gatherers/conditional/conditional_gatherer_test.go
- pkg/insights/insightsuploader/insightsuploader.go
Reverting the previous revert and providing fix
Yes/No
> Revert the previous revert and fix

- docs/gathered-data.md
- docs/insights-archive-sample/config/apiserver.json
- pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
- pkg/gatherers/clusterconfig/gather_cluster_apiserver.go
- pkg/gatherers/clusterconfig/gather_cluster_apiserver_test.go
This is a manual cherry-pick of #825
> [release-4.12] OCPBUGS-22435: gather APIServer.config.openshift.io resource

- docs/gathered-data.md
- docs/insights-archive-sample/config/apiserver.json
- pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
- pkg/gatherers/clusterconfig/gather_cluster_apiserver.go
- pkg/gatherers/clusterconfig/gather_cluster_apiserver_test.go
This is a manual cherry-pick of #825
> [release-4.11] OCPBUGS-22763: gather APIServer.config.openshift.io resource

- manifests/06-deployment-ibm-cloud-managed.yaml
- manifests/06-deployment.yaml
- profile-patches/ibm-cloud-managed/06-deployment.yaml-patch
> NO-JIRA: update nodeSelector key in the deployment manifests

- cmd/changelog/main.go
> OCPBUGS-26188: another attempt to fix security warning for changelog script

- .snyk
- cmd/changelog/main.go
- [] Data Enhancement
No
No
https://issues.redhat.com/browse/OCPBUGS-26937
> OCPBUGS-26937: Add extra check in ids to bypass validations

- manifests/03-clusterrole.yaml
> NO-JIRA: add permission for prometheus to be able to read metrics

- .snyk
- cmd/changelog/main.go
> [release-4.14] OCPBUGS-24698: Add extra check in ids to bypass validations

- pkg/config/configobserver/secretconfigobserver.go
- pkg/config/legacy_config.go
- pkg/controller/status/controller.go
- pkg/controllerstatus/controllerstatus.go
- pkg/insights/insightsclient/requests.go
- pkg/insights/insightsreport/insightsreport.go
- pkg/insights/insightsuploader/insightsuploader.go
- pkg/recorder/diskrecorder/diskrecorder.go
- pkg/recorder/recorder.go
> NO-JIRA: adjust loglevel for  some further messages

- pkg/config/configobserver/config.go
- pkg/gatherers/conditional/conditions.go
- pkg/gatherers/conditional/conditions_test.go
> NO-JIRA: (refactor) reduce cognitive and adding unit tests

- OWNERS
> NO-JIRA: update OWNERS list

- pkg/controller/gather_commands.go
- pkg/controller/gather_commands_test.go
- pkg/controller/operator.go
- pkg/controller/periodic/job.go
- pkg/controller/periodic/periodic.go
- pkg/controller/periodic/periodic_test.go
- pkg/controller/status/conditions.go
- pkg/controller/status/conditions_test.go
- pkg/controller/status/controller.go
- pkg/controller/status/controller_test.go
- pkg/controller/status/datagather_status.go
- pkg/controller/status/status.go
- pkg/controller/status/status_test.go
- pkg/controllerstatus/controllerstatus.go
- pkg/gather/gather.go
- pkg/gatherers/conditional/conditional_gatherer.go
- pkg/gatherers/conditional/conditional_gatherer_test.go
- pkg/gatherers/conditional/default_remote_configuration.json
- pkg/gatherers/conditional/filter_and_gather_container_logs.go
- pkg/gatherers/conditional/filter_and_gather_container_logs_test.go
- pkg/gatherers/conditional/parsing.go
- pkg/gatherers/conditional/parsing_test.go
- pkg/gatherers/conditional/types.go
- pkg/insights/insightsclient/requests.go
- pkg/insights/insightsclient/requests_test.go
- pkg/insights/insightsreport/insightsreport.go
- pkg/insights/insightsreport/insightsreport_test.go
- pkg/utils/errors.go
- pkg/utils/errors_test.go
This changes the original conditional gathering (including the endpoint) to consume new content including these so called "container log requests", which are basically requests for what Pod and what log messages we are interested in. 
This includes following technical changes:
- add new `rapid_container_logs` gathering function to the existing conditional gatherer (impl is `pkg/gatherers/conditional/filter_and_gather_container_logs.go`)
-  default "buil-in" remote configuration (with empty `container_logs` for no) when the connection to the remote service fails or is not available
- new clusteroperator conditions - `RemoteConfigurationAvailable` and `RemoteConfigurationValid` providing status about availability and validity of the remote configuration content
- changes are also required …
> CCXDEV-12582: rapid recommendations with new status condition

- pkg/gatherers/conditional/conditional_gatherer.go
- pkg/gatherers/conditional/conditional_gatherer_test.go
- pkg/gatherers/conditional/container_log.schema.json
- pkg/gatherers/conditional/container_logs.schema.json
- pkg/gatherers/conditional/parsing.go
- pkg/gatherers/conditional/validation.go
> NO-JIRA: introduce JSON schema & validation for rapid container logs

- pkg/config/configobserver/configmapobserver.go
Yes/No
https://issues.redhat.com/browse/OCPBUGS-37100
> OCPBUGS-37100: fix the configmapobserver notifications

- config/pod.yaml
- pkg/gatherers/conditional/filter_and_gather_container_logs.go
> NO-JIRA: limit the time for the new rapid container logs & update the endpoint

- DoD.md
> NO-JIRA: add definition of done

- CHANGELOG.md
- docs/gathered-data.md
- pkg/gatherers/clusterconfig/gather_aggregated_instances.go
This PR updates documentation of GatherAggregatedMonitoringCRNames gatherer with the correct versions of its backports. There were erratas confirmed.
Yes
No
> NO-JIRA: Update docs for GatherAggregatedMonitoringCRNames with backport versions

- manifests/03-clusterrole.yaml
This fixes previous PR #976 
Yes/No
https://issues.redhat.com/browse/OCPBUGS-37673
> [release-4.14] OCPBUGS-37673: Missing cluster role

- manifests/03-clusterrole.yaml
> OCPBUGS-39111: add missing permission to get nmstate CRs

- docs/arch.md
> NO-JIRA: update docs/arch.md to mention the Rapid Recommendations

- CHANGELOG.md
> NO-JIRA: changelog update

- pkg/gatherers/conditional/container_log.schema.json
> NO-JIRA: container log JSON schema - minor description update

- Dockerfile
- Makefile
This is a PR to test in the CI the availability of the new build flags in the existing compiler and base images and to check the result of the build in the existing build infra.
N/A
N/A
N/A
Yes. There are no new collected information
No
No
> NO-JIRA: Updating build options in order to ensure FIPS compliant build

- pkg/gatherers/conditional/filter_and_gather_container_logs.go
- pkg/gatherers/conditional/filter_and_gather_container_logs_test.go
- pkg/gatherers/conditional/types.go
no new data
Yes/No
https://issues.redhat.com/browse/OCPBUGS-42961
> OCPBUGS-42961: update the filtering of the container logs

- pkg/gatherers/conditional/conditional_gatherer_test.go
Extend test cases for conditional gathering to include server known error codes.
> NO-JIRA: Add gather server error known codes to the checks

- docs/gathered-data.md
- docs/insights-archive-sample/config/certificatesigningrequests/csr-test.json
- docs/insights-archive-sample/config/pod/di-288312/auditlog-retention-28566720-t22qj.json
- docs/insights-archive-sample/config/pod/di-288312/data-hub-flow-agent-1a3a7e88888b7fe0630189-qcwhm-547b57cc5fvmg8.json
- docs/insights-archive-sample/config/pod/di-288312/default-2k58azz-backup-deletion-5rdw4.json
- docs/insights-archive-sample/config/pod/di-288312/vsystem-867f4b77cc-pqcns.json
- pkg/gatherers/clusterconfig/gather_certificate_signing_requests.go
- pkg/gatherers/clusterconfig/gather_cluster_operator_pods_and_events.go
- pkg/gatherers/clusterconfig/gather_machine_configs.go
- pkg/gatherers/clusterconfig/gather_sap_pods.go
- `docs/insights-archive-sample/config/certificatesigningrequests/csr-test.json`
- 
No
> NO-JIRA: add/update some missing sample data

- pkg/controller/periodic/job.go
> AUTH-482: set required-scc for dataGahtering jobs & pods

- docs/gathered-data.md
- docs/insights-archive-sample/namespaces/openshift-logging/lokistack-sample.json
- manifests/03-clusterrole.yaml
- pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
- pkg/gatherers/clusterconfig/const.go
- pkg/gatherers/clusterconfig/gather_lokistack.go
- pkg/gatherers/clusterconfig/gather_lokistacks_test.go
This is a manual cherry-pick of #1022 and #1043 
/assign openshift-ci-robot
> [release-4.18] OCPBUGS-45201: LokiStack gatherer

- pkg/gatherers/conditional/filter_and_gather_container_logs_test.go
> NO-JIRA: minor test update

- pkg/gatherers/workloads/gather_workloads_runtime_infos.go
- no new data
No
https://issues.redhat.com/browse/OCPBUGS-45926
> OCPBUGS-45926: use joinHostPort to fix IPv6

- docs/gathered-data.md
- docs/insights-archive-sample/namespaces/openshift-logging/lokistack-sample.json
- manifests/03-clusterrole.yaml
- pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
- pkg/gatherers/clusterconfig/const.go
- pkg/gatherers/clusterconfig/gather_lokistack.go
- pkg/gatherers/clusterconfig/gather_lokistacks_test.go
This is a manual cherry-pick of https://github.com/openshift/insights-operator/pull/1022 and https://github.com/openshift/insights-operator/pull/1043
/assign openshift-ci-robot
> [release-4.17] OCPBUGS-45202: LokiStack gatherer

- docs/gathered-data.md
- docs/insights-archive-sample/namespaces/openshift-logging/lokistack-sample.json
- manifests/03-clusterrole.yaml
- pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
- pkg/gatherers/clusterconfig/const.go
- pkg/gatherers/clusterconfig/gather_lokistack.go
- pkg/gatherers/clusterconfig/gather_lokistacks_test.go
This is a manual cherry-pick of #1022 and #1043
/assign openshift-ci-robot
> [release-4.15] OCPBUGS-45204: LokiStack gatherer

- OWNERS
Adding Ondrej username to the OWNERS file
> NO-JIRA: Add Ondrej user to OWNERS file

- OWNERS
This PR adds BaiyangZhou to OWNERS file
None
None
None
None
No
> NO-JIRA: add BaiyangZhou to OWNERS file

- cmd/obfuscate-archive/main.go
- manifests/03-insightsdatagather-config-crd.yaml
- manifests/04-datagather-insights-crd.yaml
- manifests/04-insightsdatagather-config-cr.yaml
- pkg/anonymization/anonymizer.go
- pkg/anonymization/anonymizer_test.go
- pkg/anonymization/builder.go
- pkg/anonymization/builder_test.go
- pkg/config/configobserver/insighgtsdatagather_observer.go
- pkg/config/configobserver/insightsdatagather_observer_test.go
- pkg/config/mock_configurator.go
- pkg/controller/gather_commands.go
- pkg/controller/operator.go
- pkg/controller/periodic/datagather_informer.go
- pkg/controller/periodic/job.go
- pkg/controller/periodic/job_test.go
- pkg/controller/periodic/mock_periodic.go
- pkg/controller/periodic/periodic.go
- pkg/controller/periodic/periodic_test.go
- pkg/controller/status/controller_test.go
- pkg/controller/status/datagather_status.go
- pkg/controller/status/datagather_status_test.go
- pkg/controller/status/gatherer_status.go
- pkg/controller/status/gatherer_status_test.go
- pkg/gather/gather.go
- pkg/gather/gather_test.go
- pkg/recorder/recorder_test.go
This PR is updating all the code that is using the api and client packages from v1alpha1 to v1alpha2 version.
- None
- None
- Multiple tests were updated.
Yes
https://issues.redhat.com/browse/CCXDEV-15045
> CCXDEV-15045: update code to use v1alpha2 api version

- docs/arch.md
This PR is updating the information about how to enable or disable the gathering with the use of the InsightsDataGather CRD.
- None
- None
- None
- None
No
[CCXDEV-15041](https://issues.redhat.com/browse/CCXDEV-15041)
> CCXDEV-15041: update on-demand gathering docs

- pkg/controller/periodic/job.go
- pkg/controller/periodic/job_test.go
This is a manual cherry-pick of https://github.com/openshift/insights-operator/pull/1094.
> [release-4.17] OCPBUGS-59753: copy proxy envs from IO pod to gathering pods

- OWNERS
> NO-JIRA: remove me from the OWNERS list

- manifests/06-deployment-ibm-cloud-managed.yaml
- profile-patches/ibm-cloud-managed/06-deployment.yaml-patch
Similar to https://github.com/openshift/insights-operator/pull/1122, but keeps the label who's removal was causing issues
> OCPBUGS-61798: Run missing make update
