- pkg/authorizer/clusterauthorizer/clusterauthorizer.go
- pkg/config/configobserver/configobserver.go
- pkg/insights/insightsclient/insightsclient.go
If the token for the cluster contains a newline, the error is
reported in a generic fashion to the cluster operator status which
contains the auth token value. This is an information leak and
should not happen.
Prevent future disclosure bugs by not printing the exact error when
we build an invalid request. Check the token value in both the client
(before setting the header) and when we read from config (before
loading the token) so that we report this error in an earlier place
with a specific error.
To reproduce, put a newline inside the cloud.openshift.com token in
the cluster pull-secret (in openshift-config namespace).
/assign @mfojtik
> Bug 1738495: Invalid token is reported as error in cluster status

- pkg/controller/status/status.go
Until we figure out why [we're getting 415s][1] from https://cloud.redhat.com/api/ingress/v1/upload just pretend everything's fine to unstick upgrade CI.
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1744297
> Bug 1744297: pkg/controller/status/status: Never go degraded (hack)

- manifests/04-proxy-cert-configmap.yaml
- manifests/05-deployment.yaml
- pkg/controller/operator.go
- pkg/insights/insightsclient/insightsclient.go
This wire the proxy certs into operator and enable proxy vars injections. The insights client then use transport that has the correct trust set.
@danehans i think we missed this one.
/cc @smarterclayton @iNecas
> Provide initial proxy support for insights operator

- pkg/controller/operator.go
- pkg/gather/clusterconfig/clusterconfig.go
- pkg/record/diskrecorder/diskrecorder.go
- pkg/record/interface.go
While testing the insights-operator, I've noticed a lot of messages like
this:
```
E0828 14:22:05.301631   28307 diskrecorder.go:186] Tried to copy to insights-2019-08-28-122158.tar.gz which already exists
E0828 14:22:35.301368   28307 diskrecorder.go:186] Tried to copy to insights-2019-08-28-122228.tar.gz which already exists
```
There seemed to be two problems:
1. the fingerprints not being set while the clearRecords method was
not clearing the data when fingerprint was empty
2. the race condition of gathering and flushing the data
The main source of the messages seemed to be the 2nd case. What seemed
to happen was the flushing happening in the middle of the gathering
phase, leading to couple of records from the same time being left for
the next flushing. During the next flush, the old …
> Synchronize gathering and flushing

- pkg/controller/operator.go
- pkg/controller/periodic/periodic.go
- pkg/gather/clusterconfig/clusterconfig.go
- pkg/record/interface.go
- pkg/record/interface_test.go
A failing node has significant information for understanding why the node is failed. Anonymize most information on the node and return it when it is marked as NotReady.
Moves recorder flush to the gatherer under the same execution context.
> gather: Capture failing nodes during gather pass

- pkg/controller/operator.go
- pkg/controller/periodic/periodic.go
- pkg/gather/clusterconfig/clusterconfig.go
- pkg/record/interface.go
- pkg/record/interface_test.go
Pods that are failing within namespaces referenced by cluster operators that are degraded or unavailable should be returned in order to get termination messages or other status conditions that will assist in debugging seriously broken clusters.
First commit is from #14
> gather: Capture failing pods from broken operators during gather pass

- pkg/controller/status/status.go
- pkg/controllerstatus/controllerstatus.go
- pkg/insights/insightsuploader/insightsuploader.go
Given the upload failures are outside of control of the OCP administrator
and they are not fatal for the the functionality of the cluster,
don't set the cluster as degraded for the upload failures.
Separate stats "Uploading" is introduce to indicate the health of the
upload process.
> Bug 1745973: Don't reported Degraded on upload error, report UploadDegraded

- Makefile
- README.md
Sometimes it might be necessary to specify CLI options for unit tests.
> Unit test options

- pkg/gather/clusterconfig/clusterconfig.go
In case a container is restarting or has restart count higher than zero, consider it not healthy and copy it to the report in case the related operator is degraded.
> gather: consider restarting pods as not healthy

- manifests/03-clusterrole.yaml
- pkg/gather/clusterconfig/clusterconfig.go
Collect all events for `openshift-` namespaces that are not older than 1 hour (for starter). The events are compacted to minimize the size in payload. If we still see big file, we can tweak the 1h interval to 30 min.
> gather: include events in report

- pkg/insights/insightsclient/insightsclient.go
Api to metrics service has been changed suddenly without our knowledge, causing metrics to not be registered anymore, therefore this change is needed to resolve the issue.
> api to metrics service changed from prometheus to legacyregistry

- manifests/05-service.yaml
- manifests/06-deployment.yaml
- manifests/07-cluster-operator.yaml
- manifests/07-servicemonitor.yaml
Enables the CVO to exclude manifests in an externally hosted control plane deployment
See https://github.com/openshift/cluster-version-operator/pull/252
> Add manifest annotations for hosted deployment exclusions

- pkg/gather/clusterconfig/clusterconfig.go
Backport of https://github.com/openshift/insights-operator/pull/36
This allows insights operator to collect 1h of events for namespaces defined as relatedObjects when operators is observed as degraded=true.
> Bug 1767719: gather: include network events for namespace that has degraded operator

- manifests/03-clusterrole.yaml
- pkg/gather/clusterconfig/clusterconfig.go
The previous backport only backported the network events capture, not all events. This will revert the previous backport and pick the correct commits from release-4.3.
> Bug 1767719: Fix the event reporting in insights operator

- Makefile
- test/integration/bugs_test.go
- test/integration/main_test.go
Output locally
```
$ go test ./test/integration
ok      github.com/openshift/insights-operator/test/integration 10.722s
```
> initial commit for tests

- manifests/02-namespace.yaml
To ensure the deployment works properly in case of default node selector
is set.
> Bug 1782151 - override node selector

- pkg/insights/insightsclient/insightsclient.go
We see 'Unable to report: unable to build request to connect to Insights server' message reported as reason for degraded insights operator, but we don't know why (probably bad token?).
@iNecas @smarterclayton is there a reason we muted the error we use for degraded message?
> insightsclient: include error message when we are unable to build request

- Makefile
- test/integration/basic_test.go
- test/integration/bugs_test.go
- test/integration/main_test.go
added test to verify insights operator reports degraded after 5 unsuccessful upload attempts
> Bug 1797563: added TestUnreachableHost

- manifests/02-namespace.yaml
To ensure the deployment works properly in case of default node selector
is set.
(cherry picked from commit 53cfc74e5b5edf7fb3fc192080ee4d7299d5ad96)
> Bug 1788116: override node selector (4.2)

- manifests/02-namespace.yaml
To ensure the deployment works properly in case of default node selector
is set.
(cherry picked from commit 53cfc74e5b5edf7fb3fc192080ee4d7299d5ad96)
> Bug 1788112: override node selector (4.3)

- pkg/insights/insightsclient/insightsclient.go
added metric status code '0' to indicate failed request builds
> Insightsclient metrics - small bugfix , added status code '0'.

- Dockerfile
I believe insights-operator should use a base image which corresponds to OCP version.
> Updated base image for insights-operator

- manifests/02-namespace.yaml
Insights should follow normal admission control rules for a cluster.
> manifests: Remove run-level, insights operator does not need it

- pkg/config/configobserver/configobserver.go
- pkg/config/configobserver/configobserver_test.go
The test should run ConfigObserver and check if it watches changes in mocked kubernetes Secrets.
Bugzilla issue [1753755 - insights-operator recorder does not respect override interval](https://bugzilla.redhat.com/show_bug.cgi?id=1753755)
> Add test to observe config changes

- test/integration/basic_test.go
- test/integration/bugs_test.go
- test/integration/main_test.go
The test is failing quite often and I suspect the problem is quite hidden in pod logs. I wanted to see what is the exact problem and adding the output of actual logs for it.
This is increasing timeouts of our e2e tests to double. It looks the environment is now very slow and we just need to be patient.
> Report logs when checkPods is going to fail

- go.mod
- pkg/authorizer/clusterauthorizer/clusterauthorizer.go
- pkg/authorizer/clusterauthorizer/clusterauthorizer_test.go
- pkg/config/config.go
- pkg/config/configobserver/configobserver.go
- pkg/insights/insightsclient/insightsclient.go
- vendor/golang.org/x/net/http/httpproxy/proxy.go
- vendor/modules.txt
This change allows to override proxy passed with Env using support secret.
It uses golang build-in proxy settings, including noproxy logic.
> Support for specific http proxy for the service

- go.mod
- go.sum
- pkg/authorizer/clusterauthorizer/clusterauthorizer.go
- pkg/authorizer/clusterauthorizer/clusterauthorizer_test.go
- pkg/config/config.go
- pkg/config/configobserver/configobserver.go
- pkg/insights/insightsclient/insightsclient.go
- pkg/insights/insightsclient/insightsclient_test.go
- test/integration/basic_test.go
- test/integration/bugs_test.go
- test/integration/main_test.go
- vendor/golang.org/x/net/http/httpproxy/proxy.go
- vendor/modules.txt
Cherry-pick support for specific http proxy
Obviously I wasn't successful with squashing the commits here, so I had to cherry pick them manually this time.
> Bug 1820633: Cherry-pick release 4.4 Support for specific http proxy for the service

- Makefile
- pkg/config/configobserver/configobserver_test.go
This is just to unblock the merge, I know this is not the solution, I would like to investigate properly later.
> Increase tests timeout and ignore failing tests

- manifests/04-service-ca-configmap.yaml
- manifests/06-deployment.yaml
- pkg/cmd/start/start.go
- pkg/controller/operator.go
> Bug 1813894: Stop using service ca from service account token

- docs/gathered-data.md
- manifests/03-clusterrole.yaml
- pkg/gather/clusterconfig/clusterconfig.go
- pkg/gather/clusterconfig/clusterconfig_test.go
Adding cluster's Image Registry pruner configuration to gather.
> Bug 1837967: Gathering Image Pruner configuration

- pkg/gather/clusterconfig/clusterconfig.go
- pkg/gather/clusterconfig/csr.go
- pkg/record/diskrecorder/diskrecorder.go
- pkg/record/interface.go
`Marshalable` interface is extended to provide a file extension. It 
is being appended to the files when these are written to disk. Openshift/kube object serializers are writing json data, configmap / id serializers are writing plain bytes etc.
If marshaller returns empty string no extension is appended.
Ref: CCXDEV-1366
> Bug 1838969: pkg/record/diskrecorder/diskrecorder: add json extension 

- pkg/controller/status/status.go
- pkg/controller/status/status_test.go
- pkg/insights/insightsuploader/insightsuploader.go
If the operator is started for the first time, or if it is not degraded, it will upload the collected data immediately after they are collected.
This is removing the original initial jitter delay between periods. Consequent runs will still be jittered. The 15 seconds detection of data to send is still there even for initial run, so the data should arrive in 15 seconds after they are collected (few seconds).
> Bug 1841057: Skip the initial upload delay

- docs/insights-archive-sample/config/clusteroperator/insights
- pkg/controller/status/status.go
- pkg/gather/clusterconfig/testdata/clusteroperators.json
We've been light on reasons for expected conditions like `Progressing=False` since 80ab9237bc.  But if we feel like we have a message we want to set to help humans understand the condition, we should be setting a reason string for machines too.  `AsExpected` follows [the library-go precedent][1].
The `Degraded` reason I'm adding here isn't a great fit for a progressing reason, but does match the current logic used to set `Progressing=True`.  The insights operator doesn't actually supply any in-cluster APIs beyond ClusterOperator as far as I can tell, so it's not clear to me what sort of progressing it would do except its internal intialization (which I give a new `Initializing` reason).  But adding an odd reason seemed easy enough, and we can always circle back later and remove this …
> pkg/controller/status/status: Set reasons for conditions

- Makefile
- test/integration/basic_test.go
- test/integration/bugs_test.go
- test/integration/main_test.go
The e2e tests were occasionally failing, I think there were few problems:
- Tests in go run in indefined order. Normal unit tests should not change environment for consequent tests. For tests which were modifying the cluster I added cleanup methods, which should revert caused changes.
- Added extra test to make sure pull-secret exists
- Shortened upload interval for OptIn test, which makes sure we upload as fast as possible and not wait for random Jitter period. (Not waiting on startup skips the initial delay only when upload is executed in first 30 seconds (Because it is based on initial call to status.update) - maybe this could be improved).
- Fixed IsDisabled condition
- Added check for disabled to OptIn test beginning
> Make e2e tests more stable

- pkg/gather/clusterconfig/clusterconfig.go
These metrics help identify distribution of CPU and memory use
within a cluster at infrequent intervals. All labels on the new
metrics are present in ALERTS and are also returned in telemetry,
so do not represent a larger source of gathered data.
The data will be used to identify regressions in core and extension
operator usage across the fleet, as well as to ensure that over time
OpenShift operators continue to reduce resource consumption.
> gather: Collect namespace level cpu and memory metrics

- pkg/gather/clusterconfig/clusterconfig.go
- pkg/gather/clusterconfig/clusterconfig_examples.go
- pkg/gather/clusterconfig/clusterconfig_test.go
A lot of scenarios could use node information even if these are reporting
as healthy - e.g. custom taints may prevent pods from scheduling or
single master installs. This commit ensures anonymized node information
is included in every archive.
> pkg/gather/clusterconfig/clusterconfig: include node information in every archive

- pkg/gather/clusterconfig/clusterconfig.go
- pkg/record/diskrecorder/diskrecorder.go
This commit ensures clusterconfig won't collect large logs.
GatherClusterOperators would use maximum available compressed tarball
size (set in `diskrecorder`), multiply it by `logCompressionRatio`
(set to 2 initially) and split this budget between unhealthy pods.
`collectContainerLogs` would limit the amount of fetched bytes so
that log lines would not exceed container log budget.
Addresses https://github.com/openshift/insights-operator/pull/115#discussion_r441858786
> clusterconfig.go: limit the size of collected logs

- pkg/controller/operator.go
- pkg/controller/status/status.go
- pkg/insights/insightsuploader/insightsuploader.go
There are three main changes here:
- Besides checking reported operator status, before enabling Fast upload path (without initial delay) it is also checking insights Operator Pod status. This is to address https://github.com/openshift/insights-operator/pull/117#issuecomment-645646045.
- Originally, the fast upload mode was enabled and disabled by UpdateStatus, which is happening on startup and then periodically every 30s. On larger clusters when data Gathering took more then 30 seconds, this consequent call to updateStatus was not considered initial and disabled - even if operator was helthy. To fix this, fast mode is now disabled from after insights upload happens (successfully or not)..
- Additional fast upload mode improvement - originally when Cluster Version wasnt available (which is …
> Check also Pod status before enabling Fast upload

- pkg/gather/clusterconfig/clusterconfig.go
- pkg/gather/clusterconfig/csr.go
- pkg/record/diskrecorder/diskrecorder.go
- pkg/record/interface.go
`Marshalable` interface is extended to provide a file extension. It
is being appended to the files when these are written to disk.
If marshaller returns empty string no extension is appended.
Cherry-pick of https://github.com/openshift/insights-operator/pull/99 on 4.4
> Bug 1840012: [release-4.4] pkg: write files with extension

- README.md
- tools/gen_cert_key.py
Info how to retrieve key and certificate and simple script to do so
> Info how to retrieve key and certificate and simple script to do so

- test/integration/bugs_test.go
We should wait a little bit longer for a log that tells logs are already written, not that the logs are currently being written.
> TestPodLogsCollected fix

- Makefile
The timeout for e2e was too high, now it runs in about 7m, so setting 10m should be enough.
> Shorten e2e tests interval

- test/integration/bugs_test.go
- test/integration/main_test.go
Tests if files in insights archive have an extension. There are some exceptions. The test will be needed to be updated if new extensions or exceptions appear.
This test was added to tests after degrading the operator, as these add more files to the insights archive. So there is more to check without making tests run longer.
https://bugzilla.redhat.com/show_bug.cgi?id=1840012
Q: are really these "patterns" supposed to be exceptions?
`/config$`,
`/id$`,
`/invoker$`,
`/metrics$`,
`/version$`,
> Test if files in insights archive have extension set

- README.md
- docs/gathered-data.md
- pkg/gather/clusterconfig/clusterconfig.go
- pkg/gather/clusterconfig/clusterconfig_test.go
Copy of #147 with a couple of additional fixes and tweaks.
The docs update also includes a forgotten update from #133.
> When an operator starts generating big amount of Alerts into the prometheus, Insights operator is downloading all the alerts and the resulting file might be big.
>
> The consequence is that internal data pipeline in CCX is failing, because we cannot store archive to Kafka, where maximal limit is 1MB a if the file is larger then 300 KB, services were failing during the Insights rule processing when it was extracting it all to memory.
> Bug 1862444: Limit collection of ALERTS metric to 1000 lines (~500KiB) to avoid unbearably large archives

- pkg/gather/clusterconfig/clusterconfig.go
- pkg/record/diskrecorder/diskrecorder.go
This commit ensures clusterconfig won't collect large logs.
GatherClusterOperators would use maximum available compressed tarball
size (set in `diskrecorder`), multiply it by `logCompressionRatio`
(set to 2 initially) and split this budget between unhealthy pods.
`collectContainerLogs` would limit the amount of fetched bytes so
that log lines would not exceed container log budget.
Cherry-pick of https://github.com/openshift/insights-operator/pull/126
> Bug 1851492: [release-4.5] clusterconfig.go: limit the size of collected logs

- OWNERS
I have been working on the Insights Operator for a while now and having the permissions would be helpful. Right now I can't use many of the OpenShift bot commands. Ricardo will soon, hopefully, start working on the Insights Operator as well, so it may be for the best to add both of us at once.
> Add @natiiix to OWNERS

- Makefile
- test/integration/bugs_test.go
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1835090
Q: Is checking if CSR is collected enough? or we also need to check if the collected CSR is anonymized?
> TestCSRCollected

- pkg/config/configobserver/configobserver.go
- pkg/config/configobserver/configobserver_test.go
Decreasing the minimal duration of insights secret interval can significantly speed-up e2e tests
> Decrease insights secret interval minimal duration

- pkg/gather/clusterconfig/clusterconfig.go
- pkg/gather/clusterconfig/clusterconfig_test.go
> [release-4.5] Bug 1866776: Limit collection of ALERTS metric to 1000 lines (~500KiB) to avoid unbearably large archives

- Makefile
- test/integration/basic_test.go
- test/integration/bugs_test.go
- test/integration/main_test.go
https://bugzilla.redhat.com/show_bug.cgi?id=1841057
> TestUploadNotDelayedAfterStart

- test/integration/bugs_test.go
Checking if insights operator records an event file before checking that the records were written to the disk should prevent running tests with an older archive that doesn't have new records yet
> Fix TestArchiveContains/File: Check if insights operator records an event

- pkg/controller/operator.go
- pkg/controller/status/status.go
- pkg/controller/status/status_test.go
- pkg/insights/insightsuploader/insightsuploader.go
This PR is backport into 4.4 for Not delaying initial upload, which was implemented in two PRs, PR https://github.com/openshift/insights-operator/pull/117 and https://github.com/openshift/insights-operator/pull/132
The later PR is improving problem detection algorithm for skipping fast upload and fixes skipping fast upload after long gathering.
> [release-4.4] Bug 1842489: Don't delay first upload

- pkg/gather/clusterconfig/clusterconfig.go
- pkg/gather/clusterconfig/clusterconfig_test.go
> [release-4.4] Bug 1869197: Limit collection of ALERTS metric to 1000 lines (~500KiB) to avoid unbearably large archives

- pkg/insights/insightsclient/insightsclient.go
The ingress service for cloud.redhat.com started returning 201 status codes when posting archives.  This change handles that response code as a valid OK response.
> Bug 1872557: handle 201 response from upload

- manifests/06-deployment.yaml
Rename the operator container to allow for more reasonable debugging.
> Bug 1876858: manifests: rename operator container to be more descriptive

- pkg/gather/clusterconfig/clusterconfig.go
Currently, if a CRD is missing from a cluster and the Insights Operator with unsucessfully attempt to collect it, it will crash. However, some CRDs are supposed to be missing, which would cause I.O. to repeatedly crash. Instead, these errors should only be logged and the error should not be reported.
> Bug 1881848: Do not return CRD not found error, just log it

- OWNERS
Several members of the Insights Operator team are missing from the `OWNERS` file in the Insights Operator repository. This PR adds the missing members to the `OWNERS` file. Hopefully no one has been forgotten.
> Bug 1881364: Add new team members to OWNERS

- pkg/gather/clusterconfig/clusterconfig.go
Backport of #148 (upstream implementation), #153 (4.5 backport), #162 (4.4 backport)
*The test is missing because the 4.3 Insights Operator executed gathering functions in a vastly different way from the 4.4+ versions.*
> [release-4.3] Bug 1874018: Limit collection of ALERTS metric to 1000 lines (~500KiB) to avoid unbearably large archives

- config/local.yaml
- docs/gathered-data.md
- docs/insights-archive-sample/config/serviceaccounts.json
- pkg/controller/operator.go
- pkg/gather/clusterconfig/clusterconfig.go
- pkg/gather/clusterconfig/clusterconfig_test.go
The change is collecting numbers of service accounts from kubernetes default namespaces and openshift built-in namespaces (openshift*).
It would be used to detect that a particular SA exists in ns, specifically to target https://access.redhat.com/solutions/5221881 and find lib-bucket-provisioner from NS openshift-storage
> Gather ServiceAccounts stats from cluster namespaces

- pkg/controller/operator.go
- pkg/gather/clusterconfig/clusterconfig.go
This patch should avoid that the operator ends up with an unhealthy status due to a possible file change.
> Bug 1884221: IO becomes unhealthy due to a file change

- pkg/insights/insightsclient/insightsclient.go
This should return (for log) the http body, for example if ingress returns http errors.
> Report the returned response body to log the error detail from cloud.redhat.com

- .gitignore
- pkg/gather/clusterconfig/clusterconfig.go
Fix collisions between pdbs with the same name but living in different namespaces.
> Bug 1886462: Add the namespace to the gatherers reports to avoid conflicts

- Dockerfile
Updating ose-insights-operator builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/ose-insights-operator.yml
If you have any questions about this pull request, please reach out to `@art-team` in the `#aos-art` coreos slack channel.
Depends on https://github.com/openshift/images/pull/44 . Allow it to merge and then run `/test all` on this PR.
> Updating ose-insights-operator builder & base images to be consistent with ART

- pkg/config/config.go
- pkg/controller/operator.go
While loading config, serialized.ToController was supposing that all values will be explicitly set in serialized config (config/local.yaml file), instead of using default values from support.Controller.
This change will use default values, unless they are overwritten by serializable config, or later overwritten by from secrets.
Before this change, loading logic required the PullReport.Delay to be set, which leads to crash on serialized.ToController error with `delay must be a non-negative duration`
> Take default support instead of rely on existence of config

- docs/gathered-data.md
- docs/insights-archive-sample/config/containerruntimeconfigs/set-log-and-pid.json
- pkg/gather/clusterconfig/clusterconfig.go
- pkg/gather/clusterconfig/clusterconfig_test.go
My cluster didn't have one by default so here is an example you can use to verify:
```yaml
apiVersion: machineconfiguration.openshift.io/v1
kind: ContainerRuntimeConfig
metadata:
name: set-log-and-pid
spec:
machineConfigPoolSelector:
matchLabels:
debug-crio: config-log-and-pid
containerRuntimeConfig:
pidsLimit: 2048
logLevel: debug
```
> Bug 1887778: Adds ContainerRuntimeConfig gatherer

- pkg/gather/clusterconfig/clusterconfig.go
- pkg/record/diskrecorder/diskrecorder.go
If the pod is not healthy Insights operator should collect
previous/current logs for the pod containers. Only last 100 lines
is being kept to prevent the archive from growing large.
This also backports #128 so that resulting tarball doesn't exceed 8Mb
> Bug 1844419: [release-4.4] GatherClusterOperators: store pod logs

- test/integration/bugs_test.go
The allowed delay was too strict, it sometimes fails with older version if the delay happens to be ~1min 30 secs, which shouldn't cause test failure.
> Fix test: Increase allowed delay in TestUploadNotDelayedAfterStart

- manifests/03-clusterrole.yaml
- pkg/controller/operator.go
After this change, when you locally change your config/local.yaml, to some invalid account
impersonate: system:serviceaccount:openshift-insights:some-invalid-account
All the gatherers should return error and no archive should be created in /tmp in the end (withtout this, only pdb was gathered, because it used operator account)
> Bug 1888601: Fixes policyClient and the corresponding config.

- Makefile
The paths in the `-ldflags` part of build script were incorrect causing the client-go `version.gitCommit` and `version.gitVersion` remained on the default value.
> [release 4.5] Bug 1885515: Fixes 'make build'

- Makefile
At the moment test logs are not so informative:
```
secret/support created
go test ./test/integration -run ^\(TestIsIOHealthy\)$ ^\(TestPullSecretExists\)$ -timeout 1m
ok  	github.com/openshift/insights-operator/test/integration	0.754s
go test ./test/integration -timeout 13m 
ok  	github.com/openshift/insights-operator/test/integration	676.211s
```
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-insights-operator-master-insights-operator-e2e-tests-periodic/1320515607073918976/artifacts/insights-operator-e2e-tests-periodic/container-logs/test.log
It would be nice to have more details.
> Add more verbosity to the tests

- manifests/02-namespace.yaml
- manifests/03-clusterrole.yaml
- manifests/03-prometheus_role.yaml
- manifests/03-prometheus_rolebinding.yaml
- manifests/04-proxy-cert-configmap.yaml
- manifests/04-service-ca-configmap.yaml
- manifests/04-serviceaccount.yaml
- manifests/05-service.yaml
- manifests/06-deployment.yaml
- manifests/07-cluster-operator.yaml
- manifests/07-servicemonitor.yaml
This is matches openshift/enhancements#510 and doesn't change existing behavior
> add current profile annotations to CVO manifests

- manifests/03-clusterrole.yaml
- pkg/controller/operator.go
- pkg/gather/clusterconfig/clusterconfig.go
- pkg/gather/clusterconfig/clusterconfig_examples.go
- pkg/gather/clusterconfig/clusterconfig_test.go
Gather info about clusteroperator resources. I added only basic test for `CluterOperator` (no related resource there) because it doesn't seem to be easy to use `discoveryClient.ServerPreferredResources()`. This cal requires to have some `APIGroups` available (see https://github.com/kubernetes/client-go/blob/master/discovery/discovery_client.go#L287)), which is not our case.
I would suggest to test this properly in integration tests.
> Gather clusteroperator resources

- pkg/record/diskrecorder/diskrecorder.go
It fixes a small problem related to the `diskrecorder` that was storing the records using the wrong index, resulting in the reports not being cleared in memory and causing eventual duplicate items.
> Bug 1893766: IO archive contains more records of than is the limit

- test/integration/basic_test.go
- test/integration/bugs_test.go
Upload delay hasn't been changed in this version yet -  these tests cause failures of unrelated backporting PRs
> [release-4.6] temporarily remove e2e-tests (delayed upload)

- test/integration/basic_test.go
Temporarily skipping TestArchiveUploadedAndResultReceived, this test keeps failing, and devs work on fixing the problem ([CCXDEV-3397](https://issues.redhat.com/browse/CCXDEV-3397))
> Skip TestArchiveUploadedAndResultReceived

- pkg/gather/clusterconfig/container_images.go
- pkg/gather/clusterconfig/container_images_test.go
- vendor/github.com/openshift/library-go/pkg/image/internal/digest/digest.go
- vendor/github.com/openshift/library-go/pkg/image/internal/digest/digester.go
- vendor/github.com/openshift/library-go/pkg/image/internal/digest/doc.go
- vendor/github.com/openshift/library-go/pkg/image/internal/reference/doc.go
- vendor/github.com/openshift/library-go/pkg/image/internal/reference/reference.go
- vendor/github.com/openshift/library-go/pkg/image/internal/reference/regexp.go
- vendor/github.com/openshift/library-go/pkg/image/reference/reference.go
- vendor/modules.txt
See #133 
- Don't filter container images based on URL.
- Since filtering isn't possible, only the top 1000 most common images are collected to limit the size.
- The sha256 is collected instead of the full image specs when possible.
> Improve container image collection

- test/integration/bugs_test.go
- test/integration/main_test.go
Signed-off-by: Pavel Simovec <psimovec@redhat.com>
> Reuse archives & refactor archive checks + some fixes

- manifests/02-namespace.yaml
- manifests/03-clusterrole.yaml
- manifests/03-prometheus_role.yaml
- manifests/03-prometheus_rolebinding.yaml
- manifests/04-proxy-cert-configmap.yaml
- manifests/04-service-ca-configmap.yaml
- manifests/04-serviceaccount.yaml
- manifests/05-service.yaml
- manifests/06-deployment.yaml
- manifests/07-cluster-operator.yaml
- manifests/07-servicemonitor.yaml
This partially implements phase 1 of https://github.com/openshift/enhancements#482
and does not change behavior. Initially, all insights-operator
manifests are included in the single-node-developer cluster profile.
Follow-on PRs may exclude any of these that are not needed in the
profile.
> Annotate manifests for single-node-developer cluster profile

- pkg/controller/operator.go
- pkg/controller/periodic/periodic.go
- pkg/controller/status/status.go
- pkg/controller/status/status_test.go
- pkg/insights/insightsuploader/insightsuploader.go
- test/integration/basic_test.go
This is to replace initial upload delay (setting it to 0 actually) with gathering delay. What we are doing now is following:
1. Run gathering right after IO start
2. Check if IO is healthy (checked in https://github.com/openshift/insights-operator/blob/master/pkg/controller/status/status.go#L396)
- if it's healthy then upload immediately
- if it's not heatlhy then wait some time between (15min, 45min) - this happens quite often in CI clusters because of `E1104 14:09:52.697292       1 status.go:406] Couldn't get Insights Operator Pod to detect its status. Error: pods "insights-operator-6d5cf8b5ff-982dt" is forbidden: User "system:serviceaccount:openshift-insights:gather" cannot get resource "pods" in API group "" in the namespace "openshift-insights": RBAC: …
> First check IO container status and optionally delay first gathering

- pkg/record/interface.go
It adds some metrics to log and to generated archive that collects some information about the gathers executions:
- Elapsed time;
- Number of records generated;
- List of errors;
The report is stored at the archive, in the file `insights-operator\gathers.json`
> Adding a metrics report to IO gatherers

- manifests/03-clusterrole.yaml
- pkg/controller/operator.go
After this change, when you locally change your config/local.yaml, to some invalid account
impersonate: system:serviceaccount:openshift-insights:some-invalid-account
All the gatherers should return error and no archive should be created in /tmp in the end (withtout this, only pdb was gathered, because it used operator account)
> [release 4.6] Bug 1888602: Fixes policyClient and the corresponding config.

- pkg/controller/operator.go
This is additional commit for https://github.com/openshift/insights-operator/commit/b7da048d7375d1ebf5dc0750926637dcdf3b046f. 
We shouldn't check the condition if the context was cancelled or done meanwhile. This is unnecessary waiting and can lead to error state.
> Check context status when checking container is running OK

- Makefile
- pkg/controller/operator.go
`TestIsIOHealthy` was failing, because we were waiting too long (more than 10 min) in case of the previous container state was not healthy. 
This is to shorten the waiting time to max 330 seconds (five and a half minutes) and add more time to `TestIsIOHealthy` test
> Update initial waiting times and give TestIsIOHealthy more time

- .github/pull_request_template.md
This PR adds the Github PR template as [CCXDEV-3569](https://issues.redhat.com/browse/CCXDEV-3569) requests.
Sample repository:
https://github.com/rluders/github-templates-test
> Adds github pull request template.

- pkg/gather/clusterconfig/clusterconfig.go
A backport (4.6) of a bug fix that has to do with problems with gathering data due to if we have more resources with the same name, but the resources are in different namespaces, IO collects only one of them.
- Not necessary
- Not necessary
- Not necessary
No new data is collected
https://issues.redhat.com/browse/CCXDEV-3303
https://bugzilla.redhat.com/show_bug.cgi?id=1888165
> [release 4.6] Bug 1888165: Add the namespace to the gatherers reports to avoid conflicts

- Makefile
- test/integration/bugs_test.go
> Bug 1907293: e2e tests - increase timeouts little bit

- docs/gathered-data.md
- docs/insights-archive-sample/config/netnamespaces.json
- pkg/gather/clusterconfig/0_gatherer.go
- pkg/gather/clusterconfig/netnamespaces.go
- pkg/gather/clusterconfig/netnamespaces_test.go
This is a new data enhancement for gathering interesting networking info about netnamespaces.
- Adding `docs/insights-archive-sample/config/netnamespaces.json `
- `docs/gathered-data.md` updated
- Added `pkg/gather/clusterconfig/netnamespaces_test.go `
The obfuscation of IP addresses and hostnames will be adressed with https://issues.redhat.com/browse/CCXDEV-3655. It's still being discussed.
https://bugzilla.redhat.com/show_bug.cgi?id=1907378
> Bug 1907378: Gather netnamespaces network info

- pkg/gather/clusterconfig/clusterconfig.go
A backport (4.5) of a bug fix that has to do with problems with gathering data due to if we have more resources with the same name, but the resources are in different namespaces, IO collects only one of them.
- Not necessary
- Not necessary
- Not necessary
No new data is collected
https://issues.redhat.com/browse/CCXDEV-3303
https://bugzilla.redhat.com/show_bug.cgi?id=1887886
> [release 4.5] Bug 1887886: Add the namespace to the gatherers reports to avoid conflicts

- manifests/03-clusterrole.yaml
- pkg/controller/operator.go
Backports (4.5) a fix for the permissions that caused some resources to be skipped during gathering.
How to verify:
After this change, when you locally change your config/local.yaml, to some invalid account
impersonate: system:serviceaccount:openshift-insights:some-invalid-account
All the gatherers should return error and no archive should be created in /tmp in the end (withtout this, only pdb was gathered, because it used operator account)
- Not necessary
- Not necessary
- Not necessary
No new data is gathered.
https://issues.redhat.com/browse/CCXDEV-3270
https://bugzilla.redhat.com/show_bug.cgi?id=1888607
> [release 4.5] Bug 1888607: Fixes policyClient and the corresponding config.

- docs/insights-archive-sample/config/hostsubnet/ci-ln-iffptmb-f76d1-nhwgd-master-0.json
- docs/insights-archive-sample/config/hostsubnet/ci-ln-iffptmb-f76d1-nhwgd-master-1.json
- docs/insights-archive-sample/config/hostsubnet/ci-ln-iffptmb-f76d1-nhwgd-master-2.json
- docs/insights-archive-sample/config/hostsubnet/ci-ln-iffptmb-f76d1-nhwgd-worker-b-56nwr.json
- docs/insights-archive-sample/config/hostsubnet/ci-ln-iffptmb-f76d1-nhwgd-worker-c-wkwh7.json
- docs/insights-archive-sample/config/hostsubnet/ci-ln-iffptmb-f76d1-nhwgd-worker-d-mdwl8.json
- pkg/gather/clusterconfig/clusterconfig.go
… in the hostsubnet gathering
… in the hostsubnet gathering
This is bugfixing for hostsubnet gathering
- `docs/insights-archive-sample/config/hostsubnet/ci-ln-iffptmb-f76d1-nhwgd-master-0.json`
- `docs/insights-archive-sample/config/hostsubnet/ci-ln-iffptmb-f76d1-nhwgd-master-1.json`
- and more ....
- no need to update
- no update
IP addresses in the hostsubnet definition already anonymized
https://bugzilla.redhat.com/show_bug.cgi?id=1904413
> Bug 1904413: Fix hostsubnet gathering and add to sample archive

- docs/gathered-data.md
- docs/insights-archive-sample/config/pod/openshift-sdn/logs/sdn-controller-l8gq9/errors.log
- pkg/gather/clusterconfig/0_gatherer.go
- pkg/gather/clusterconfig/gather_logs.go
- pkg/gather/clusterconfig/gather_logs_test.go
- pkg/gather/clusterconfig/openshift_apiserver_operator_logs.go
- pkg/gather/clusterconfig/openshift_sdn_controller_logs.go
- pkg/gather/clusterconfig/openshift_sdn_logs.go
sdn-controller (openshift-sdn namespace) emits important messages when it finds issues affecting Egress IPs. The important messages are the following:
“Node %s is not Ready”: A node has been set offline for egress IPs because it is reported not ready at API
“Node %s may be offline... retrying”: An egress node has failed the egress IP health check once, so it has big chances to be marked as offline soon or, at the very least, there has been a connectivity glitch.
“Node %s is offline”: An egress node has failed enough probes to have been marked offline for egress IPs. If it has egress CIDRs assigned, its egress IPs have been moved to other nodes. Indicates issues at either the node or the network between the master and the node.
“Node %s is back online”: This indicates that a node has …
> Bug 1916843: collect logs from openshift-sdn-controller pod

- pkg/gather/clusterconfig/clusterconfig.go
- pkg/gather/clusterconfig/clusterconfig_test.go
- vendor/github.com/openshift/library-go/pkg/image/internal/digest/digest.go
- vendor/github.com/openshift/library-go/pkg/image/internal/digest/digester.go
- vendor/github.com/openshift/library-go/pkg/image/internal/digest/doc.go
- vendor/github.com/openshift/library-go/pkg/image/internal/reference/doc.go
- vendor/github.com/openshift/library-go/pkg/image/internal/reference/reference.go
- vendor/github.com/openshift/library-go/pkg/image/internal/reference/regexp.go
- vendor/github.com/openshift/library-go/pkg/image/reference/reference.go
- vendor/modules.txt
The old container image collection code is already in `release-4.6`, but the improvements are not yet. So this PR backports only the improvements into the 4.6 branch.
- `docs/insights-archive-sample/config/running_containers.json`
Short description in the `docs/gathered-data.md` file, as per usual.
- `pkg/gather/clusterconfig/clusterconfig_test.go` - `TestGatherContainerImages` (together with all the other tests before refactor)
No sensitive data is collected by this enhancement.
N/A
PR: #133
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1860032
PR: #174 
Task: https://issues.redhat.com/browse/CCXDEV-2750
Task: https://issues.redhat.com/browse/CCXDEV-2674
> [release-4.6] Bug 1913645: Improved Red Hat image and crashlooping OpenShift pod collection

- docs/gathered-data.md
- docs/insights-archive-sample/config/clusteroperator/imageregistry.operator.openshift.io/config/cluster.json
- docs/insights-archive-sample/config/clusteroperator/imageregistry.operator.openshift.io/imagepruner/cluster.json
- docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/authentication/cluster.json
- docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/cloudcredential/cluster.json
- docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/config/cluster.json
- docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/console/cluster.json
- docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/csisnapshotcontroller/cluster.json
- docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/dns/default.json
- docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/etcd/cluster.json
- docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/kubeapiserver/cluster.json
- docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/kubecontrollermanager/cluster.json
- docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/kubescheduler/cluster.json
- docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/kubestorageversionmigrator/cluster.json
- docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/openshiftapiserver/cluster.json
- docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/openshiftcontrollermanager/cluster.json
- docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/serviceca/cluster.json
- docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/storage/cluster.json
- docs/insights-archive-sample/config/clusteroperator/samples.operator.openshift.io/config/cluster.json
- manifests/03-clusterrole.yaml
- pkg/controller/operator.go
- pkg/gather/clusterconfig/clusterconfig.go
- pkg/gather/clusterconfig/clusterconfig_examples.go
- pkg/gather/clusterconfig/clusterconfig_test.go
- test/integration/bugs_test.go
This PR backports IO enhancement to gather complete spec defintion for clusteroperator `operator.openshift.io` resources
- `docs/insights-archive-sample/config/clusteroperator/imageregistry.operator.openshift.io/config/cluster.json`
- `docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/authentication/cluster.json`
- `docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/console/cluster.json` 
- and more .....
- `docs/gathered-data.md` - minor update
- `pkg/gather/clusterconfig/clusterconfig_test.go` - basic test added
Anonymization considered. IP addresses, buckets, etc. anonymized - see e.g https://github.com/openshift/insights-operator/pull/287/files#diff-e0e8d2778274ee7ccca623c59f06a4d9720242acb010907d8417caadd17085d7R96 …
> [release-4.5] Bug 1905106: Collect spec config for clusteroperator resources

- pkg/gather/clusterconfig/0_gatherer.go
Errors produced by the gather-functions are supposed to be stored in the metadata, but because it was left up to go on how to parse/store the errors, so they either showed up correctly or just an empty object, which is not really helpful.
This PR fixes that by just storing the error string (ie.: `error.Error()`).
- not necessary
- not necessary
- not necessary
not necessary
-
> Bug 1923888: Fixes error metadata gathering

- docs/gathered-data.md
- docs/insights-archive-sample/config/pod/openshift-authentication/logs/oauth-openshift-6c98668d5b-ftt5n/errors.log
- pkg/gather/clusterconfig/0_gatherer.go
- pkg/gather/clusterconfig/openshift_authentication_logs.go
collect invalid resource name error from logs of openshift-authentication namespace
https://issues.redhat.com/browse/CCXDEV-3900
https://bugzilla.redhat.com/show_bug.cgi?id=1922267
> Bug 1922267: collect invalid resource name error from logs 

- pkg/record/diskrecorder/diskrecorder.go
This PR backports a bugfix related to the `diskrecorder` that was storing the records using the wrong index, resulting in the reports not being cleared in memory and causing eventual duplicate items.
No.
No.
None.
Not applicable. This PR doesn't collect any data.
https://issues.redhat.com/browse/CCXDEV-3428
https://bugzilla.redhat.com/show_bug.cgi?id=1894243
>  [release-4.5] Bug 1894243: Fixes records index on diskrecorder

- docs/gathered-data.md
- docs/insights-archive-sample/config/running_containers.json
- pkg/gather/clusterconfig/clusterconfig.go
- pkg/gather/clusterconfig/clusterconfig_test.go
- vendor/github.com/openshift/library-go/pkg/image/internal/digest/digest.go
- vendor/github.com/openshift/library-go/pkg/image/internal/digest/digester.go
- vendor/github.com/openshift/library-go/pkg/image/internal/digest/doc.go
- vendor/github.com/openshift/library-go/pkg/image/internal/reference/doc.go
- vendor/github.com/openshift/library-go/pkg/image/internal/reference/reference.go
- vendor/github.com/openshift/library-go/pkg/image/internal/reference/regexp.go
- vendor/github.com/openshift/library-go/pkg/image/reference/reference.go
- vendor/modules.txt
This is a backport of #174 and #133 to 4.5, based on the 4.6 backport (#304).
- `docs/insights-archive-sample/config/running_containers.json`
Short description in the `docs/gathered-data.md` file.
- `pkg/gather/clusterconfig/clusterconfig_test.go` - `TestGatherContainerImages` (together with all the other tests before refactor)
No sensitive data is collected by this enhancement.
N/A
PR: #133
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1860032
PR: #174 
Task: https://issues.redhat.com/browse/CCXDEV-2750
Task: https://issues.redhat.com/browse/CCXDEV-2674
`release-4.6` backport PR: #304 
4.5.z backport Bugzilla bug: https://bugzilla.redhat.com/show_bug.cgi?id=1914255
> [release-4.5] Bug 1914255: Red Hat image and crashlooping OpenShift pod collection

- pkg/gather/clusterconfig/0_gatherer.go
- pkg/gather/clusterconfig/recent_metrics.go
Do not create the metrics file in the IO archive when there is some error when querying the metrics. From processing perspective it doesn't make any sense to have a file (containing some error message) that can't be parsed. 
No new data. 
No neeed to update.
No new unit test.
https://issues.redhat.com/browse/CCXDEV-3961
> Do not create the metrics file in case of any error

- pkg/controller/status/status.go
Sets the status of the operator to disabled on repeated gather failures instead of degraded.  
- not needed
- not needed
- not needed
not needed
https://bugzilla.redhat.com/show_bug.cgi?id=1925659
> Disable instead of Degrade in case of gather fails

- docs/gathered-data.md
- docs/insights-archive-sample/config/containerruntimeconfigs/set-log-and-pid.json
- pkg/gather/clusterconfig/clusterconfig.go
- pkg/gather/clusterconfig/clusterconfig_test.go
A backport (4.6) of a new data enhancement for gathering of ContainerRuntimeConfigs.
My cluster didn't have one by default so here is an example you can use to verify:
```yaml
apiVersion: machineconfiguration.openshift.io/v1
kind: ContainerRuntimeConfig
metadata:
name: set-log-and-pid
spec:
machineConfigPoolSelector:
matchLabels:
debug-crio: config-log-and-pid
containerRuntimeConfig:
pidsLimit: 2048
logLevel: debug
```
- `docs/insights-archive-sample/config/containerruntimeconfigs/set-log-and-pid.json`
- `pkg/gather/clusterconfig/clusterconfig_test.go`
https://issues.redhat.com/browse/CCXDEV-3318
https://issues.redhat.com/browse/INSIGHTOCP-84
https://bugzilla.redhat.com/show_bug.cgi?id=1891544
> [release 4.6] Bug 1891544: Adds ContainerRuntimeConfig gatherer

- pkg/authorizer/clusterauthorizer/clusterauthorizer_test.go
- pkg/config/configobserver/configobserver_test.go
- pkg/controller/status/status_test.go
- pkg/gather/clusterconfig/0_gahterer_test.go
- pkg/gather/clusterconfig/certificate_signing_requests_test.go
- pkg/gather/clusterconfig/config_maps_test.go
- pkg/gather/clusterconfig/image_pruners_test.go
- pkg/gather/clusterconfig/image_registries_test.go
- pkg/gather/clusterconfig/install_plans_test.go
- pkg/gather/clusterconfig/service_accounts_test.go
This PR implements parallelism to our unit tests to improve its performance.
No.
No.
- `pkg/authorizer/clusterauthorizer/clusterauthorizer_test.go` - this one can't use parallelism
- `pkg/config/configobserver/configobserver_test.go`
- `pkg/controller/status/status_test.go`
- `pkg/gather/clusterconfig/0_gahterer_test.go`
- `pkg/gather/clusterconfig/certificate_signing_requests_test.go`
- `pkg/gather/clusterconfig/config_maps_test.go`
- `pkg/gather/clusterconfig/image_pruners_test.go`
- `pkg/gather/clusterconfig/image_registries_test.go`
- `pkg/gather/clusterconfig/install_plans_test.go`
- `pkg/gather/clusterconfig/service_accounts_test.go`
This PR doesn't collect any data or change any gather.
No. …
> Introduce parallelism to unit tests

- docs/gathered-data.md
- docs/insights-archive-sample/config/containerruntimeconfigs/set-log-and-pid.json
- pkg/gather/clusterconfig/clusterconfig.go
- pkg/gather/clusterconfig/clusterconfig_test.go
A backport (4.5) of a new data enhancement for gathering of ContainerRuntimeConfigs.
My cluster didn't have one by default so here is an example you can use to verify:
```yaml
apiVersion: machineconfiguration.openshift.io/v1
kind: ContainerRuntimeConfig
metadata:
name: set-log-and-pid
spec:
machineConfigPoolSelector:
matchLabels:
debug-crio: config-log-and-pid
containerRuntimeConfig:
pidsLimit: 2048
logLevel: debug
```
- `docs/insights-archive-sample/config/containerruntimeconfigs/set-log-and-pid.json`
- `pkg/gather/clusterconfig/clusterconfig_test.go`
https://issues.redhat.com/browse/CCXDEV-3318
https://issues.redhat.com/browse/INSIGHTOCP-84
https://bugzilla.redhat.com/show_bug.cgi?id=1891545
> [release 4.5] Bug 1891545: Adds ContainerRuntimeConfig gatherer

- docs/gathered-data.md
- pkg/gather/clusterconfig/clusterconfig.go
This adds new gatherer which gathers important messages from SDN pod logs. 
OCP Networking is one of biggest support case volumes areas
These data enhancements were requested by Support SMEs and will enable them to
- shorten time to resolve. Data that we normally request form customers will be gathered automatically
- there are several Insights rules attached to these new data enhancement which have potential to deflect dozens OCP support cases each month
- no data available for the sample archive because we haven't been able to reproduce the errors yet
Unfortunately no unit test because the fake pod expansion returns only empty request (see https://github.com/kubernetes/client-go/blob/v0.18.9/kubernetes/typed/core/v1/fake/fake_pod_expansion.go#L60) in our …
> [release-4.6] Bug 1921554: Gather OpenShift SDN error messages from logs

- pkg/controller/periodic/periodic.go
This PR simplifies the #348 
No.
No.
No.
Not applicable.
No.
Not applicable.
> Remove code duplication that disable the gather

- docs/gathered-data.md
- pkg/gather/clusterconfig/0_gatherer.go
- pkg/gather/clusterconfig/sap_pods.go
- pkg/gather/clusterconfig/sap_pods_test.go
When the SDI installation fails, it is possible to detect the problem be looking at which of the initialization pods have failed. The process can be automated by gathering the information about failed pods in the SAP/SDI namespace(s).
*The newly gathered data are JSON pod dumps, which are no different from all the other currently gathered pods. Due to the challenging nature of the SAP enhancement development, it was not possible to properly anonymous sample data.*
- `docs/gathered-data.md` - `SAPPods` section
- `pkg/gather/clusterconfig/sap_pods_test.go` - `TestSAPPods`
No.
- [Jira Task](https://issues.redhat.com/browse/CCXDEV-3483)
- [Bugzilla Bug](https://bugzilla.redhat.com/show_bug.cgi?id=1930393)
> Bug 1930393: Gather info about unhealthy SAP pods

- docs/gathered-data.md
- docs/insights-archive-sample/config/serviceaccounts.json
- pkg/controller/operator.go
- pkg/gather/clusterconfig/clusterconfig.go
- pkg/gather/clusterconfig/clusterconfig_test.go
This data enhancement is linked to the Insights rule that enables all customers on 4.6.z to self solve the following issue:
lib-bucket-provisioner' keeps flapping between "Pending" and "Succeeded" in the process of upgrading from v1.0.0 to 2.0.0.
Backporting to 4.6 will therefore reduce CEE support case volume.
- `docs/insights-archive-sample/config/serviceaccounts.json`
- `pkg/gather/clusterconfig/clusterconfig_test.go` (line 796)
Yes. The collected data is being anonymized.
Implements the Service Account Gatherer to the Insights Operator to collect ServiceAccounts statistics from Openshift namespaces.
https://issues.redhat.com/browse/CCXDEV-3250
https://bugzilla.redhat.com/show_bug.cgi?id=1885941
https://issues.redhat.com/browse/INSIGHTOCP-75 …
> [release-4.6] Bug 1885941: Gather ServiceAccounts stats from cluster namespaces

- pkg/controller/periodic/periodic.go
- pkg/recorder/diskrecorder/diskrecorder.go
- pkg/recorder/diskrecorder/diskrecorder_test.go
- pkg/recorder/interface.go
- pkg/recorder/recorder.go
- pkg/recorder/recorder_test.go
Previously when the context exceeded then we end up with an empty archive. 
I believe we don't need the context when saving records to the disk. IOW I think we want to store the records everytime regardless of the context. 
No new data
No update
No new test.
https://issues.redhat.com/browse/CCXDEV-4118
> Do not use context in the recorder

- docs/gathered-data.md
- docs/insights-archive-sample/config/olm_operators.json
- pkg/gather/clusterconfig/olm_operators.go
- pkg/gather/clusterconfig/olm_operators_test.go
- pkg/gather/clusterconfig/testdata/csv_1.yaml
Getting more data about installed OLM operators and create corresponding upgrade report is one of the CCX goals. This PR extends the data with corresponding Operator/ClusterServiceVersion conditions. See the CCX epics below. 
Sample archive updated in:
- `docs/insights-archive-sample/config/olm_operators.json `
Documentation updated:
Test updated in:
- `pkg/gather/clusterconfig/olm_operators_test.go `
https://issues.redhat.com/browse/CCXDEV-719
https://issues.redhat.com/browse/CCXDEV-3965
https://issues.redhat.com/browse/CCXDEV-3966
https://bugzilla.redhat.com/show_bug.cgi?id=1934397
> Bug 1934397:  Extend the OLM operator data with related ClusterServiceVersion conditions

- docs/insights-archive-sample/insights-operator/gathers.json
- pkg/gather/clusterconfig/0_gatherer.go
This PR adds 2 new fields to the metadata (`gathers.json`).
`uptime`: the duration since the start of the first gather
`memory_alloc`: the memory allocated at the time of creating the report. (in bytes)
Some disclaimers:
- I intended to have memory usage stats for each gather-function, but it wasn't really viable. The only way I could measure it was by marshaling the produced records, which is not only inefficient but we can just as easily measure the size of the produced archive and get the same idea.
- The `memory_alloc` stat wont show the peak memory allocation. Even if we are only talking about the gather cycle, knowing when to measure to get the max usage is impossible so we would need to monitor the entire process, which would more complex without much benefit IMO. The purpose of …
> Bug 1934112: Adds memory usage to the metadata

- docs/gathered-data.md
- pkg/gather/clusterconfig/config_maps.go
- pkg/gather/clusterconfig/config_maps_test.go
- pkg/gather/clusterconfig/olm_operators_test.go
Fix missing namespace namespace name in the path of binarydata configmap
No update
Minor fix in: 
New basic unit test added in:
- `pkg/gather/clusterconfig/config_maps_test.go`
https://bugzilla.redhat.com/show_bug.cgi?id=1936785
> Bug 1936785: Include namespace name in binarydata configmap path & test

- .golangci.yml
- Makefile
- pkg/config/configobserver/configobserver_test.go
- pkg/controller/status/status_test.go
- pkg/gather/clusterconfig/0_gatherer_test.go
- pkg/gather/clusterconfig/certificate_signing_requests_test.go
- pkg/gather/clusterconfig/config_maps_test.go
- pkg/gather/clusterconfig/container_images_test.go
- pkg/gather/clusterconfig/container_runtime_configs_test.go
- pkg/gather/clusterconfig/custom_resource_definitions_test.go
- pkg/gather/clusterconfig/gather_logs_test.go
- pkg/gather/clusterconfig/host_subnets_test.go
- pkg/gather/clusterconfig/image_pruners_test.go
- pkg/gather/clusterconfig/image_registries_test.go
- pkg/gather/clusterconfig/install_plans_test.go
- pkg/gather/clusterconfig/machine_config_pools_test.go
- pkg/gather/clusterconfig/machine_sets_test.go
- pkg/gather/clusterconfig/netnamespaces_test.go
- pkg/gather/clusterconfig/olm_operators_test.go
- pkg/gather/clusterconfig/operators_test.go
- pkg/gather/clusterconfig/pod_disruption_budgets.go
- pkg/gather/clusterconfig/pod_disruption_budgets_test.go
- pkg/gather/clusterconfig/sap_config_test.go
- pkg/gather/clusterconfig/sap_pods.go
- pkg/gather/clusterconfig/sap_pods_test.go
- pkg/gather/clusterconfig/service_accounts_test.go
- pkg/recorder/diskrecorder/diskrecorder_test.go
- pkg/recorder/recorder_test.go
This PR fixes some code styling issues, based on the linting tool report.
No.
No.
It doesn't include any tests, but most lint issues were related to it.
No.
https://issues.redhat.com/browse/CCXDEV-4079
> Fixing code style

- docs/gathered-data.md
- pkg/gather/clusterconfig/0_gatherer.go
- pkg/gather/clusterconfig/sap_pods.go
- pkg/gather/clusterconfig/sap_pods_test.go
This is a backport of #347. It is necessary to get this enhancement to 4.6.z in order to see useful results in a reasonable time. After a discussion with a patch manager, it has been determined that it is necessary to backport to 4.7.z as well, even though this version is not supported by the SAP team.
N/A; just like with #347:
> The newly gathered data are JSON pod dumps, which are no different from all the other currently gathered pods. Due to the challenging nature of the SAP enhancement development, it was not possible to properly anonymous sample data.
- `docs/gathered-data.md` - "SAPPods" section
- `pkg/gather/clusterconfig/sap_pods_test.go`
This is just a backport, so it is no different form the upstream …
> [release-4.7] Bug 1934442: Gather info about unhealthy SAP pods

- docs/insights-archive-sample/insights-operator/gathers.json
- pkg/gather/clusterconfig/0_gatherer.go
This PR is a backport of https://github.com/openshift/insights-operator/pull/356
It adds 2 new fields to the metadata (gathers.json).
uptime: the duration since the start of the first gather
memory_alloc: the memory allocated at the time of creating the report. (in bytes)
Some disclaimers:
I intended to have memory usage stats for each gather-function, but it wasn't really viable. The only way I could measure it was by marshaling the produced records, which is not only inefficient but we can just as easily measure the size of the produced archive and get the same idea.
The memory_alloc stat wont show the peak memory allocation. Even if we are only talking about the gather cycle, knowing when to measure to get the max usage is impossible so we would need to monitor the entire process, …
> [release 4.7] Bug 1935605: Adds memory usage to the metadata

- pkg/controller/periodic/periodic.go
- pkg/controller/status/status.go
- pkg/controllerstatus/controllerstatus.go
Some of the new gatherers can fail. We shouldn't degrade the IO in such case. 
No new data
No update
No new unit test
https://bugzilla.redhat.com/show_bug.cgi?id=1939640
> [release-4.6] Bug 1939640: Do not degrade in case of gathering failure

- docs/gathered-data.md
- docs/insights-archive-sample/config/pod/sdi/logs/license-manager-da1d2e8fadfb8dd7022f08-4hjh7-6887768c5b-qzxb6/errors.log
- pkg/authorizer/clusterauthorizer/clusterauthorizer_test.go
- pkg/config/config.go
- pkg/controller/periodic/periodic.go
- pkg/gather/clusterconfig/0_gatherer.go
- pkg/gather/clusterconfig/const.go
- pkg/gather/clusterconfig/custom_resource_definitions.go
- pkg/gather/clusterconfig/gather_logs.go
- pkg/gather/clusterconfig/gather_logs_test.go
- pkg/gather/clusterconfig/image_pruners.go
- pkg/gather/clusterconfig/ingresses.go
- pkg/gather/clusterconfig/openshift_apiserver_operator_logs.go
- pkg/gather/clusterconfig/openshift_authentication_logs.go
- pkg/gather/clusterconfig/openshift_sdn_controller_logs.go
- pkg/gather/clusterconfig/openshift_sdn_logs.go
- pkg/gather/clusterconfig/sap_config.go
- pkg/gather/clusterconfig/sap_config_test.go
- pkg/gather/clusterconfig/sap_vsystem_iptables_logs.go
- pkg/gather/interface.go
- pkg/insights/insightsclient/insightsclient.go
Backport
```
The SAP installation may fail in license management pod, so We need error logs to detect the failure.
Get the filtered error logs as followings.
Found 2 pods, using pod/license-management-l4rvh-74595f8c9b-flgz9
+ iptables -D PREROUTING -t nat -j VSYSTEM-AGENT-PREROUTING
+ true
+ iptables -F VSYSTEM-AGENT-PREROUTING -t nat
+ true
+ iptables -X VSYSTEM-AGENT-PREROUTING -t nat
+ true
+ iptables -N VSYSTEM-AGENT-PREROUTING -t nat
iptables v1.6.2: can't initialize iptables table `nat': Permission denied
Perhaps iptables or your kernel needs to be upgraded.
```
Tested on SAP cluster with different substrings.
No changes
No changes
https://issues.redhat.com/browse/CCXDEV-4172 …
> [release-4.7] Bug 1939061: Sap license management logs gatherer 4.7

- docs/gathered-data.md
- docs/insights-archive-sample/customresources/installers.datahub.sap.com/datahubs/sdi/default.json
- pkg/gather/clusterconfig/0_gatherer.go
- pkg/gather/clusterconfig/sap_datahubs.go
- pkg/gather/clusterconfig/sap_datahubs_test.go
This PR is a backport of #376, which is another SAP enhancement. Much like the others, this one will also have to be backported to 4.6.z for us to see any useful results in a reasonable amount of time.
The presence of the Datahubs resource(s) is used for the identification of SAP (SDI) clusters. As such, it has been decided that it should be collected from all of them in order for the team processing the IO archives to be able to tell SAP clusters apart from the remaining clusters. It is possible that all of the data gathered exclusively from SAP clusters could be missing, in which case it would be impossible to determine if a cluster has an SDI installation or not. This enhancement fixes that issue by gathering a resource that should, universally, be present on all SAP clusters. By …
> [release-4.7] Bug 1942068: Gahter datahubs.installers.datahub.sap.com resources from SAP clusters

- docs/gathered-data.md
- pkg/gather/clusterconfig/operators.go
- pkg/gather/clusterconfig/operators_test.go
- pkg/utils/check/is_healthy_pod.go
This PR changes the ClusterOperator gather in order to allow it to collect also logs from pods that are related to unhealthy operators.
No.
- `docs/gathered-data.md` _(updated Operators gather description)_
- `pkg/gather/clusterconfig/operators_test.go` _(adds extra testing to it)_
No.
https://issues.redhat.com/browse/CCXDEV-4033
https://bugzilla.redhat.com/show_bug.cgi?id=1924663
> Bug 1924663: Gather related pod logs when a cluster operator is degraded

- docs/gathered-data.md
- docs/insights-archive-sample/insights-operator/gathers.json
- pkg/gather/clusterconfig/0_gatherer.go
- pkg/gather/clusterconfig/operators.go
- pkg/gather/clusterconfig/version.go
- pkg/insights/insightsclient/insightsclient.go
Using similar logic to what `gatherClusterOperators` uses, but for the ClusterVersion operator's namespace.  Usually we'd only gather the pod YAML if the pod was failing, but in order to help audit tolerations for [rhbz#1941901][1], at the moment I'm gathering it every time.
With two initial pivots to set the stage:
* pkg/gather/clusterconfig: Collapse GatherClusterID into GatherClusterVersion
* pkg/insights/insightsclient: Inline client handling for ClusterVersion
Details on everything in the respective commit messages.
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1941901
> Bug 1942271: Gather openshift-cluster-version pods and events

- .golangci.yml
- STYLEGUIDE.md
This PR disables the `gocritical` rule for `emptyStringTest` and adds some guidance to the Styleguide about string comparison.
N/A
- `STYLEGUIDE.md` by adding some recommendations about string comparison
N/A
N/A
N/A
https://issues.redhat.com/browse/CCXDEV-4078
> Disable emptyStringTest check

- docs/insights-archive-sample/insights-operator/gathers.json
- pkg/record/interface.go
This PR is a backport of https://github.com/openshift/insights-operator/pull/364
It introduces the metadata gathering to 4.6 and the recently added 2 new fields. (gathers.json).
- name
- duration in milliseconds
- the count of records collected
- errors (if any)
- uptime_seconds: the duration since the start of the first `record.Collect`
- memory_alloc_bytes: the memory allocated at the time of creating the report. (in bytes)
Some disclaimers:
I intended to have memory usage stats for each gather-function, but it wasn't really viable. The only way I could measure it was by marshaling the produced records, which is not only inefficient but we can just as easily measure the size of the produced archive and get the same idea.
The memory_alloc stat wont show the peak memory allocation. Even …
> [release 4.6] Bug 1942457: Adds metadata to the IO archive

- docs/gather-job.yaml
- pkg/cmd/start/start.go
- pkg/controller/const.go
- pkg/controller/gather_job.go
- pkg/controller/operator.go
Updates the gather_job.go so that it doesn't always require a `--kubeconfig` param, also adds the `docs/gather-job.yaml` which is a one off job to run a single gather.
```
$ kubectl apply -n openshift-insights -f docs/gather-job.yaml
...
$ kubectl describe -n openshift-insights job/insights-operator-job
...
Events:
Type    Reason            Age    From            Message
----    ------            ----   ----            -------
Normal  SuccessfulCreate  7m18s  job-controller  Created pod: insights-operator-job-zhmrd <-- THIS
$ kubectl logs -n openshift-insights insights-operator-job-zhmrd insights-operator
...
I0407 11:55:38.192084       1 diskrecorder.go:34] Wrote 108 records to disk in 33ms <-- THIS
$ kubectl cp openshift-insights/insights-operator-job-zhmrd:/var/lib/insights-operator …
```
> Bug 1948966: One-off gather

- docs/gathered-data.md
- pkg/gather/clusterconfig/0_gatherer.go
- pkg/gather/clusterconfig/sap_datahubs.go
- pkg/gather/clusterconfig/sap_pods.go
- pkg/gather/clusterconfig/sap_vsystem_iptables_logs.go
- pkg/gather/clusterconfig/workloads.go
This PR adds limit 3000 for number of gathered pods in the new workload fingerprint gatherer
No new data
No new documentation
> Bug 1948943: Workloads - Add limit for the number of pods gathered

- manifests/02-namespace.yaml
- manifests/06-deployment.yaml
In support of the workload partitioning feature
(openshift/enhancements#703), we need to add
annotations to all management pods and namespaces so they can be
properly identified and assigned to segregated management cores on
clusters configured to do so.
https://github.com/openshift/enhancements/pull/703
> Add management workload annotations

- docs/insights-archive-sample/config/olm_operators.json
- pkg/gather/clusterconfig/olm_operators.go
- pkg/gather/clusterconfig/olm_operators_test.go
- pkg/gather/clusterconfig/testdata/csv_2.yaml
- pkg/gather/clusterconfig/testdata/olm_operator_2.yaml
- pkg/gather/clusterconfig/testdata/olm_operator_3.yaml
This PR refactors a bit the original OLM Operator gatherer and extends the data with the `ClusterServiceVersion` display name. The unit is also extended. 
Sample archive updated in:
- `docs/insights-archive-sample/config/olm_operators.json `
No documentation update
Test significantly extended in:
- `pkg/gather/clusterconfig/olm_operators_test.go `
> Bug 1949990: Extend OLM data with CSV display name

- pkg/gather/clusterconfig/workloads.go
This updates the pod limit in the workload gatherer to be more accurate.
No update
No doc update
No new test
https://bugzilla.redhat.com/show_bug.cgi?id=1948943
> Bug 1948943: Make the pods limit in the workload gatherer more accurate

- docs/insights-archive-sample/config/olm_operators.json
- pkg/gather/clusterconfig/olm_operators.go
- pkg/gather/clusterconfig/olm_operators_test.go
- pkg/gather/clusterconfig/testdata/csv_2.yaml
- pkg/gather/clusterconfig/testdata/olm_operator_2.yaml
- pkg/gather/clusterconfig/testdata/olm_operator_3.yaml
This updates the OLM operator gatherer to include corresponding `ClusterServiceVersion` display name. This is required for the nomination listed below. This PR also updates the gatherer to better handle the errors and extends the corresponding unit test. 
Sample data updated in:
- `docs/insights-archive-sample/config/olm_operators.json `
No documentation updated
Test updated and extended in:
- ` pkg/gather/clusterconfig/olm_operators_test.go `
https://bugzilla.redhat.com/show_bug.cgi?id=1950926
https://issues.redhat.com/browse/INSIGHTOCP-280
> [release-4.7] Bug 1950926: Extend OLM data with CSV display name

- manifests/06-deployment.yaml
As per openshift/enhancements#739, the workload
annotations names are changing.
/hold
Hold until after openshift/kubernetes#632 is merged please
https://github.com/openshift/enhancements/pull/739
> Rename workload annotations

- docs/gathered-data.md
- docs/insights-archive-sample/config/metrics
- pkg/gather/clusterconfig/recent_metrics.go
Add vsphere_node_hw_version_total metric to the collected metrics
- `docs/insights-archive-sample/config/metrics` was updated
- `docs/gathered-data.md` was updated
- not necessary
https://issues.redhat.com/browse/CCXDEV-4623
> Bug 1955102: Add vsphere_node_hw_version_total metric to the collected metrics

- docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/authentication/cluster.json
- docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/kubeapiserver/cluster.json
- docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/openshiftapiserver/cluster.json
- pkg/gather/clusterconfig/infrastructures.go
- pkg/gather/clusterconfig/operators.go
This removes legacy URL anonymization in the clusteroperator resources. This will be obfuscated when user enables the global obfuscation in 4.8.
Sample archive udpated in:
- `insights-operator/docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/authentication/cluster.json` 
- `insights-operator/docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/kubeapiserver/cluster.json`
- `insights-operator/docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/openshiftapiserver/cluster.json`
No doc update.
No new test
> Bug 1954931: Remove URL anonymization from ClusterOperator resources

- docs/gathered-data.md
- docs/insights-archive-sample/config/metrics
- pkg/gather/clusterconfig/recent_metrics.go
Add vsphere_node_hw_version_total metric
- `docs/insights-archive-sample/config/metrics`  updated
- `gahtered-data.md` updated
https://issues.redhat.com/browse/CCXDEV-4631
> [release 4.7] Bug 1955476: Add vsphere_node_hw_version_total metric

- docs/insights-archive-sample/config/olm_operators.json
- pkg/gather/clusterconfig/olm_operators.go
- pkg/gather/clusterconfig/olm_operators_test.go
- pkg/gather/clusterconfig/testdata/csv_2.yaml
- pkg/gather/clusterconfig/testdata/olm_operator_2.yaml
- pkg/gather/clusterconfig/testdata/olm_operator_3.yaml
This updates the OLM operator gatherer to include corresponding ClusterServiceVersion display name. This is required for the nomination listed below. This PR also updates the gatherer to better handle the errors and extends the corresponding unit test.
Sample data updated in:
- `docs/insights-archive-sample/config/olm_operators.json `
No doc update.
Test updated and extended in:
- `pkg/gather/clusterconfig/olm_operators_test.go`
https://bugzilla.redhat.com/show_bug.cgi?id=1951033
https://issues.redhat.com/browse/INSIGHTOCP-280
> [release-4.6] Bug 1951033: Extend OLM data with CSV display name

- pkg/gather/clusterconfig/operators_pods_and_events.go
This PR improves documentation of GatherClusterOperatorPodsAndEvents:
- Improves wording to make it clear what is collected and when.
- Lists locations of individual data points so that users know where to
look for the data even if they don't have a sample archive with the
data (e.g. when starting an extraction notebook).
N/A
I need your help here. Is it preferred to update `gathered-data.md` with this type of changes or you do it once in a while? I didn't include an updated version of `gathered-data.md` because it included changes that I didn't do...
N/A
No.
https://coreos.slack.com/archives/CLABA9CHY/p1620223118250600?thread_ts=1620212876.245500&cid=CLABA9CHY
> Bug 1957889: Improves documentation of GatherClusterOperatorPodsAndEvents

- pkg/config/configobserver/configobserver_test.go
Adds a few extra tests for the configoberver
- no change
- no change
- see `pkg/config/configobserver/configobserver_test.go`
> Bug 1952906: Add a few tests to configobserver_test.go

- go.sum
- pkg/gather/clusterconfig/pod_disruption_budgets.go
- pkg/gather/clusterconfig/pod_disruption_budgets_test.go
- pkg/insights/insightsclient/insightsclient.go
- pkg/insights/insightsreport/insightsreport.go
This is adding retry logic for the insights report pulling - addressing https://github.com/openshift/insights-operator/issues/417 and also updating Policy API version to v1.
No new data
No update
No new test
> Bug 1958759: #417 insights report - add basic retry logic in case of 404

- .githooks/pre-commit
This PR fixes a small issue at the pre-commit script, it wasn't ignoring the staged files under the vendor folder.
n/a
n/a
n/a
n/a
n/a
https://bugzilla.redhat.com/show_bug.cgi?id=1958114
> Bug 1958114: Fix pre-commit script for staged vendor files

- pkg/gatherers/clusterconfig/const.go
- pkg/gatherers/clusterconfig/operators_pods_and_events.go
- pkg/gatherers/clusterconfig/operators_pods_and_events_test.go
This PR adds the capability to collect full container logs if the partial log contains possible stack traces.
None.
None.
- `pkg/gatherers/clusterconfig/operators_pods_and_events_test.go`
None.
https://issues.redhat.com/browse/CCXDEV-4600
https://bugzilla.redhat.com/show_bug.cgi?id=1961067
> Bug 1961067: Collect full pod log for stack traces

- pkg/gatherers/clusterconfig/operators_pods_and_events.go
This PR changes the event gathering interval. It is now 2 times the gatherer's interval. It means that it should collect events that happened in the last 2 hours from the gatherer execution.
No
No
No
N/A
No
https://issues.redhat.com/browse/CCXDEV-4621
https://bugzilla.redhat.com/show_bug.cgi?id=1961701
> Bug 1961701: Change event gathering interval

- docs/gather-job.yaml
This PR replaces the previous image without FQDN used by the gather-job.
If you need to test it, the instructions for it can be found [here](https://github.com/openshift/insights-operator/pull/389).
N/A
N/A
N/A
N/A
N/A
No
https://issues.redhat.com/browse/CCXDEV-4861
https://bugzilla.redhat.com/show_bug.cgi?id=1962095
> Bug 1962095: Replace gather-job image without FQDN

- pkg/gatherers/clusterconfig/gather_logs.go
- pkg/gatherers/clusterconfig/operators_pods_and_events.go
- `*.log` files now have full timestamps
No changes
Yes, the new format of timestamps in the logs
https://issues.redhat.com/browse/CCXDEV-4897
> Bug 1966717: include full timestamps in the logs

- .golangci.precommit.yml
- .golangci.yml
- cmd/changelog/main.go
- cmd/gendoc/main.go
- cmd/insights-operator/main.go
- pkg/config/mock_configurator.go
- pkg/controller/periodic/periodic.go
- pkg/controller/periodic/periodic_test.go
- pkg/gather/gather.go
- pkg/gather/gather_test.go
- pkg/gather/tasks_processing_test.go
- pkg/gatherers/clusterconfig/certificate_signing_requests.go
- pkg/gatherers/clusterconfig/image_registries.go
- pkg/gatherers/clusterconfig/infrastructures.go
- pkg/gatherers/clusterconfig/machine_healthcheck.go
- pkg/gatherers/clusterconfig/nodes.go
- pkg/gatherers/clusterconfig/openshift_apiserver_operator_logs.go
- pkg/gatherers/clusterconfig/operators_pods_and_events.go
- pkg/gatherers/clusterconfig/pod_network_connectivity_checks.go
- pkg/gatherers/clusterconfig/pod_network_connectivity_checks_test.go
- pkg/gatherers/clusterconfig/proxies.go
- pkg/gatherers/clusterconfig/sap_machine_configs_test.go
- pkg/gatherers/clusterconfig/version.go
- pkg/gatherers/workloads/workloads_info_test.go
- pkg/recorder/recorder.go
- pkg/recorder/recorder_test.go
- pkg/utils/anonymize/string.go
- pkg/utils/anonymize/url.go
- pkg/utils/check/has_container_in_crashloop.go
- pkg/utils/check/is_healthy_pod.go
This PR fixes the remaining lint issues in our codebase. So, we should be all good to have it enabled in the CI. :partying_face: 
Related to: https://github.com/openshift/release/pull/18961
No changes.
No changes.
- `pkg/controller/periodic/periodic_test.go`
- `pkg/gather/gather_test.go`
- `pkg/gather/tasks_processing_test.go`
- `pkg/gatherers/clusterconfig/pod_network_connectivity_checks_test.go`
- `pkg/gatherers/clusterconfig/sap_machine_configs_test.go` (biggest changes)
- `pkg/gatherers/workloads/workloads_info_test.go`
- `pkg/recorder/recorder_test.go`
No
https://issues.redhat.com/browse/CCXDEV-4078
https://bugzilla.redhat.com/show_bug.cgi?id=1967595
> Bug 1967595: Fixes the remaining lint issues

- manifests/03-clusterrole.yaml
- pkg/anonymization/anonymizer.go
- pkg/anonymization/anonymizer_test.go
- pkg/gather/gather_test.go
- pkg/recorder/recorder.go
- pkg/recorder/recorder_test.go
The anonymizer has a translation-table about the obfuscated IP addresses. As of right now its inaccessible, so this change would store the  translation-table in a `Secret` in the `openshift-insights` namespace.
On the Web UI you can easily find the secrets under `Workloads` -> `Secrets`, the name of the secret is `obfuscation-translation-table`.
- no
- Added docstrings, user facing documentation is a separate task.
- Added new unit tests to `pkg/anonymization/anonymizer_test.go`
> Bug 1958790: Store translation table in a secret

- .golangci.yml
- .openshiftci/install-golangci-lint.sh
- cmd/changelog/main.go
- pkg/anonymization/anonymizer.go
- pkg/authorizer/clusterauthorizer/clusterauthorizer.go
- pkg/cmd/start/start.go
- pkg/config/config.go
- pkg/config/configobserver/configobserver.go
- pkg/config/mock_configurator.go
- pkg/controller/gather_job.go
- pkg/controller/operator.go
- pkg/controller/periodic/periodic.go
- pkg/controller/status/status.go
- pkg/controllerstatus/controllerstatus.go
- pkg/gather/gather.go
- pkg/gatherers/clusterconfig/container_images_test.go
- pkg/gatherers/interface.go
- pkg/record/memory.go
- pkg/record/record.go
- pkg/recorder/recorder.go
This PR replaces `golint` with `revive`, since `golint` is deprecated and `revive` is 6x faster than `golint`. Also, this PR fixes some linting issues pointed by `revive`.
No.
No.
- `pkg/gatherers/clusterconfig/container_images_test.go`
N/A
N/A
No.
https://bugzilla.redhat.com/show_bug.cgi?id=1969525
> Bug 1969525: Replace golint with revive

- pkg/config/mock_configurator.go
- pkg/controller/periodic/periodic_test.go
Adds a few tests for `periodic.go` (+ some minor lint fixes)
- not necessary
- not necessary
- `pkg/controller/periodic/periodic_test.go`
No
> Bug 1967832: Adds more tests for periodic.go

- pkg/controller/gather_job.go
- pkg/controller/operator.go
- pkg/gather/gather.go
- pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
- pkg/gatherers/clusterconfig/clusterconfig_gatherer_test.go
- pkg/gatherers/clusterconfig/const.go
- pkg/gatherers/clusterconfig/operators_pods_and_events.go
- pkg/gatherers/clusterconfig/operators_pods_and_events_test.go
- pkg/gatherers/clusterconfig/version.go
lastTimeStamp is zero
This PR updates the logic of events gathering to use the gathering interval to get the oldest event time and also looks at event series time in case of `lastTimeStamp` being zero.
No new data
No doc update
No new test
No
> Bug 1961701: Use configured interval as the event time limit & check series if

- pkg/gather/tasks_processing.go
Adds a task pool in the task_processing.go so that the resource usage doesn't grow linearly with the number of added gatherers.
No
> Bug 1967833: Adds tasks pool to tasks_processing

- docs/gathered-data.md
- pkg/gather/clusterconfig/0_gatherer.go
- pkg/gather/clusterconfig/0_utils.go
- pkg/gather/clusterconfig/operators.go
- pkg/gather/clusterconfig/operators_pods_and_events.go
- pkg/gather/clusterconfig/operators_pods_and_events_test.go
- pkg/gather/clusterconfig/operators_test.go
- pkg/utils/check/is_healthy_pod.go
This PR backports two changes related to `GatherClusterOperators` #355 and #397.
This backports some changes that allow the gather to collect also logs from pods that are related to unhealthy operators, and also improves the gather responsibility by splitting it into to gathers `GatherClusterOperators` and `GatherClusterOperatorsPodAndEvents`.
N/A
- `docs/gathered-data.md` (updated)
- `pkg/gather/clusterconfig/operators_pods_and_events_test.go` (new)
- `pkg/gather/clusterconfig/operators_test.go` (updated)
N/A
https://issues.redhat.com/browse/CCXDEV-4428
https://bugzilla.redhat.com/show_bug.cgi?id=1953582
> [release 4.6] Bug 1953582: GatherClusterOperators and GatherClusterOperatorsPodAndEvents

- pkg/anonymization/anonymizer.go
- pkg/anonymization/anonymizer_test.go
No changes
No changes
No changes
Not really
https://issues.redhat.com/browse/CCXDEV-4864
> add egress ips support to anonymizer

- pkg/recorder/recorder.go
- pkg/recorder/recorder_test.go
`MemoryRecord` name can be partially obfuscated as well (when includes cluster base domain i.e node names, hostsubnet names could contain `<CLUSTER_BASE_DOMAIN>` string). This means that such record couldn't be found in https://github.com/openshift/insights-operator/blob/master/pkg/recorder/recorder.go#L171 and the size was growing....and now we have enforced the size limit -> basically empty archives after some time when obfuscation is enabled, because the size limit was exceeded. 
Also do not check the length of the data fingerprint (since it will be always 0 because we don't use fingerprints) -> fix the size counting in case of same duplicate records (yes it can happen as I found out).
No new data
No update
No new test
Yes. There are no sensitive data in the newly collected …
> MemoryRecord name can be obfuscated & fix case of duplicate records

- .golangci.precommit.yml
This PR enables the godox linter to checks at the precommit for TODO, FIXME, and BUG comments. To help us to avoid issue tracking. (PS: It doesn't not affect the CI)
No.
No.
No.
No.
No.
No.
No.
> Enables godox on precommit

- docs/gathered-data.md
- pkg/gatherers/clusterconfig/config_maps.go
- pkg/gatherers/clusterconfig/image_pruners.go
- pkg/gatherers/clusterconfig/image_registries.go
- pkg/gatherers/clusterconfig/operators.go
Minor documentation update
No new data
No new tests
No
> Gathered data doc update - add some known previous locations

- manifests/03-clusterrole.yaml
I found out that we need to keep these resource definitions and add this new delete annotation so that CVO can remove them after upgrading from 4.8 to 4.9.
No new data
No update
No new test
No
https://bugzilla.redhat.com/show_bug.cgi?id=1975542
> Bugzilla 1975542: Add delete annotation to stale resources

- pkg/gatherers/clusterconfig/const.go
- pkg/gatherers/clusterconfig/container_images.go
- pkg/gatherers/clusterconfig/install_plans.go
- pkg/gatherers/clusterconfig/service_accounts.go
IIUC, the gather functions (serviceaccount, installplan and container images) want to collect the resources in the system(openshift) namespaces only. So, we will check if the namespace has prefix `openshift`,  but the openshift preserved namespace prefixes are `openshift-, kube-` per doc [1].
[1] https://docs.openshift.com/container-platform/4.7/applications/projects/working-with-projects.html
No changes
No changes
No changes
No new collected data
No
No
https://docs.openshift.com/container-platform/4.7/applications/projects/working-with-projects.html
> Update the gather functions to collect data from the system namespaces only

- pkg/gatherers/clusterconfig/const.go
- pkg/gatherers/clusterconfig/operators_pods_and_events.go
This PR implements a better way to gather the pod container logs by using an offset limit based on the line where the first stack trace message is found.
No.
No.
No.
No.
No.
https://issues.redhat.com/browse/CCXDEV-4600
> Better pod log gathering with offset for stacktrace messages

- pkg/controllerstatus/controllerstatus.go
Set also to operation so it can be distinguished in `status.go`. See the messy code here https://github.com/openshift/insights-operator/blob/master/pkg/controller/status/status.go#L156. We should probably set `degradingFailure` to false by default. There's already issue to refactor this method. 
No new data
No doc update
No new test but we should think about some integration test if possible. 
No
https://bugzilla.redhat.com/show_bug.cgi?id=1982170
> Bug 1982170: Set also the summary operation when updating status

- pkg/cmd/start/start.go
`klog.Fatal` dumps goroutines stack traces and calls `os.Exit(255)`. This is not desired.
No new data
No documentation update
No new test
No
https://bugzilla.redhat.com/show_bug.cgi?id=1984047
> Bug 1984047: Do not use klog.Fatal

- pkg/controller/status/status.go
pull-secret
The disabled state was not consistent previously. We set it in the following situations:
- token is not valid (or ingress returned 403 or 401 for some reason). Disabled was set together with `UploadDegraded` state, but the gathering continued. 
- gathering failed multiple times in a row. Disabled was set, but it didn't have any effect. Gathering continued after some time
- token was removed from the `pull-secret` -> disabled was set -> gathering as well as uploading was stopped
This PR changes the disabled setting to happen only in the last situation. That's the only situation when it makes sense IMO. 
No update
No update
No new unit test, but it requires integ. test update https://gitlab.cee.redhat.com/ccx/insights-operator-tests/-/merge_requests/49
Yes. There are no …
> Bug 1987192: Set the disabled state only when the token is removed from the

- config/local.yaml
- config/pod.yaml
- manifests/03-clusterrole.yaml
- pkg/authorizer/clusterauthorizer/clusterauthorizer.go
- pkg/cmd/start/start.go
- pkg/config/config.go
- pkg/config/configobserver/configobserver.go
- pkg/controller/operator.go
- pkg/insights/insightsclient/insightsclient.go
- pkg/ocm/ocm.go
- pkg/ocm/ocm_test.go
secret
This adds a new OCM controller which periodically (each 8 hours) tries to pull the SCA (Simple content access) data from the OCM API. The SCA data (basically a x509 certificate) is exposed in the `etc-pki-entitlement` secret in the `openshift-config-managed` namespace. 
No new data
No update here
Basic test covered in `pkg/ocm/ocm_test.go ` 
https://issues.redhat.com/browse/CCXDEV-4211
> Bug 1988351: OCM controller - periodically pull the data and update corresponding

- pkg/controller/operator.go
- pkg/controller/status/status.go
- pkg/insights/insightsreport/insightsreport.go
This PR registers the `insightsreport` status controller so that the operation can be distinguished and new condition (called `InsightsDownloadDegraded`) introduced 
No new data
No doc update
I will work on new integration test.
No
> Bug 1988349: Insightsreport set corresponding clusteroperator condition correctly

- pkg/anonymization/anonymizer.go
- pkg/anonymization/anonymizer_test.go
Backport of https://github.com/openshift/insights-operator/pull/446
No changes
No changes
- pkg/anonymization/anonymizer_test.go:TestAnonymizer_NewAnonymizerFromConfigClient
Not really
https://issues.redhat.com/browse/CCXDEV-5123
> [release-4.8] Bug 1974877: Add egress ips to anonymizer to 4.8

- .editorconfig
- manifests/03-clusterrole.yaml
- manifests/image-references
- pkg/anonymization/anonymizer.go
- pkg/anonymization/anonymizer_test.go
- pkg/controller/gather_job.go
- pkg/controller/operator.go
- pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
Backport [CCXDEV-4481](https://issues.redhat.com/browse/CCXDEV-4481) to 4.8
No changes
No changes
- `pkg/anonymization/anonymizer_test.go`
No new collected data
No
No
https://issues.redhat.com/browse/CCXDEV-5297
> [release-4.8] Bug 1977342: Fix obfuscation translation table secret 4.8

- pkg/gatherers/clusterconfig/cluster_config_v1_config_map.go
- pkg/gatherers/clusterconfig/config_maps.go
- pkg/recorder/recorder.go
- pkg/recorder/recorder_test.go
- do not return an empty `Record` in the `gatherClusterConfigV1`
- check if the empty `record.Item` is not empty before actual recording + basic test
No new data
No update
Test added in:
- `pkg/recorder/recorder_test.go`
No
https://bugzilla.redhat.com/show_bug.cgi?id=1991860
> Bug 1991860: Don't try to record an empty Record if gatherClusterConfigV1 fails

- pkg/controller/operator.go
- pkg/controller/status/status.go
- pkg/controllerstatus/controllerstatus.go
- pkg/insights/insightsclient/insightsclient.go
- pkg/insights/insightsreport/insightsreport.go
- pkg/ocm/ocm.go
This adds status checking to the OCM controller. If the response from the OCM API is an HTTP error other than 404 (which means that SCA certs are not allowed for the given organization) then try again with exponential backoff and after few attempts mark the operator as degraded.  
At the same time, the status doesn't have to be changed to degraded in a disconnected environment. This means that any non-HTTP error is not considered as a reason for marking the operator as degraded.
No new data
No documentation update
No new test
No
https://bugzilla.redhat.com/show_bug.cgi?id=1995913
> Bug 1995913: Degraded status in the OCM controller

- docs/gathered-data.md
- docs/insights-archive-sample/config/psp_names.json
- pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
- pkg/gatherers/clusterconfig/pod_security_policies.go
- pkg/gatherers/clusterconfig/pod_security_policies_test.go
This adds new gatherer for `PodSecurityPolicies` names installed in a cluster. There are no psps by default in a cluster so you have to create one (see the example below) to test this. 
Sample archive updated
- `docs/insights-archive-sample/config/psp_names.json `
Doc updated
- ` docs/gathered-data.md`
No
https://issues.redhat.com/browse/CCXDEV-5605
https://issues.redhat.com/browse/INSIGHTOCP-433
https://access.redhat.com/solutions/5622051
> Bug 2000820: Gather installed PSP names

- README.md
- scripts/update_sample_archive.sh
This PR adds a shell script for updating the sample archive using an extracted IO archive gathered from an OCP cluster. Additional filtering can be applied in order to only updated certain files (based on their content). This was motivated by the sample archive update after the removal of `managedFields` from resource JSONs.
N/A
N/A
N/A
This PR doesn't add or modify any gathered data.
No.
No.
https://issues.redhat.com/browse/CCXDEV-5281
> Add a script for updating files in the sample archive

- docs/gathered-data.md
- docs/insights-archive-sample/config/psp_names.json
- pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
- pkg/gatherers/clusterconfig/pod_security_policies.go
- pkg/gatherers/clusterconfig/pod_security_policies_test.go
This adds new gatherer for PodSecurityPolicies names installed in a cluster. There are no psps by default in a cluster so you have to create one (see the example below) to test this.
Updated
- `docs/insights-archive-sample/config/psp_names.json `
Updated
Added
- ` pkg/gatherers/clusterconfig/pod_security_policies_test.go`
No
https://issues.redhat.com/browse/INSIGHTOCP-433
https://bugzilla.redhat.com/show_bug.cgi?id=2001457
https://access.redhat.com/solutions/5622051
> [release-4.8] Bug 2001457: Gather installed PSP names (#489)

- pkg/insights/insightsclient/insightsclient.go
- pkg/insights/insightsreport/insightsreport.go
The functions `RecvReport` and `RecvSCACerts` don't close the response body. 
No new data
No doc update.
No test
No
> insightsclient - close response body

- pkg/ocm/ocm.go
- pkg/ocm/ocm_test.go
This changes the type of the `etc-pki-entitlement` secret to opaque. It also change the attribute names to end with `pem` suffix so that it can be easily consumed by the Build API. 
No new data
No doc update
Corresponding unit tests updated.
No
https://bugzilla.redhat.com/show_bug.cgi?id=2004814
> Bug 2004814: OCM controller - change type of the secret

- pkg/insights/insightsclient/insightsclient.go
This checks if some proxy is defined for the Insights Operator and if so then:
1.  Looks at the cluster-wide proxy spec `clusterProxy.Spec.TrustedCA.Name` to get the  name of the config map with the CA cert
2.  Gets the corresponding config map from the `openshift-config` namespaces
3. Tries to read the `ca-bundle.crt` key from the config map
4. Adds the CA bundle cert to the CA cert pool used in the `insightsclient`
**How to reproduce**
It's quite easy to reproduce the actual problem (you can set some proxy in the cluster-wide proxy and observe the IO error), but it's a bit difficult to verify that this fix works. You can check the https://access.redhat.com/articles/4740031. In general you need to do the following:
1.  Deploy the mitmproxy to a cluster
2. Extract the …
> Bug 2003657:  Respect user defined proxy's CA cert

- docs/gathered-data.md
- docs/insights-archive-sample/config/jaegertracing.io/jaeger1.json
- manifests/03-clusterrole.yaml
- pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
- pkg/gatherers/clusterconfig/const.go
- pkg/gatherers/clusterconfig/jaeger_cr.go
- pkg/gatherers/clusterconfig/jaeger_cr_test.go
This adds a new gatherer for `jaeger.jaegertracing.io/v1` resources. There's a limit of 5 records for this new gatherer. 
**How to reproduce**
Install the Jaeger operator via OLM. Click on the installed operator and you can create a new instance there. These instances should be gathered. 
- `docs/insights-archive-sample/config/jaegertracing.io/jaeger1.json`
- `pkg/gatherers/clusterconfig/jaeger_cr_test.go`
No
> Gather jaegers.jaegertracing.io CRs

- docs/gathered-data.md
- docs/insights-archive-sample/config/psp_names.json
- pkg/gather/clusterconfig/pod_security_policies.go
- pkg/gather/clusterconfig/pod_security_policies_test.go
This adds new gatherer for PodSecurityPolicies names installed in a cluster. There are no psps by default in a cluster so you have to create one (see the example below) to test this.
Updated
- `docs/insights-archive-sample/config/psp_names.json`
Updated
- `pkg/gather/clusterconfig/pod_security_policies_test.go`
No
https://issues.redhat.com/browse/INSIGHTOCP-433
https://bugzilla.redhat.com/show_bug.cgi?id=2002539
https://access.redhat.com/solutions/5622051
> [release-4.7] Bug 2002539: Gather installed PSP names (#489)

- CHANGELOG.md
- cmd/changelog/main.go
- docs/gathered-data.md
- pkg/gatherers/clusterconfig/machine_configs.go
- pkg/gatherers/clusterconfig/pod_security_policies.go
This is to address [CCXDEV-5537](https://issues.redhat.com/browse/CCXDEV-5537). The changelog was probably generated wrongly and I used the command without the date attributes, which means that it was only updating the original wrong version. 
I think it's better to use the command with the date attributes (specifying time range). I used `go run cmd/changelog/main.go 2020-01-01 2021-09-22` for this one. I also found one minor bug in one of the regexes. 
No new data
No docs.
No new tests
Changelog was regenerated and one minor bug fixed there.
No
https://issues.redhat.com/browse/CCXDEV-5537
> Regenerate changelog & update some gatherers OCP versions

- pkg/gather/clusterconfig/0_gatherer.go
- pkg/gather/clusterconfig/pod_security_policies.go
This fixes my previous backport of PSP gatherer
Yes/No
https://bugzilla.redhat.com/show_bug.cgi?id=2002539
> [release-4.7] Bug 2002539: Fix wrong rebase of PSP gatherer

- pkg/gatherers/clusterconfig/image_registries.go
- pkg/gatherers/clusterconfig/image_registries_test.go
status
Anonymize sensitive information in the `ImageRegistry` config also in `status` and check if there's a `kubectl.kubernetes.io/last-applied-configuration` annotation present, which will probably include this sensitive information as well.
No new data
No doc update
Corresponding unit test updated and extended
No
https://bugzilla.redhat.com/show_bug.cgi?id=2005771
> Bug 2005771: Anonymize the ImageRegistry storage information also in

- pkg/gatherers/workloads/workloads_info.go
This PR removes a very simple code smell from workload_info.go as well one TODO comment from the same file, that was converted to a task.
n/a
n/a
n/a
No
> Removing one unnecessary case statement from workload_info

- pkg/insights/insightsclient/insightsclient.go
This reverts my previous https://github.com/openshift/insights-operator/commit/66d737fc1e0516222ac73726ee5df667048c1399. I was wrong. This should work as it is, because the file [/var/run/configmaps/trusted-ca-bundle/ca-bundle.crt](https://github.com/openshift/insights-operator/blob/master/pkg/insights/insightsclient/insightsclient.go#L106) refers to the config map with user defined CA cert and when the map changes then the file is updated and thus the CA cert is respected. 
No new data
No docs
No test
No
> Reverts "Respect user defined proxy's CA cert"

- pkg/anonymization/anonymizer.go
No changes
No changes
No changes
No
No
https://issues.redhat.com/browse/CCXDEV-6055
https://bugzilla.redhat.com/show_bug.cgi?id=2011822
> Bug 2011822: obfuscation ovn clusters bug

- pkg/ocm/ocm.go
- pkg/ocm/ocm_test.go
This changes the type of the `etc-pki-entitlement` secret to opaque. It also change the attribute names to end with pem suffix so that it can be easily consumed by the Build API. if there is already a same secret of type TLS then delete it first and re-create as opaque secret. 
No doc update
Unit tests udated
No
https://bugzilla.redhat.com/show_bug.cgi?id=2005338
> [release-4.9] Bug 2005338: OCM controller - change type of the secret (#500)

- cmd/changelog/main.go
- cmd/gendoc/main.go
- cmd/obfuscate-archive/main.go
- pkg/cmd/start/start.go
- pkg/gatherers/clusterconfig/certificate_signing_requests_test.go
- pkg/gatherers/clusterconfig/config_maps_test.go
- pkg/gatherers/clusterconfig/install_plans_test.go
- pkg/gatherers/clusterconfig/olm_operators_test.go
- pkg/gatherers/clusterconfig/recent_metrics.go
- pkg/gatherers/conditional/conditional_gatherer_test.go
- pkg/gatherers/workloads/workloads_info_test.go
- pkg/insights/insightsclient/insightsclient.go
- pkg/recorder/diskrecorder/diskrecorder.go
This PR replaces the deprecated `ioutil` as recommended by [golang 1.16 changelog](https://golang.org/doc/go1.16#ioutil) and makes our lint happy.
n/a
n/a
n/a
n/a
> Bug 2020250: Replacing deprecated ioutil

- pkg/insights/insightsuploader/insightsuploader.go
When IO receives HTTP 403 from Ingress service then wait for a time from the interval (1h,3h) instead of (2h,8h) (given the default gathering period is 2h). 
No new data
No doc update
No new test
No
https://issues.redhat.com/browse/CCXDEV-6101
> Bug 2022251: Shorter delay in case of HTTP 403 during upload

- cmd/changelog/main.go
- cmd/gendoc/main.go
- pkg/cmd/start/start.go
- pkg/gatherers/clusterconfig/certificate_signing_requests_test.go
- pkg/gatherers/clusterconfig/config_maps_test.go
- pkg/gatherers/clusterconfig/image_registries.go
- pkg/gatherers/clusterconfig/image_registries_test.go
- pkg/gatherers/clusterconfig/install_plans_test.go
- pkg/gatherers/clusterconfig/olm_operators_test.go
- pkg/gatherers/clusterconfig/recent_metrics.go
- pkg/gatherers/workloads/workloads_info_test.go
- pkg/insights/insightsclient/insightsclient.go
- pkg/recorder/diskrecorder/diskrecorder.go
This backport the https://github.com/openshift/insights-operator/pull/526 & removes deprecated `ioutil` usage to satisfy our linter
No new data
No doc update
Test updated and extended: 
- `pkg/gatherers/clusterconfig/image_registries_test.go`
Yes/No
https://bugzilla.redhat.com/show_bug.cgi?id=2020601
> [release-4.8] Bug 2020601: Anonymize the ImageRegistry storage information also in status

- pkg/gatherers/conditional/conditional_gatherer.go
- pkg/gatherers/conditional/conditional_gatherer_test.go
- pkg/gatherers/conditional/conditions.go
- pkg/gatherers/conditional/gathering_rule.schema.json
- pkg/gatherers/conditional/validation_test.go
No changes
No changes
- `pkg/gatherers/conditional/conditional_gatherer_test.go`
- `pkg/gatherers/conditional/validation_test.go`
No
No
https://issues.redhat.com/browse/CCXDEV-5878
> unified conditional gatherer api with targeted update edge blocking api

- pkg/controller/gather_job.go
Fixed a bug when no more gatherer or metadata would be added to the archive after an error in creating functions for one of the gatherers
No changes
No changes
No changes
No
No
> Bug 2026699: fixed a bug with missing metadata

- cmd/changelog/main.go
- cmd/gendoc/main.go
- cmd/obfuscate-archive/main.go
- docs/gathered-data.md
- pkg/cmd/start/start.go
- pkg/gatherers/clusterconfig/certificate_signing_requests_test.go
- pkg/gatherers/clusterconfig/config_maps_test.go
- pkg/gatherers/clusterconfig/install_plans_test.go
- pkg/gatherers/clusterconfig/olm_operators_test.go
- pkg/gatherers/clusterconfig/operators_pods_and_events.go
- pkg/gatherers/clusterconfig/operators_pods_and_events_test.go
- pkg/gatherers/clusterconfig/recent_metrics.go
- pkg/gatherers/conditional/conditional_gatherer_test.go
- pkg/gatherers/workloads/workloads_info_test.go
- pkg/insights/insightsclient/insightsclient.go
- pkg/recorder/diskrecorder/diskrecorder.go
This is backport of https://github.com/openshift/insights-operator/pull/516 + update of deprecated `ioutil` 
No
https://issues.redhat.com/browse/CCXDEV-6467
https://bugzilla.redhat.com/show_bug.cgi?id=2026644
> [release-4.9] Bug 2026644: Gather all the container logs from relate namespaces of degraded clusteroperator

- docs/gathered-data.md
- docs/insights-archive-sample/config/tsdb.json
- pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
- pkg/gatherers/clusterconfig/tsdb_status.go
This PR implements a method to collect and store TSDB status of the prometheus instance in the monitoring stack. It does this by creating a Gatherer that calls v1/status/tsdb endpoint.
Yes/No
https://issues.redhat.com/browse/CCXDEV-6332
https://issues.redhat.com/browse/MON-1971
> changes for collecting tsdb status

- docs/gathered-data.md
- docs/insights-archive-sample/config/mutatingwebhookconfigurations/machine-api.json
- docs/insights-archive-sample/config/mutatingwebhookconfigurations/pod-identity-webhook.json
- docs/insights-archive-sample/config/validatingwebhookconfigurations/autoscaling.openshift.io.json
- docs/insights-archive-sample/config/validatingwebhookconfigurations/machine-api.json
- docs/insights-archive-sample/config/validatingwebhookconfigurations/multus.openshift.io.json
- docs/insights-archive-sample/config/validatingwebhookconfigurations/prometheusrules.openshift.io.json
- docs/insights-archive-sample/config/validatingwebhookconfigurations/snapshot.storage.k8s.io.json
- pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
- pkg/gatherers/clusterconfig/mutatingwebhookconfigurations.go
- pkg/gatherers/clusterconfig/validatingwebhookconfigurations.go
- pkg/gatherers/clusterconfig/webhookconfigurations_test.go
Backport of gatherer for webhook configuration resources - https://github.com/openshift/insights-operator/pull/508
- `docs/insights-archive-sample/config/mutatingwebhookconfigurations/machine-api.json `
- `docs/insights-archive-sample/config/mutatingwebhookconfigurations/pod-identity-webhook.json`
- ...
- `docs/insights-archive-sample/config/validatingwebhookconfigurations/autoscaling.openshift.io.json`
Updated
- `pkg/gatherers/clusterconfig/webhookconfigurations_test.go `
No
https://bugzilla.redhat.com/show_bug.cgi?id=2027637
> [release-4.9] Bug 2027637: gather webhook configurations

- docs/insights-archive-sample/insights-operator/conditional-gatherer-rules.json
- go.mod
- go.sum
- pkg/gather/gather.go
- pkg/gatherers/conditional/conditional_gatherer.go
- pkg/gatherers/conditional/conditional_gatherer_test.go
- pkg/gatherers/conditional/conditions.go
- pkg/gatherers/conditional/gathering_functions.go
- pkg/gatherers/conditional/gathering_rule.schema.json
- vendor/github.com/blang/semver/v4/LICENSE
- vendor/github.com/blang/semver/v4/go.mod
- vendor/github.com/blang/semver/v4/json.go
- vendor/github.com/blang/semver/v4/range.go
- vendor/github.com/blang/semver/v4/semver.go
- vendor/github.com/blang/semver/v4/sort.go
- vendor/github.com/blang/semver/v4/sql.go
- vendor/modules.txt
No changes
No changes
- `pkg/gatherers/conditional/conditional_gatherer_test.go`
No
Yes
https://issues.redhat.com/browse/CCXDEV-5773
> Cluster version condition

- docs/gathered-data.md
- docs/insights-archive-sample/config/mutatingwebhookconfigurations/machine-api.json
- docs/insights-archive-sample/config/mutatingwebhookconfigurations/pod-identity-webhook.json
- docs/insights-archive-sample/config/validatingwebhookconfigurations/autoscaling.openshift.io.json
- docs/insights-archive-sample/config/validatingwebhookconfigurations/machine-api.json
- docs/insights-archive-sample/config/validatingwebhookconfigurations/multus.openshift.io.json
- docs/insights-archive-sample/config/validatingwebhookconfigurations/prometheusrules.openshift.io.json
- docs/insights-archive-sample/config/validatingwebhookconfigurations/snapshot.storage.k8s.io.json
- pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
- pkg/gatherers/clusterconfig/mutatingwebhookconfigurations.go
- pkg/gatherers/clusterconfig/validatingwebhookconfigurations.go
- pkg/gatherers/clusterconfig/webhookconfigurations_test.go
Backport of gatherer for webhook configuration resources - #508
-     `docs/insights-archive-sample/config/mutatingwebhookconfigurations/machine-api.json`
-     `docs/insights-archive-sample/config/mutatingwebhookconfigurations/pod-identity-webhook.json`
-     ...
-     `docs/insights-archive-sample/config/validatingwebhookconfigurations/autoscaling.openshift.io.json`
Updated
- `pkg/gatherers/clusterconfig/webhookconfigurations_test.go`
No
https://bugzilla.redhat.com/show_bug.cgi?id=2027720
> [release-4.8] Bug 2027720: gather webhook configurations

- config/pod.yaml
- pkg/cmd/start/start.go
- pkg/config/config.go
- pkg/config/configobserver/configobserver.go
- pkg/controller/status/conditions.go
- pkg/controller/status/controller.go
- pkg/controller/status/status.go
- pkg/controllerstatus/controllerstatus.go
- pkg/ocm/ocm.go
This is adding a new clusteroperator condition type called "SCANotAvailable". This condition will occur in case of an OCM API response status code > 399 || < 200 and will provide the HTTP status message (e.g "NotFound") as the condition reason. 
The reason for this, is to inform users about errors when pulling down the SCA certs automatically
No new data
No doc update. It's documented in the official OCP documentation
No new test
No
> new cluster operator condition providing info about unavailable SCA certs

- docs/gathered-data.md
- docs/insights-archive-sample/config/silenced_alerts.json
- manifests/03-clusterrole.yaml
- pkg/controller/const.go
- pkg/controller/gather_job.go
- pkg/controller/operator.go
- pkg/gather/gather.go
- pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
- pkg/gatherers/clusterconfig/clusterconfig_gatherer_test.go
- pkg/gatherers/clusterconfig/silenced_alerts.go
Signed-off-by: Prashant Balachandran <pnair@redhat.com>
This PR adds a new gatherer which can collect silenced alerts from the alertmanager.
https://issues.redhat.com/browse/CCXDEV-6423
> adding gatherer for collecting silenced alerts

- docs/gathered-data.md
- docs/insights-archive-sample/config/pod/openshift-kube-scheduler/logs/openshift-kube-scheduler-ip-10-0-141-107.us-east-2.compute.internal/messages.log
- docs/insights-archive-sample/config/pod/openshift-kube-scheduler/logs/openshift-kube-scheduler-ip-10-0-177-226.us-east-2.compute.internal/messages.log
- docs/insights-archive-sample/config/pod/openshift-kube-scheduler/logs/openshift-kube-scheduler-ip-10-0-211-255.us-east-2.compute.internal/messages.log
- docs/insights-archive-sample/config/schedulers/cluster.json
- pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
- pkg/gatherers/clusterconfig/const.go
- pkg/gatherers/clusterconfig/openshift_apiserver_operator_logs.go
- pkg/gatherers/clusterconfig/openshift_authentication_logs.go
- pkg/gatherers/clusterconfig/openshift_sdn_controller_logs.go
- pkg/gatherers/clusterconfig/openshift_sdn_logs.go
- pkg/gatherers/clusterconfig/sap_vsystem_iptables_logs.go
- pkg/gatherers/clusterconfig/scheduler.go
- `docs/insights-archive-sample/config/schedulers/cluster.json`
- `docs/insights-archive-sample/config/pod/openshift-kube-scheduler/logs/{NODE_NAME}/messages.log`
No
No
https://issues.redhat.com/browse/CCXDEV-6202
> Collect Info about Openshift scheduler

- manifests/08-prometheus_rule.yaml
New alert definition for disabled Insights operator.
No new data
Requires the new docs - https://github.com/openshift/openshift-docs/pull/39518
No unit test
No
> alert about disconnected cluster

- docs/insights-archive-sample/config/configmaps/kube-system/cluster-config-v1.json
- docs/insights-archive-sample/machinesets/openshift-machine-api/ci-ln-fyvthbt-f76d1-nl2fh-worker-b.json
- docs/insights-archive-sample/machinesets/openshift-machine-api/ci-ln-fyvthbt-f76d1-nl2fh-worker-c.json
- docs/insights-archive-sample/machinesets/openshift-machine-api/ci-ln-fyvthbt-f76d1-nl2fh-worker-d.json
- pkg/gatherers/clusterconfig/cluster_config_v1_config_map.go
- pkg/gatherers/clusterconfig/cluster_config_v1_config_map_test.go
- pkg/gatherers/clusterconfig/image_registries.go
- pkg/gatherers/clusterconfig/infrastructures.go
- pkg/gatherers/clusterconfig/machine_sets.go
- pkg/gatherers/clusterconfig/nodes.go
- pkg/utils/anonymize/unstructured.go
Yes/No
https://issues.redhat.com/browse/CCXDEV-5970
> Bug 2005816: make projectid and region anonymization consistent

- pkg/controller/periodic/periodic.go
- pkg/controller/periodic/periodic_test.go
- pkg/controller/status/controller.go
- pkg/gather/gather.go
- pkg/gather/gather_test.go
- pkg/gather/mock_gatherers.go
- pkg/gather/tasks_processing.go
- pkg/gather/tasks_processing_test.go
- pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
- pkg/gatherers/conditional/conditional_gatherer.go
- pkg/gatherers/conditional/gather_alertmanager_logs.go
- pkg/gatherers/conditional/gather_alertmanager_logs_test.go
- pkg/gatherers/conditional/gather_api_request_count.go
- pkg/gatherers/conditional/gather_image_stream_definitions_of_namespace.go
- pkg/gatherers/conditional/gather_logs_of_namespace.go
- pkg/gatherers/conditional/gather_logs_of_unhealthy_pods.go
- pkg/gatherers/interface.go
- pkg/gatherers/workloads/workloads_gatherer.go
This is removing the unnecessary division into important and failable gatherers. Why? Because every gatherer can fail and in case of failure of an important gatherer, it is not worth repeating the gathering sooner IMO. This was the only significant difference when having this division. 
This requires thorough testing
no updates
updated
No
> Remove unnecessary division into important and failable gatherers

- manifests/08-prometheus_rule.yaml
This adds a new info alert when the SCA is not available/enabled for the cluster
No new data
No unit test
No
> info alert when the SCA is not available

- pkg/controller/operator.go
- pkg/ocm/sca/sca.go
- pkg/ocm/sca/sca_test.go
This is removing the TechPreview feature set check. IOW it means that the SCA certs will be pulled down automatically. There are also some minor enhancements in the related log messages.
This is not possible to test with cluster-bot cluster so you have to create your own cluster in AWS.
No new data
This requires OCP doc update
No test update
No
> Remove "InsightsOperatorPullingSCA" TP feature check

- docs/gathered-data.md
- docs/insights-archive-sample/config/image.json
- pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
- pkg/gatherers/clusterconfig/image.go
- pkg/gatherers/clusterconfig/image_test.go
New clusterconfig gatherer for cluster `images.config.openshift.io` resource definition
- `docs/insights-archive-sample/config/image.json`
- `pkg/gatherers/clusterconfig/image_test.go`
No
> Bug 2054095: Gather cluster images.config.openshift.io resource definition

- pkg/gatherers/conditional/conditional_gatherer.go
This PR implements a new data enhancement to collect logs when certain critical alerts are firing. 
https://issues.redhat.com/browse/MON-2200
> collecting logs if certain alerts are raised

- pkg/authorizer/clusterauthorizer/clusterauthorizer_test.go
- pkg/controller/periodic/periodic.go
- pkg/gather/gather.go
- pkg/gatherers/clusterconfig/install_plans_test.go
- pkg/gatherers/conditional/validation.go
This PR removes the use of the `defer` function directly inside the loops, by wrapping it into some functions. It avoids some possible resource leaks. The `defer` functions inside the test files are not causing any issue, in this case, I'm just ignoring them to make the linter happy. And also, this PR fixes some small linting issues related to `fmt.Error`.
No
No
No
No
https://issues.redhat.com/browse/CCXDEV-7149
> fix: defer in loop

- pkg/controller/status/conditions.go
- pkg/controller/status/controller.go
This PR defines the default messages for `Available`, `Degraded`, `Upgradeable` and `Progressing` clusteroperator condition types and ensures that the values of conditions are reconciled if changed. 
No new data
No docs update
- No new unit test
No
https://bugzilla.redhat.com/show_bug.cgi?id=2059586
> Bug 2059586: Set default messages & reconcile clusteroperator status conditions

- pkg/insights/insightsclient/insightsclient.go
- pkg/insights/insightsuploader/insightsuploader.go
- pkg/recorder/diskrecorder/diskrecorder.go
- pkg/recorder/diskrecorder/diskrecorder_test.go
This extends the HTTP content-disposition header to send the new metadata file including the gathering time attribute. 
No new data
No doc update
Minor update in
- `pkg/recorder/diskrecorder/diskrecorder_test.go`
No
> Send gathering time as metadata field with upload request

- manifests/05-service.yaml
- manifests/06-deployment.yaml
- manifests/07-cluster-operator.yaml
- manifests/07-servicemonitor.yaml
This is adding the required annotations to the remaining manifests resource so that the Insights operator can be installed on HyperShift hosted clusters.
No new data
No docs update
No new test
No
https://issues.redhat.com/browse/CCXDEV-6636
> HyperShift - Add required annotation to remaining manifests

- pkg/controller/status/conditions.go
- pkg/controller/status/controller.go
This reverts commit 11e44f0f953a40fdedb2bb731eb2cceb62bd5dd9. After this
merged, some clusters are failing to install with this message:
```
unable to set initial cluster status:
ClusterOperator.config.openshift.io "insights" is invalid:
status.conditions.lastTransitionTime: Required value
```
OpenShift policy is to revert payload breaking changes immediately, and
the team can build their fix on top of the unrevert.
> Revert "Set default messages & reconcile clusteroperator status conditions (#584)

- pkg/gatherers/workloads/types.go
If the images couldn't be read (for example due to timeout - see [here](https://github.com/openshift/insights-operator/blob/master/pkg/gatherers/workloads/workloads_info.go#L205)) then we ended up with json containing `"images":null`. It's better to omit the attribute completely
No update
No update
No new test
No
https://issues.redhat.com/browse/CCXDEV-7109
> Bug 2061304: Don't serialize empty `images` attribute in the workload info gatherer

- pkg/controller/status/conditions.go
- pkg/controller/status/controller.go
- pkg/controllerstatus/controllerstatus.go
This PR defines the default messages for Available, Degraded, Upgradeable and Progressing clusteroperator condition types and ensures that the values of conditions are reconciled if changed.
No new data
No docs update
No new test
No
> Bug 2059586: Set default messages & reconcile clusteroperator status conditions 

- pkg/controller/status/conditions.go
- pkg/controller/status/controller.go
- pkg/controllerstatus/controllerstatus.go
Reverts openshift/insights-operator#588
This was previously reverted in https://github.com/openshift/insights-operator/pull/586.  This should **not** be reintroduced until e2e-metal-ipi-ovn-ipv6 is added to this repo (see https://github.com/openshift/release/pull/26721), and the change is verified to not break it.
Example failure:
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-nightly-4.11-e2e-metal-ipi-ovn-ipv6/1501915647955701760
```
Operator unavailable (null): operator is not reporting conditions
```
> Bug 2063164: Revert "Set default messages & reconcile clusteroperator status conditions"

- README.md
- docs/anonymized-data.md
This PR adds a Markdown document with a list of the majority of anonymized data points (resource fields). This list was compiled by making reverse-searches of the anonymization helper functions, so it is very possible that there are anonymized data points missing from this list. If you are aware of any, please let me know, and I will gladly add them.
There were quite a few trailing spaces at the ends of lines in the README file, which were automatically removed by my formatter, and I feel like there's no good reason to have them there, so I kept it in this PR.
N/A
- `docs/anonymized-data.md`
N/A
Yes. This is just a documentation update.
N/A
No
Jira Task: https://issues.redhat.com/browse/CCXDEV-7267
> Add list of anonymized data points to documentation

- docs/insights-archive-sample/insights-operator/conditional-gatherer-rules.json
- pkg/gatherers/conditional/conditional_gatherer.go
- pkg/gatherers/conditional/parsing.go
- pkg/gatherers/conditional/parsing_test.go
- pkg/gatherers/conditional/types.go
- `insights-operator/conditional-gatherer-rules.json`
No
- `pkg/gatherers/conditional/parsing_test.go`
No
Yes, changed the structure of `insights-operator/conditional-gatherer-rules.json`
https://issues.redhat.com/browse/CCXDEV-7488
> save version of gathering rules in metadata

- docs/gathered-data.md
- docs/insights-archive-sample/config/namespaces_with_overlapping_uids.json
- pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
- pkg/gatherers/clusterconfig/namespaces_with_overlapping_uids.go
- pkg/gatherers/clusterconfig/namespaces_with_overlapping_uids_test.go
This adds a new gatherer finding namespaces with overlapping UID ranges. The UID range is obtained from the `openshift.io/sa.scc.uid-range` annotation and examples of the overlapping and non-overlapping ranges are:
- 1000670000/10000 and 1000675000/10000 **are overlapping**
- 1000670000/10000 and 1000680000/10000 **are not overlapping**
For more details see https://issues.redhat.com/browse/CCXDEV-7821
**Steps to reproduce:**
- create some namespaces in your cluster (and make some of them with overlapping UIDs)
- you can use following yaml to create the namespaces:
```
apiVersion: v1
kind: Namespace
metadata:
annotations:
openshift.io/description: ""
openshift.io/display-name: ""
openshift.io/requester: kube:admin
openshift.io/sa.scc.uid-range: 1000600000/10000
labels: …
```
> Bug 2072842: Gather namespace names with overlapping UIDs

- docs/gathered-data.md
- docs/insights-archive-sample/config/namespaces_with_overlapping_uids.json
- pkg/authorizer/clusterauthorizer/clusterauthorizer_test.go
- pkg/controller/periodic/periodic.go
- pkg/gather/gather.go
- pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
- pkg/gatherers/clusterconfig/install_plans_test.go
- pkg/gatherers/clusterconfig/namespaces_with_overlapping_uids.go
- pkg/gatherers/clusterconfig/namespaces_with_overlapping_uids_test.go
- pkg/gatherers/conditional/validation.go
This is backport of the .https://github.com/openshift/insights-operator/pull/604 - please check the original PR for the steps how to reproduce. 
This also adds the fix for linting.
- *docs/insights-archive-sample/config/namespaces_with_overlapping_uids.json*
- `pkg/gatherers/clusterconfig/namespaces_with_overlapping_uids_test.go`
No
https://issues.redhat.com/browse/CCXDEV-7821
https://issues.redhat.com/browse/INSIGHTOCP-671
https://bugzilla.redhat.com/show_bug.cgi?id=2072842
> [release-4.10] Bug 2072848: Gather namespace names with overlapping UIDs

- config/pod.yaml
- pkg/insights/insightsreport/insightsreport.go
- pkg/insights/insightsreport/types.go
This registers new Prometheus metric providing last known time of gathering. This info is obtained from the smart-proxy report and it basically confirms that the data/archive was processed. 
No new data
No
> Create a new Prometheus metric providing Insights gathering time

- pkg/dependencymagnet/docs.go
- vendor/github.com/openshift/build-machinery-go/Makefile
- vendor/github.com/openshift/build-machinery-go/OWNERS
- vendor/github.com/openshift/build-machinery-go/README.md
- vendor/github.com/openshift/build-machinery-go/doc.go
- vendor/github.com/openshift/build-machinery-go/go.mod
- vendor/modules.txt
This is fixing the vendoring (`make vendor` and `go mod vendor`)
No new data
No docs updates
NO new test
No
> Bug 2077851: Fix vendoring of the build-machinery-go

- docs/gathered-data.md
- docs/insights-archive-sample/config/storage/openshift-storage/ocs-storagecluster.json
- pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
- pkg/gatherers/clusterconfig/const.go
- pkg/gatherers/clusterconfig/openshift_logging.go
- pkg/gatherers/clusterconfig/openshift_logging_test.go
- pkg/gatherers/clusterconfig/openshift_storage.go
- pkg/gatherers/clusterconfig/openshift_storage_test.go
This PR adds the collection of the ODF StorageCluster CR. If ODF is installed, there should be exactly one instance of this CR.
This PR follows the existing example of openshift-logging gathering.
[YES](https://github.com/mulbc/insights-operator/blob/add-ODF-config-gathering/docs/insights-archive-sample/config/storage/openshift-storage/ocs-storagecluster.json)
[YES](https://github.com/mulbc/insights-operator/blob/add-ODF-config-gathering/docs/gathered-data.md#openshiftstorage)
[openshift_storage_test.go](https://github.com/mulbc/insights-operator/blob/add-ODF-config-gathering/pkg/gatherers/clusterconfig/openshift_storage_test.go)
Not yet - need advise on this
No breaking changes expected, new feature …
> Bug 2079315: Gather ODF config data

- pkg/controller/status/controller.go
- pkg/controller/status/status.go
disabled
Fix for clusteroperator conditions when the operator is disabled
**Steps to reproduce the original problem:**
- make IO degraded - e.g by changing the upload endpoint to some non-existing URL
- make IO disabled - by removing `cloud.openshift.com` token from the`pull-secret` 
- IO is still degraded (and other CO conditions are wrong as well), but it should not be
No new data
This will require a new integration test
No
https://bugzilla.redhat.com/show_bug.cgi?id=2081997
> Bug 2081997: Fix the clusteroperator conditions values when IO is

- manifests/06-deployment-ibm-cloud-managed.yaml
- manifests/06-deployment.yaml
Starting from OpenShift 4.11 pod security admission is being activated. In OpenShift the default pod security admission level is going to be `restricted`. This PR fixes workloads from this repository. Concretely, the following violations have been detected:
```
{
  "objectRef": "openshift-insights/deployments/insights-operator",
  "pod-security.kubernetes.io/audit-violations": "would violate PodSecurity \"restricted:latest\": allowPrivilegeEscalation != false (container \"insights-operator\" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabili
ties (container \"insights-operator\" must set securityContext.capabilities.drop=[\"ALL\"]), runAsNonRoot != true (pod or container \"insights-operator\" must set securityContext.runAsNonRoot=true), seccompProfile (pod or …
```
> AUTH-133: manifests/deployment: comply to restricted pod security level

- docs/gathered-data.md
- pkg/gatherers/clusterconfig/recent_metrics.go
We would like to add "console_helm_installs_total" metric created at the time of Installing a chart from Openshift Developer Console gathered by Insights Operator so that we can take decisions from that data. In order to achieve this i have modified gatherMostRecentMetrics method and updated the docs.
No
> Console helm metrics

- docs/conditional-gatherer/README.md
- docs/insights-archive-sample/insights-operator/conditional-gatherer-rules.json
- pkg/controller/kubeconfigs.go
- pkg/gatherers/conditional/conditional_gatherer.go
- pkg/gatherers/conditional/conditional_gatherer_test.go
- `docs/insights-archive-sample/insights-operator/conditional-gatherer-rules.json`
No changes
No
No
> save conditional gatherer endpoint and firing alerts in the metadata

- manifests/08-prometheus_rule.yaml
- pkg/controller/periodic/periodic.go
- pkg/controller/status/conditions.go
- pkg/controller/status/conditions_test.go
- pkg/controller/status/controller.go
- pkg/controller/status/status.go
- pkg/controllerstatus/controllerstatus.go
- pkg/controllerstatus/controllerstatus_test.go
- pkg/insights/insightsreport/insightsreport.go
- pkg/insights/insightsuploader/insightsuploader.go
- pkg/ocm/clustertransfer/cluster_transfer.go
- pkg/ocm/clustertransfer/cluster_transfer_test.go
- pkg/ocm/const.go
- pkg/ocm/sca/sca.go
ClusterTransfer controllers
This creates new permanent clusteroperator conditions for the `SimpleContentAccess` and `ClusterTransfer` controller
No new data
The conditions will be documented in the README in a followup task
Added
- `pkg/controllerstatus/controllerstatus_test.go`
No
> create new permanent clusteroperator conditions for SCA &

- go.mod
- manifests/06-deployment-ibm-cloud-managed.yaml
- manifests/06-deployment.yaml
- manifests/image-references
- pkg/cmd/start/start.go
- pkg/controller/operator.go
- pkg/insights/insightsclient/insightsclient.go
- pkg/insights/insightsreport/insightsreport.go
- pkg/insights/metrics.go
- vendor/github.com/prometheus/client_golang/prometheus/collectors/collectors.go
- vendor/github.com/prometheus/client_golang/prometheus/collectors/dbstats_collector.go
- vendor/github.com/prometheus/client_golang/prometheus/collectors/dbstats_collector_go115.go
- vendor/github.com/prometheus/client_golang/prometheus/collectors/dbstats_collector_pre_go115.go
- vendor/github.com/prometheus/client_golang/prometheus/collectors/expvar_collector.go
- vendor/github.com/prometheus/client_golang/prometheus/collectors/go_collector.go
- vendor/github.com/prometheus/client_golang/prometheus/collectors/process_collector.go
- vendor/modules.txt
This PR changes the Prometheus metrics registry/server used by IO from the `legacyregistry` to an HTTP registry served directly from the IO code. An update of the Prometheus library was included in the changes to make sure the latest version of this dependency was used.
In accordance with #635, the image references should be fixed now. Please see the additional optional test result below.
0. Start a testing cluster using the OCP image based on this PR (e.g., via cluster-bot).
0. Check in the web console that the `insights-operator` target is displayed as "up" and being properly scraped and that HTTPS is being used.
0. In the Metrics tab, try querying some of the `insightsclient_*` metrics to make sure they are being reported.
N/A
N/A
N/A
Yes. User data are not involved in the changes.
No …
> Implement Prometheus Collector pattern

- Makefile
- pkg/gather/gather_test.go
- pkg/gatherers/conditional/conditional_gatherer.go
- pkg/gatherers/conditional/conditional_gatherer_test.go
- pkg/gatherers/conditional/conditions.go
- pkg/gatherers/conditional/conditions_test.go
- pkg/gatherers/conditional/gather_containers_logs.go
Fixes a bug with conditional gatherer integration tests
No changes
No changes
- `pkg/gatherers/conditional/conditional_gatherer_test.go`
- `pkg/gatherers/conditional/conditions_test.go`
No
No
> make cluster version condition more flexible

- manifests/03-clusterrole.yaml
There's existing gatherer for gathering `storagecluster` resources, but it's missing the permissions for the related API resource.
No docs
No new tests
No
> Fix permissions for OCS for the storage gatherer

- docs/gathered-data.md
- pkg/gatherers/clusterconfig/recent_metrics.go
Signed-off-by: Kartikey Mamgain <mamgainkartikey@gmail.com>
Need to backport the metrics collected by insights operator for console_helm_installs metrics.
PR https://github.com/openshift/insights-operator/pull/627 which merges the changes required to collect metrics for 4.11 + cluster.
- [] Enhancement
Yes/No
> [release-4.10] Bug 2093906: Backport console helm installs to 4.10

- docs/gathered-data.md
- docs/insights-archive-sample/config/alerts.json
- pkg/gatherers/clusterconfig/active_alerts.go
- pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
This adds new gatherer for gathering firing/active Prometheus alerts in JSON format as well. The original [recent metrics gatherer](https://github.com/openshift/insights-operator/blob/master/pkg/gatherers/clusterconfig/recent_metrics.go) still continues to gather the alerts (not in JSON) as well, but this can be removed in the future and we will keep the data only in JSON.
- `docs/insights-archive-sample/config/alerts.json`
No
https://issues.redhat.com/browse/CCXDEV-6037
> Gather & store firing alerts in JSON too

- docs/gathered-data.md
- docs/insights-archive-sample/config/storage/openshift-storage/ocs-storagecluster-cephcluster.json
- manifests/03-clusterrole.yaml
- pkg/gatherers/clusterconfig/ceph_cluster.go
- pkg/gatherers/clusterconfig/ceph_cluster_test.go
- pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
- pkg/gatherers/clusterconfig/const.go
This PR adds a new gatherer for gathering status part of the `cephclusters.ceph.rook.io` resources. 
**Steps to have some `cephcluster` resource:**
1. Install ODF via Operator Hub
2. It requires to create `StorageSystem`. Create one:
1. Select `Use an existing StorageClass` in the first step of `Backing storage type`
2. Choose the smallest capacity and select all the nodes in the next step  
3. I've seen error page with 404, but it doesn't matter
3. `oc get cephcluster -A` should return something :) 
- `docs/insights-archive-sample/config/storage/openshift-storage/ocs-storagecluster-cephcluster.json`
- `pkg/gatherers/clusterconfig/ceph_cluster_test.go`
No …
> Gather status of the cephclusters.ceph.rook.io resources

- .github/pull_request_template.md
- README.md
This removes references to Bugzilla, because OCP now uses JIRA.
No
> Remove Bugzilla references

- pkg/controller/status/conditions.go
- pkg/controller/status/conditions_test.go
Signed-off-by: ehila <ehila@redhat.com>
Sorts the conditions array to avoid un-needed updates cluster operator status field
N/A
N/A
- `pkg/controller/status/conditions_test.go`
N/A
N/A
No
https://issues.redhat.com/browse/TRT-481
> OCPBUGS-499: fix: order conditions by type to limit un-needed updates

- docs/conditional-gatherer/README.md
- pkg/cmd/start/receiver.go
- pkg/gatherers/clusterconfig/dvo_metrics.go
- pkg/recorder/diskrecorder/diskrecorder.go
The DVO metrics gatherer relied on the `deployment-validation-operator` namespace name, which is not very convenient, because it can be installed elsewhere.
Steps to verify:
1. Install the `deployment-validation-operator` through the OperatorHub (it will be installed in the `openshift-operators` namespace).
2. Create manually the metrics service for the DVO. You can use [this definition](https://github.com/app-sre/deployment-validation-operator/blob/330a67b6c64462673343c8a0d4f30fe91c5ecac9/deploy/openshift/service.yaml). This should be fixed with the https://issues.redhat.com/browse/DVO-60
3. Create some new namespace and deploy something (e.g the default httpd example) without the resource limits specified. This is required to introduce some DVO checks to be reported. 
4. Run IO …
> OCPBUGS-439: update the DVO metrics gatherer

- manifests/02-namespace.yaml
The label was dropped back in:
```console
$ git --no-pager log -1 --oneline 75f34c7a944e20904d48949a3bd9b1f9496252c0
75f34c7a manifests: Remove run-level, insights operator does not need it
```
That landed between 4.2 and 4.3:
```console
$ git --no-pager grep openshift.io/run-level origin/release-4.2 -- manifests
origin/release-4.2:manifests/02-namespace.yaml:    openshift.io/run-level: "1"
$ git --no-pager grep openshift.io/run-level origin/release-4.3 -- manifests
...no hits...
```
So clusters which were born in 4.1 or 4.2 may have the old label still in place.  This commit clears it like openshift/cluster-version-operator@539e944920 (openshift/cluster-version-operator#623), so the cluster-version operator will clear the stale label.
> OCPBUGS-959: manifests/02-namespace: Explicitly clear run-level label

- config/pod.yaml
- pkg/controller/operator.go
- pkg/insights/insightsreport/insightsreport.go
- pkg/insights/insightsreport/insightsreport_test.go
- pkg/insights/types/types.go
This implements the `insightsReport` part in the status of the new `insightsoperator.operator.openshift.io` CRD. When there are some active recommendations (including disabled ones) in a cluster then you should be able to see them in the output of `oc get insightsoperators.operator.openshift.io cluster -o yaml`
No new data
No docs
- `pkg/insights/insightsreport/insightsreport_test.go`
No
https://issues.redhat.com/browse/CCXDEV-8871
https://issues.redhat.com/browse/CCXDEV-7397
> Implement insights report updating in the insightsoperators.operator.openshift.io resource

- manifests/10-prometheus_rule.yaml
Our `InsightsDisabled` and `SimpleContentAccessNotAvailable` alerts don't set the `namespace` level and thus they end up with the CVO namespace label, because they are based on metrics from the CVO.
No new data
No
https://issues.redhat.com/browse/OCPBUGS-1068
> OCPBUGS-1068: fix alert namespace label

- pkg/cmd/start/receiver.go
- pkg/gatherers/clusterconfig/dvo_metrics.go
- pkg/recorder/diskrecorder/diskrecorder.go
* OCPBUGS-439 update the DVO metrics gatherer
* Fix linting
Backport of the https://github.com/openshift/insights-operator/pull/664
No
https://issues.redhat.com/browse/OCPBUGS-1355
> [release-4.11] OCPBUGS-1355: update the DVO metrics gatherer (#664)

- pkg/insights/insightsreport/insightsreport.go
- pkg/insights/insightsreport/insightsreport_test.go
No new data
no docs required
improvements in
- `pkg/insights/insightsreport/insightsreport_test.go`
No
> OCPBUGS-1351: do not include disabled rules in the total metric

- pkg/gatherers/clusterconfig/kube_controller_manager_logs.go
> OCPBUGS-1949: limit the size of logs loaded into memory

- pkg/gatherers/clusterconfig/dvo_metrics.go
- pkg/utils/read_lines_with_prefix.go
- pkg/utils/read_lines_with_prefix_test.go
This PR implements the filtering for DVO Metrics information. The idea is that the DVO metrics will have the `name` and `namespace` information on the cluster unless the IO archive will not have this information by default.
**How to test it?**
- Create a Cluster (clusterbot or AWS)
- Install DVO from its repository (or you can run it locally)
- Allow openshift-monitoring to access the metrics:
```sh
$ oc process --local NAMESPACE='openshift-monitoring' -f deploy/openshift/network-policies.yaml | oc create -f -
```
[deploy/openshift/network-policies.yaml](https://github.com/app-sre/deployment-validation-operator/blob/master/deploy/openshift/network-policies.yaml)
- Forward metrics service:
```
$ kubectl port-forward service/deployment-validation-operator-metrics 8383:8383 -n …
```
> OCPBUGS-2346: refactor(dvo_metrics): remove name and namespace from dvo metrics

- docs/gathered-data.md
- pkg/gatherers/clusterconfig/node_logs.go
The gatherer gathers logs only from control plane nodes. This is a very important information for rule developers that should be available in the gatherer docs in gathered-data.md.
This PR improves gatherer documentation.
N/A
Note: A few more minor changes from previous commits are being added to this generated file.
N/A
N/A
No.
No.
> Improve GatherNodeLogs docs

- pkg/gatherers/clusterconfig/dvo_metrics.go
- pkg/utils/read_lines_with_prefix.go
- pkg/utils/read_lines_with_prefix_test.go
This PR backports #685
N/A
N/A
No
No
https://issues.redhat.com/browse/OCPBUGS-2320
> [release-4.11] OCPBUGS-2320: refactor(dvo_metrics): remove name and namespace from dvo metrics

- pkg/insights/insightsclient/insightsclient.go
- pkg/insights/insightsclient/requests.go
- pkg/insights/insightsreport/insightsreport.go
- pkg/insights/insightsreport/insightsreport_test.go
- pkg/insights/metrics.go
- pkg/insights/types/types.go
- `pkg/insights/insightsreport/insightsreport_test.go`
No
https://issues.redhat.com/browse/CCXDEV-8942
> OCPBUGS-2915: Updated info link in insights recommendations

- .golangci.precommit.yml
- .golangci.yml
This PR disables some linters for *_test.go files. Better to keep the tests independent and free of some unnecessary "clean code" stuff.
N/A
N/A
N/A
No
> chore(golanglint-ci) disabling some linters for *_test.go files

- pkg/gatherers/clusterconfig/scheduler.go
- pkg/gatherers/clusterconfig/scheduler_logs.go
This PR moves the `SchedulerLogs` to its own file.
N/A
N/A
N/A
No
> refactor(scheduler): move GatherSchedulerLogs to its own file

- pkg/gatherers/clusterconfig/mutatingwebhookconfigurations_test.go
- pkg/gatherers/clusterconfig/validatingwebhookconfigurations_test.go
This PR removes the shared asset function between (*)webhookconfigurations' gatherers, and it also split the tests for the respective gatherers.
N/A
N/A
- `pkg/gatherers/clusterconfig/mutatingwebhookconfigurations_test.go`
- `pkg/gatherers/clusterconfig/validatingwebhookconfigurations_test.go`
No
> refactor(webhookconfigurations): remove asset method and split tests

- config/pod.yaml
There are two ways to disable a rule. First is to do that for particular cluster. This would work with this original query parameter. Second is to do that for your organization (multiple clusters) and this is not currently supported by the API (and the query parameter).
Yes/No
https://issues.redhat.com/browseOCPBUGS-5257 
> OCPBUGS-5257: do not get disabled rules

- config/pod.yaml
There are two ways to disable a rule. First is to do that for particular cluster. This would work with this original query parameter. Second is to do that for your organization (multiple clusters) and this is not currently supported by the API (and the query parameter).
No
https://issues.redhat.com/browse/OCPBUGS-5463
> [release-4.12] Bug OCPBUGS-5463: do not get disabled rules

- pkg/controller/status/controller.go
- pkg/controller/status/controller_test.go
Additional fix for OCPBUGS-5347. It makes sense to have clusteroperator conditions `Disabled=True` and `Available=False` and vice versa, however we will likely need to introduce a new clusteroperator condition when only the data gathering is disabled (through the API behind TechPreview right now)
no new data
no update
updated
- `pkg/controller/status/controller_test.go`
No
> OCPBUGS-5347: additional fix

- docs/gathered-data.md
- docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/ingresscontroller/openshift-ingress-operator/default.json
- pkg/gatherers/clusterconfig/operators.go
- pkg/gatherers/clusterconfig/operators_test.go
the code
This adds new `/config/clusteroperator/operator.openshift.io/ingresscontroller/openshift-ingress-operator/default.json` file to the Insights archive. It also makes the code simple and improves the related test and test coverage.
- `docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/ingresscontroller/openshift-ingress-operator/default.json`
- `pkg/gatherers/clusterconfig/operators_test.go`
No
> OCPBUGS-5903: operators gatherer - handle ingresscontroller relatedObject & simplify

- pkg/gatherers/common/gather_logs.go
- pkg/gatherers/common/gather_logs_test.go
This is an attempt to optimize the `FilterLogFromScanner` function a little bit. It also adds some tests including an experimental benchmark test. You can compare the benchmark results with the previous implementation by executing following command in `pkg/gatherers/common` directory:
```
go test -bench=. -count=10 ./...
```
no new data
no need to document
- `pkg/gatherers/common/gather_logs_test.go`
No
> gather logs - update "FilterLogFromScanner" function and add some tests

- .openshiftci/install-golangci-lint.sh
- CHANGELOG.md
- docs/gathered-data.md
- docs/insights-archive-sample/config/persistentvolumes/monitoring-persistent-volume.json
- pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
- pkg/gatherers/clusterconfig/gather_monitoring_pvs.go
- pkg/gatherers/clusterconfig/gather_monitoring_pvs_test.go
This PR implements Persistent Volumes gathering from `openshift-monitoring namespace`. It's a backport from [4.14](https://github.com/openshift/insights-operator/pull/741). 
- `docs/insights-archive-sample/config/persistentvolumes/monitoring-persistent-volume.json`
- `docs/gathered-data.md#monitoringpvs`
- `/pkg/gatherers/clusterconfig/gather_monitoring_pvs_test.go`
Yest
Yes/No
https://issues.redhat.com/browse/CCXDEV-10221
https://issues.redhat.com/browse/OCPBUGS-8243
> [release-4.13] OCPBUGS-8243: Collect info about monitoring pods pv

- .openshiftci/install-golangci-lint.sh
- CHANGELOG.md
- docs/gathered-data.md
- docs/insights-archive-sample/config/persistentvolumes/monitoring-persistent-volume.json
- pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
- pkg/gatherers/clusterconfig/gather_monitoring_pvs.go
- pkg/gatherers/clusterconfig/gather_monitoring_pvs_test.go
- pkg/gatherers/clusterconfig/service_accounts_test.go
This PR implements Persistent Volumes gathering from openshift-monitoring namespace. It's a backport from [4.14](https://github.com/openshift/insights-operator/pull/741).
- `docs/insights-archive-sample/config/persistentvolumes/monitoring-persistent-volume.json`
- `docs/gathered-data.md#monitoringpvs`
- `/pkg/gatherers/clusterconfig/gather_monitoring_pvs_test.go`
Yes
No
https://issues.redhat.com/browse/CCXDEV-10221
https://issues.redhat.com/browse/OCPBUGS-7871
> [release-4.12] OCPBUGS-7871: Collect info about monitoring pods pv 

- .golangci.yml
- .openshiftci/install-golangci-lint.sh
- docs/insights-archive-sample/config/persistentvolumes/monitoring-persistent-volume.json
- pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
- pkg/gatherers/clusterconfig/gather_monitoring_pvs.go
- pkg/gatherers/clusterconfig/gather_monitoring_pvs_test.go
This PR implements Persistent Volumes gathering from openshift-monitoring namespace. It's a backport from [4.14](https://github.com/openshift/insights-operator/pull/741).
- `docs/insights-archive-sample/config/persistentvolumes/monitoring-persistent-volume.json`
- `docs/gathered-data.md#monitoringpvs`
- `/pkg/gatherers/clusterconfig/gather_monitoring_pvs_test.go`
Yes
No
https://issues.redhat.com/browse/CCXDEV-10221
https://issues.redhat.com/browse/OCPBUGS-7872
> [release-4.11] OCPBUGS-7872: Collect info about monitoring pods pv

- pkg/controller/gather_job.go
- pkg/controller/operator.go
- pkg/insights/insightsclient/insightsclient.go
- pkg/insights/insightsclient/requests_test.go
This PR fixes the problem of having old ClusterID cached when cluster has already new ClusterID.
- `pkg/insights/insightsclient/request_test.go`
No
https://issues.redhat.com/browse/OCPBUGS-8059
> OCPBUGS-8059: Stop Clusterversion caching

- pkg/anonymization/anonymizer.go
- pkg/config/configobserver/insighgtsdatagather_observer.go
- pkg/controller/operator.go
- pkg/controller/periodic/periodic.go
- pkg/controller/status/controller.go
- pkg/insights/insightsuploader/insightsuploader.go
https://github.com/openshift/insights-operator/pull/779 changed the logic in `operator.go` so that the `configinformer` runs every time (and not only in the techpreview). This caused the problem (unable to sync cache -> restart every 10 min) in the techpreview, because it doesn't seem to be possible to add an additional informer, when it's already started. 
This creates (and starts) a new extra config informer only in the techpreview when the feature is enabled. 
-no new data
No
https://issues.redhat.com/browse/OCPBUGS-14771
> OCPBUGS-14771: run an extra config informer in the tech preview

- pkg/gatherers/clusterconfig/pod_disruption_budgets.go
- pkg/gatherers/clusterconfig/pod_disruption_budgets_test.go
backport of PR##786
- `/pkg/gatherers/clusterconfig/pod_disruption_budgets_test.go`
No
https://issues.redhat.com/browse/OCPBUGS-15459
> [release-4.12] OCPBUGS-15459: gather PDBs only from openshift namespaces

- pkg/controller/gather_commands.go
- pkg/controller/operator.go
- pkg/controller/periodic/periodic.go
- pkg/insights/insightsclient/insightsclient.go
- pkg/insights/insightsclient/requests.go
- pkg/insights/insightsreport/insightsreport.go
- pkg/insights/insightsreport/insightsreport_test.go
- pkg/insights/insightsuploader/insightsuploader.go
- pkg/insights/metrics.go
This PR updates the logic of Prometheus metrics registration to work in techpreview (when data gathering runs in a job) as well. The registration and incrementation of the `insightsclient_request_send_total` metric is moved from the uploader and the metric in the techpreview is updated based on the conditions of the latest `datagather` CR (which provides information including HTTP status code in its conditions).  
This also removes the `insightsclient_last_gather_time` metric. This data is available in the Insights CRs. 
This also removes  
no new data
No
> update registration of the metrics to work in techpreview too

- pkg/gatherers/clusterconfig/pod_disruption_budgets.go
- pkg/gatherers/clusterconfig/pod_disruption_budgets_test.go
Backport of PR#780 
- `/pkg/gatherers/clusterconfig/pod_disruption_budgets_test.go`
No
https://issues.redhat.com/browse/OCPBUGS-15506
> [release-4.11] OCPBUGS-15506: gather PDBs only from openshift namespaces

- config/pod.yaml
- pkg/cmd/start/start.go
- pkg/config/config.go
- pkg/config/configobserver/config.go
- pkg/controller/gather_commands.go
- pkg/controller/gather_commands_test.go
- pkg/controller/status/datagather_status.go
- pkg/controller/status/datagather_status_test.go
- pkg/insights/insightsclient/requests.go
This PR implements a new check (HTTP GET) for the `processingStatusEndpoint` (better name suggestions are welcome), which requires cluster ID as well as the Insights request ID (which is part of the data upload HTTP response). 
The endpoint is polled three times (in case of error or response other than HTTP 200) with initial delay of 1 min (same as previously). If the check is successful then the HTTP response body is read and it's used to evaluate whether the data/archive processing was finished or not. The result is provided as the `DataProcessed` condition in the respective `DataGather` CR. 
no new data
- `pkg/controller/gather_commands_test.go` - basic test for the new function
No …
> check new processing status endpoint after uploading data in the job

- pkg/config/configobserver/insighgtsdatagather_observer.go
- pkg/config/configobserver/insightsdatagather_observer_test.go
Adding a basic unit test
no new data
no docs required
- `pkg/config/configobserver/insightsdatagather_observer_test.go`
No
> add unit test for the InsightsDataGather Observer

- config/pod.yaml
- pkg/cmd/start/start.go
- pkg/config/config.go
- pkg/config/configobserver/config.go
- pkg/config/mock_configurator.go
- pkg/controller/gather_commands.go
- pkg/controller/gather_commands_test.go
- pkg/controller/operator.go
- pkg/controller/periodic/periodic.go
- pkg/controller/periodic/periodic_test.go
- pkg/controller/status/datagather_status.go
- pkg/controller/status/datagather_status_test.go
- pkg/controller/status/gatherer_status.go
- pkg/controller/status/gatherer_status_test.go
- pkg/insights/insightsclient/requests.go
- pkg/insights/insightsreport/insightsreport.go
- pkg/insights/insightsreport/insightsreport_test.go
- pkg/insights/types/types.go
This introduces a new `reportEndpointTechPreview` attribute, which replaces the endpoint for donwloading the Insights analysis reports in the techpreview. First we check if the data was processed, and if it was, it tries to download the corresponding Insights analytics report immediately (the Insights request ID is used), if not, we do nothing. 
The response from the new endpoint is different (acutally more light) so there are new types defined (to be able to unmarshal the data). The Insights report is updated in the corresponding DataGather custom resource as well as in the `cluster` `insightsoperator.operator.openshift.io` resource.  
no new data
No …
> download Insights analysis report from a new endpoint (using Insights request ID)

- docs/gathered-data.md
- docs/insights-archive-sample/config/workload_info.json
- pkg/gatherers/workloads/gather_workloads_info.go
- pkg/gatherers/workloads/gather_workloads_info_test.go
- pkg/gatherers/workloads/types.go
This PR implements a new data enhancement to [Workload info gatherer](https://github.com/openshift/insights-operator/blob/master/pkg/gatherers/workloads/gather_workloads_info.go) to add image repository to the archive. The repository image is only collected if it's from outside of Red Hat domain. 
- `docs/insights-archive-sample/config/workload_info.json`
- `pkg/gatherers/workloads/gather_workloads_info_test.go`
No
No
https://issues.redhat.com/browse/CCXDEV-11505
https://issues.redhat.com/browse/OCPBUGS-17428
> OCPBUGS-17428: workload info gatherer, add external image repo

- docs/gathered-data.md
- pkg/gatherers/clusterconfig/gather_config_maps.go
This PR improves documentation of the `GatherConfigMaps` gatherer.
N/A?
None.
N/A
No, N/A.
No
https://issues.redhat.com/browse/CCXDEV-11558
> Improve ConfigMaps gatherer docs

- docs/gathered-data.md
- pkg/gatherers/clusterconfig/gather_dvo_metrics.go
This is changing the logic for filtering out deployment names, namespace names, etc. to be applied only in case the DVO service is deployed in the `openshift-deployment-validation-operator` namespace.
No
> OCPBUGS-18002: DVO metrics gatherer - use UIDs only when DVO deployed in 'openshift-deployment-validation-operator' namespace

- docs/insights-archive-sample/config/workload_info.json
- pkg/config/config_test.go
- pkg/gatherers/workloads/types.go
- pkg/gatherers/workloads/workloads_info.go
- pkg/gatherers/workloads/workloads_info_test.go
This is manual cherry-pick of https://github.com/openshift/insights-operator/pull/811
> [release-4.12] OCPBUGS-19405: workload info gatherer, add external image repo

- pkg/controller/periodic/periodic.go
- pkg/controller/periodic/periodic_test.go
This extracts the "listener" for the on-demand data gathering requests/resources to separate function. Why should this be better than the previous solution?
- the periodic data gathering doesn't block (when running) the on-demand data gathering requests
- new context is created only when a new valid dataGather resource is created - this used to have unexpected consequences - e.g the on-demand datagathering request didn't work because the context was already timeout
- no new data gathered
- 
- simple unit test added, but it will be better to test in the integration tests
No
https://issues.redhat.com/browse/OCPBUGS-20034
> OCPBUGS-20034: improve on-demand data gathering timing issues

- manifests/03-clusterrole.yaml
- pkg/config/configobserver/config_aggregator.go
- pkg/config/configobserver/config_aggregator_test.go
- pkg/config/configobserver/configmapobserver.go
- pkg/config/mock_configurator.go
- pkg/config/types.go
- pkg/controller/gather_commands.go
- pkg/controller/gather_commands_test.go
- pkg/controller/operator.go
- pkg/controller/periodic/periodic.go
- pkg/controller/periodic/periodic_test.go
- pkg/gather/gather.go
- pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
- pkg/gatherers/clusterconfig/gather_support_secret.go
- pkg/gatherers/clusterconfig/gather_support_secret_test.go
- pkg/gatherers/conditional/conditional_gatherer.go
- pkg/gatherers/conditional/conditional_gatherer_test.go
- pkg/insights/insightsuploader/insightsuploader.go
This is minimal PoC for introducing the Insights Operator's configuration in the new `insights-config` configmap instead of the `support` secret configuration. The `support` secret configuration continues to work (to keep backward compatibility), but the configmap takes precedence if exists.
This PR introduces following new files:
- `pkg/config/configobserver/configmapobserver.go` - basic configmap observer watching the configmap's changes using Kubernetes informer
- `pkg/config/configobserver/config_aggregator.go` - this is a listener for both - the original "legacy" secret configobserver as well as the new configmap observer. The idea here is to aggregate or merge the config from both sources at one place. 
The `insights-config` configmap is supposed to live in the `openshift-insights` …
> First minimal PoC version for moving the configuration to configmap

- pkg/gatherers/clusterconfig/gather_dvo_metrics.go
This adds retry logic (with context timeout of 2 seconds) to the DVO metrics gatherer
no new data
No
> add retry logic to the DVO metrics gatherer

- .openshiftci/install-golangci-lint.sh
- cmd/gendoc/main.go
- docs/gathered-data.md
- pkg/gatherers/clusterconfig/gather_cluster_infrastructure.go
- pkg/gatherers/clusterconfig/gather_install_plans.go
- pkg/gatherers/clusterconfig/gather_olm_operators.go
> Fix lint, pin its version and other minor fixes

- pkg/anonymization/anonymizer.go
- pkg/anonymization/anonymizer_test.go
- pkg/config/configobserver/config_aggregator.go
- pkg/config/configobserver/config_aggregator_test.go
- pkg/config/types.go
- pkg/controller/gather_commands.go
- pkg/controller/operator.go
- pkg/controller/periodic/periodic_test.go
- pkg/gather/gather_test.go
- pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
- pkg/gatherers/clusterconfig/gather_cluster_operator_pods_and_events.go
- pkg/gatherers/clusterconfig/gather_cluster_version.go
- pkg/gatherers/clusterconfig/gather_dvo_metrics.go
- pkg/gatherers/clusterconfig/gather_openshift_machine_api_events.go
- pkg/recorder/recorder_test.go
This PR adds a new `obfuscation` option to the new `insights-config` config map. This option allows you to enable the "legacy global obfuscation" as well as the new `workloads_names` obfuscation, which is currently only used for DVO metrics. 
Example can look like:
```yaml
kind: ConfigMap
apiVersion: v1
metadata:
name: insights-config
namespace: openshift-insights
immutable: false
data:
config.yaml: |
dataReporting:
obfuscation:
- workload_names
- networking
```
- no new data
Yes/No
> extends obfuscation options in the configmap

- pkg/gatherers/clusterconfig/gather_dvo_metrics.go
This updates the original `queryMetricsService` function in the DVO gatherer. I think the problem was that the timeout for the context was only 5 seconds and this context was also used for streaming the data. 5 seconds is not enough when streaming larger DVO metrics data. 
This changes the logic to use HEAD request to check whether the DVO service is up and running and then, if it's OK, start reading/streaming the data.
Yes/No
> OCPBUGS-23097: DVO gatherer - do the retry request as HEAD and not stream

- docs/gathered-data.md
- docs/insights-archive-sample/config/storage/storageclasses/standard-csi.json
- pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
- pkg/gatherers/clusterconfig/gather_storageclass.go
- pkg/gatherers/clusterconfig/gather_storageclass_test.go
Backport #858
- `docs/insights-archive-sample/config/storage/storageclasses/standard-csi.json`
- `pkg/gatherers/clusterconfig/gather_cluster_storageclass_test.go`
No
https://issues.redhat.com/browse/OCPBUGS-22996
> [release-4.14] OCPBUGS-22996: adds cluster storageclasses gather (#858)

- pkg/config/configobserver/configmapobserver.go
- pkg/controller/operator.go
This is adding the logic to try to read the new configuration config map immediately during the configmap observer initialization (and not wait for the first informer sync or re-sync)
no new data 
Yes/No
> CCXDEV-12194: read configmap during configmap observer init

- docs/arch.md
Fix a typo in arch doc in a link to gathers.json.
> Fix typo in link to gathers.json

- pkg/controller/periodic/periodic.go
- pkg/controller/periodic/periodic_test.go
This sets the related objects in the DataGather resource status. 
- no new data
No
> CCXDEV-11652: update related objects in the DataGather CR in techpreview

- pkg/gatherers/clusterconfig/gather_dvo_metrics.go
no new data
No
https://issues.redhat.com/browse/OCPBUGS-23445
> [release-4.14] OCPBUGS-23445: DVO gatherer - add retry logic (#861)

- docs/gathered-data.md
- docs/insights-archive-sample/config/storage/storageclasses/standard-csi.json
- pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
- pkg/gatherers/clusterconfig/gather_storageclass.go
- pkg/gatherers/clusterconfig/gather_storageclass_test.go
Backport #858
- `docs/insights-archive-sample/config/storage/storageclasses/standard-csi.json`
- `pkg/gatherers/clusterconfig/gather_cluster_storageclass_test.go`
No
https://issues.redhat.com/browse/OCPBUGS-22997
> [release-4.13] OCPBUGS-22997: adds gather storageclasses

- cmd/changelog/main.go
This is attempt to fix the SAST warning:
```
Unsanitized input from a CLI argument flows into net.http.NewRequestWithContext, where it is used as an URL to perform a request. This may result in a Server-Side Request Forgery vulnerability.
```
no new data
No
https://issues.redhat.com/browse/OCPBUGS-23616
> OCPBUGS-23616: changelog script - parse arguments as time

- docs/gathered-data.md
- docs/insights-archive-sample/config/helmchart_info.json
- pkg/gather/gather.go
- pkg/gatherers/workloads/gather_helm_info.go
- pkg/gatherers/workloads/gather_helm_info_test.go
- pkg/gatherers/workloads/types.go
- pkg/gatherers/workloads/types_test.go
- pkg/gatherers/workloads/workloads_gatherer.go
- pkg/gatherers/workloads/workloads_gatherer_test.go
- pkg/gatherers/workloads/workloads_info_test.go
Backport #868 
- `docs/insights-archive-sample/config/helmchart_info.json`
- `docs/gathered-data.md` (updated)
- `pkg/gatherers/workloads/gather_helm_info_test.go`
- `pkg/gatherers/workloads/gather_workloads_info_test.go` (updated)
- `pkg/gatherers/workloads/types_test.go`
No
https://issues.redhat.com/browse/CCXDEV-12266
> [release-4.13] OCPBUGS-24255: adds helm information gather

- docs/gathered-data.md
- docs/insights-archive-sample/config/helmchart_info.json
- pkg/gather/gather.go
- pkg/gatherers/workloads/gather_helm_info.go
- pkg/gatherers/workloads/gather_helm_info_test.go
- pkg/gatherers/workloads/types.go
- pkg/gatherers/workloads/types_test.go
- pkg/gatherers/workloads/workloads_gatherer.go
- pkg/gatherers/workloads/workloads_gatherer_test.go
- pkg/gatherers/workloads/workloads_info_test.go
Backport #868 
- `docs/insights-archive-sample/config/helmchart_info.json`
- `docs/gathered-data.md` (updated)
- `pkg/gatherers/workloads/gather_helm_info_test.go`
- `pkg/gatherers/workloads/gather_workloads_info_test.go` (updated)
- `pkg/gatherers/workloads/types_test.go`
No
https://issues.redhat.com/browse/CCXDEV-12266
> [release-4.12] OCPBUGS-24256: adds helm information gather

- docs/gathered-data.md
- docs/insights-archive-sample/config/helmchart_info.json
- pkg/gather/gather.go
- pkg/gatherers/workloads/gather_helm_info.go
- pkg/gatherers/workloads/gather_helm_info_test.go
- pkg/gatherers/workloads/types.go
- pkg/gatherers/workloads/types_test.go
- pkg/gatherers/workloads/workloads_gatherer.go
- pkg/gatherers/workloads/workloads_gatherer_test.go
- pkg/gatherers/workloads/workloads_info_test.go
Backport #868 
- `docs/insights-archive-sample/config/helmchart_info.json`
- `docs/gathered-data.md` (updated)
- `pkg/gatherers/workloads/gather_helm_info_test.go`
- `pkg/gatherers/workloads/gather_workloads_info_test.go` (updated)
- `pkg/gatherers/workloads/types_test.go`
No
https://issues.redhat.com/browse/CCXDEV-12266
> [release-4.11] OCPBUGS-25711: adds helm information gather

- pkg/cmd/start/start.go
- pkg/config/configobserver/secretconfigobserver.go
- pkg/controller/gather_commands.go
- pkg/controller/periodic/periodic.go
- pkg/controller/status/controller.go
- pkg/gather/tasks_processing.go
- pkg/gatherers/workloads/gather_workloads_info.go
- pkg/insights/insightsclient/requests.go
- pkg/insights/insightsreport/insightsreport.go
- pkg/insights/insightsuploader/insightsuploader.go
- pkg/recorder/diskrecorder/diskrecorder.go
- pkg/recorder/recorder.go
> NO-JIRA: adjust log level of some rather important messages

- manifests/06-deployment-ibm-cloud-managed.yaml
- manifests/06-deployment.yaml
with the https://github.com/openshift/insights-operator/pull/894  loglevel controller has merged, we can remove the loglevel in manifests, which now is already controlled by loglevel controller and is set on Normal by default
Yes/No
> NO-JIRA: manifests: bump loglevel of operator to normal

- manifests/06-deployment-ibm-cloud-managed.yaml
- manifests/06-deployment.yaml
This PR pins the required SCC to the `insights-operator` workload.
None; `restricted-v2` is the SCC that the pod is currently admitted with.
https://issues.redhat.com/browse/AUTH-482
> AUTH-482: set required-scc for openshift workloads

- manifests/03-clusterrole.yaml
- pkg/controller/periodic/job.go
- pkg/controller/periodic/periodic.go
This PR replaces event polling from periodic job completion and replaces it with event listening.
N/A
N/A
N/A
No
https://issues.redhat.com/browse/CCXDEV-10669
> NO-JIRA: (refactor) job completion uses event instead polling

- pkg/controller/periodic/job.go
- pkg/controller/periodic/periodic.go
- vendor/k8s.io/client-go/tools/watch/informerwatcher.go
- vendor/k8s.io/client-go/tools/watch/retrywatcher.go
- vendor/k8s.io/client-go/tools/watch/until.go
- vendor/modules.txt
No
https://issues.redhat.com/browse/OCPBUGS-31031
> OCPBUGS-31031: use retrywatcher when watching job

- pkg/controller/operator.go
- pkg/controller/periodic/job.go
This is adding logic (in techpreview) that after start removes all the active Jobs with `periodic-gathering-` prefix (I think it's not very nice to kill job spawned by user). This is to prevent potential race condition for the future remote configuration (rapid recommendations) based on the OCP version. What can theoretically happen is the following:
- operator creates a job with OCP version 1.2.3 (so the remote configuration is in version 1.2.3 too)
- CVO updates the operator to OCP version 1.2.4 (which leads to re-redeployment), but the job still uses the older OCP version 
No
> NO-JIRA: delete all active jobs during restart

- pkg/controller/operator.go
- pkg/insights/insightsuploader/insightsuploader.go
> NO-JIRA: minor logging update when data gathering is disabled

- docs/gathered-data.md
- pkg/gatherers/clusterconfig/gather_dvo_metrics.go
Minor update to DVO metrics gatherer. It extends the documentation to be more explicit and it also adds warning to archive metadata when no DVO service is found. 
- no new data
Yes/No
> NO-JIRA: DVO metrics gatherer minor changes

- pkg/anonymization/anonymizer.go
- pkg/anonymization/anonymizer_test.go
This is a simple fix for the IP anonymizer
- no new data
- 
No
https://issues.redhat.com/browse/OCPBUGS-32702
> OCPBUGS-32702: anonymization - externalIP can be nil

- pkg/anonymization/anonymizer.go
- pkg/anonymization/anonymizer_test.go
Yes/No
https://issues.redhat.com/browse/OCPBUGS-33193
> [release-4.14] OCPBUGS-33193: anonymization - externalIP can be nil (#931)

- pkg/anonymization/anonymizer.go
- pkg/anonymization/anonymizer_test.go
> [release-4.13] OCPBUGS-33449: anonymization - externalIP can be nil (#931) (#933)

- docs/gathered-data.md
- docs/insights-archive-sample/aggregated/pods_and_netnamespaces_with_sdn_annotations.json
- pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
- pkg/gatherers/clusterconfig/gather_pod_and_netnamespaces_with_sdn_annotation.go
- pkg/gatherers/clusterconfig/gather_pod_and_netnamespaces_with_sdn_annotation_test.go
This new gatherer aggregates a number of Pods having `pod.network.openshift.io/assign-macvlan` annotation and number of netnamespaces having `netnamespace.network.openshift.io/multicast-enabled: "true"` annotation 
- `docs/insights-archive-sample/aggregated/pods_and_netnamespaces_with_sdn_annotations.json`
- `pkg/gatherers/clusterconfig/gather_pod_and_netnamespaces_with_sdn_annotation_test.go`
No
https://issues.redhat.com/browse/OCPBUGS-34788
> OCPBUGS-34788: gather aggregated numbers of Pods and Netnamespaces with SDN annotations

- .golangci.yml
- docs/gathered-data.md
- docs/insights-archive-sample/aggregated/ingress_controllers_certs.json
- pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
- pkg/gatherers/clusterconfig/gather_cluster_ingress_certificates.go
- pkg/gatherers/clusterconfig/gather_cluster_ingress_certificates_test.go
This PR continues the work of #917
> OCPBUGS-35727: Ingress controller related certificates' validate dates gathering

- pkg/controller/periodic/periodic.go
- pkg/controller/periodic/periodic_test.go
- pkg/insights/insightsreport/insightsreport.go
- pkg/insights/metrics.go
Previously when user clicked on the link and there wasn't any active SSO session/token then the redirect failed. 
- no new data
- 
- `
No
https://issues.redhat.com/browse/OCPBUGS-35882
> OCPBUGS-35882: properly encode the URL for the advisor links

- pkg/controller/periodic/periodic.go
- pkg/controller/periodic/periodic_test.go
- pkg/insights/insightsreport/insightsreport.go
- pkg/insights/metrics.go
Yes/No
https://issues.redhat.com/browse/OCPBUGS-35882
> [release-4.16] OCPBUGS-36149: properly encode the URL for the advisor links

- cmd/gendoc/main.go
- pkg/controller/periodic/periodic.go
- pkg/controller/periodic/periodic_test.go
- pkg/insights/insightsreport/insightsreport.go
- pkg/insights/metrics.go
Yes/No
https://issues.redhat.com/browse/OCPBUGS-36475
> [release-4.14] OCPBUGS-36475: properly encode the URL for the advisor links

- manifests/06-deployment-ibm-cloud-managed.yaml
- manifests/06-deployment.yaml
This PR pins the required SCC to the insights-operator workload.
Manual cherry-pick of [#915](https://github.com/openshift/insights-operator/pull/915)
None; restricted-v2 is the SCC that the pod is currently admitted with.
https://issues.redhat.com/browse/OCPBUGS-36805
> [release-4.15] OCPBUGS-36805: Set required-scc for openshift workloads

- cmd/gendoc/main.go
- pkg/insights/insightsreport/insightsreport.go
- pkg/insights/metrics.go
Yes/No
https://issues.redhat.com/browse/OCPBUGS-36475
> [release-4.13] OCPBUGS-36745: properly encode the URL for the advisor links (#962)

- docs/gathered-data.md
- docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkconfigurationpolicies/policy-name.json
- docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkstates/ip-10-0-21-41.us-east-2.compute.internal.json
- docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkstates/ip-10-0-24-83.us-east-2.compute.internal.json
- docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkstates/ip-10-0-42-30.us-east-2.compute.internal.json
- docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkstates/ip-10-0-61-249.us-east-2.compute.internal.json
- docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkstates/ip-10-0-78-199.us-east-2.compute.internal.json
- docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkstates/ip-10-0-85-177.us-east-2.compute.internal.json
- pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
- pkg/gatherers/clusterconfig/const.go
- pkg/gatherers/clusterconfig/gather_nmstate_node_network_configuration_policy.go
- pkg/gatherers/clusterconfig/gather_nmstate_node_network_configuration_policy_test.go
- pkg/gatherers/clusterconfig/gather_nmstate_nodenetworkstate.go
- pkg/gatherers/clusterconfig/gather_nmstate_nodenetworkstate_test.go
- pkg/gatherers/clusterconfig/testdata/node_network_configuration_policy.yaml
- pkg/gatherers/clusterconfig/testdata/node_network_state_no_interfaces.yaml
- pkg/gatherers/clusterconfig/testdata/node_network_state_with_interfaces.yaml
- pkg/gatherers/clusterconfig/testdata/node_network_state_with_interfaces_and_mac_addresses.yaml
- pkg/gatherers/conditional/filter_and_gather_container_logs.go
- pkg/gatherers/conditional/gather_containers_logs.go
- pkg/gatherers/conditional/gathering_functions.go
- `docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkconfigurationpolicies/policy-name.json`
- `docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkstates/ip-10-0-21-41.us-east-2.compute.internal.json`
- `docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkstates/ip-10-0-24-83.us-east-2.compute.internal.json`
- `docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkstates/ip-10-0-42-30.us-east-2.compute.internal.json`
- `docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkstates/ip-10-0-61-249.us-east-2.compute.internal.json`
- `pkg/gatherers/clusterconfig/gather_nmstate_node_network_configuration_policy_test.go`
- …
> OCPBUGS-39111: collect some nmstate customresources

- pkg/controller/operator.go
- pkg/insights/insightsclient/insightsclient.go
- pkg/insights/insightsclient/requests.go
- pkg/ocm/sca/sca.go
- pkg/ocm/sca/sca_test.go
N/A
N/A
N/A
Yes. There is no new data collected.
No
https://issues.redhat.com/browse/OCPBUGS-32233
> OCPBUGS-32233: Not able to enable repositories during entitled build in OCP Cluster on IBM-Z

- docs/gathered-data.md
- docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkconfigurationpolicies/policy-name.json
- docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkstates/ip-10-0-21-41.us-east-2.compute.internal.json
- docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkstates/ip-10-0-24-83.us-east-2.compute.internal.json
- docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkstates/ip-10-0-42-30.us-east-2.compute.internal.json
- docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkstates/ip-10-0-61-249.us-east-2.compute.internal.json
- docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkstates/ip-10-0-78-199.us-east-2.compute.internal.json
- docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkstates/ip-10-0-85-177.us-east-2.compute.internal.json
- manifests/03-clusterrole.yaml
- pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
- pkg/gatherers/clusterconfig/const.go
- pkg/gatherers/clusterconfig/gather_nmstate_node_network_configuration_policy.go
- pkg/gatherers/clusterconfig/gather_nmstate_node_network_configuration_policy_test.go
- pkg/gatherers/clusterconfig/gather_nmstate_nodenetworkstate.go
- pkg/gatherers/clusterconfig/gather_nmstate_nodenetworkstate_test.go
- pkg/gatherers/clusterconfig/testdata/node_network_configuration_policy.yaml
- pkg/gatherers/clusterconfig/testdata/node_network_state_no_interfaces.yaml
- pkg/gatherers/clusterconfig/testdata/node_network_state_with_interfaces.yaml
- pkg/gatherers/clusterconfig/testdata/node_network_state_with_interfaces_and_mac_addresses.yaml
- `docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkconfigurationpolicies/policy-name.json`
- `pkg/gatherers/clusterconfig/gather_nmstate_node_network_configuration_policy_test.go`
No
https://issues.redhat.com/browse/OCPBUGS-39394
> [release-4.16] OCPBUGS-39394: collect some nmstate customresources

- docs/gathered-data.md
- docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkconfigurationpolicies/policy-name.json
- docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkstates/ip-10-0-21-41.us-east-2.compute.internal.json
- docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkstates/ip-10-0-24-83.us-east-2.compute.internal.json
- docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkstates/ip-10-0-42-30.us-east-2.compute.internal.json
- docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkstates/ip-10-0-61-249.us-east-2.compute.internal.json
- docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkstates/ip-10-0-78-199.us-east-2.compute.internal.json
- docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkstates/ip-10-0-85-177.us-east-2.compute.internal.json
- manifests/03-clusterrole.yaml
- pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
- pkg/gatherers/clusterconfig/const.go
- pkg/gatherers/clusterconfig/gather_nmstate_node_network_configuration_policy.go
- pkg/gatherers/clusterconfig/gather_nmstate_node_network_configuration_policy_test.go
- pkg/gatherers/clusterconfig/gather_nmstate_nodenetworkstate.go
- pkg/gatherers/clusterconfig/gather_nmstate_nodenetworkstate_test.go
- pkg/gatherers/clusterconfig/testdata/node_network_configuration_policy.yaml
- pkg/gatherers/clusterconfig/testdata/node_network_state_no_interfaces.yaml
- pkg/gatherers/clusterconfig/testdata/node_network_state_with_interfaces.yaml
- pkg/gatherers/clusterconfig/testdata/node_network_state_with_interfaces_and_mac_addresses.yaml
- `docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkconfigurationpolicies/policy-name.json`
- `pkg/gatherers/clusterconfig/gather_nmstate_node_network_configuration_policy_test.go`
No
https://issues.redhat.com/browse/OCPBUGS-39395
> [release-4.15] OCPBUGS-39395: collect some nmstate customresources 

- pkg/ocm/sca/sca.go
Small bugfix over the previous PR #991
N/A
N/A
N/A
No
No
https://issues.redhat.com/browse/OCPBUGS-39563
> [release-4.17] OCPBUGS-39563: Not able to enable repositories during entitled build in OCP Cluster on IBM-Z

- pkg/controller/gather_commands.go
- pkg/controller/gather_commands_test.go
- pkg/controller/periodic/periodic.go
- pkg/controller/periodic/periodic_test.go
- pkg/controller/status/controller.go
- pkg/controller/status/datagather_status.go
- pkg/controllerstatus/controllerstatus.go
- pkg/gatherers/conditional/conditional_gatherer.go
- pkg/gatherers/conditional/conditional_gatherer_test.go
- pkg/gatherers/conditional/types.go
- pkg/gatherers/conditional/validation.go
- pkg/gatherers/interface.go
error
We can't propagate the remote configuration status as an error, because then the gathering won't take place (when the remote config is not available) and we still want to run it based on the built-in configuration (even though it's empty now). 
This introduces a new "gatherer type" providing the acess to the remote configuration status.   
- no new data
-
No
https://issues.redhat.com/browse/OCPBUGS-42675
> OCPBUGS-42675: do not propagate the remote configuration status as an

- docs/gathered-data.md
- pkg/gatherers/clusterconfig/gather_machine_configs.go
- pkg/gatherers/clusterconfig/gather_machine_configs_test.go
This PR implements a new data enhancement to the MachineConfig gatherer. It will generate the number of unused MachineConfig detected on the cluster.
- `aggregated/unused_machine_configs_count.json`
N/A
N/A
No
No
https://issues.redhat.com/browse/CCXDEV-14462
> CCXDEV-14462: [IO Enhancement] collect how many unused MachineConfigs in the cluster

- docs/gathered-data.md
- docs/insights-archive-sample/cluster-scoped-resources/rbac.authorization.k8s.io/clusterroles/admin.json
- docs/insights-archive-sample/cluster-scoped-resources/rbac.authorization.k8s.io/clusterroles/edit.json
- pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
- pkg/gatherers/clusterconfig/gather_cluster_roles.go
- pkg/gatherers/clusterconfig/gather_cluster_roles_test.go
- `docs/insights-archive-sample/cluster-scoped-resources/rbac.authorization.k8s.io/clusterroles/admin.json`
- `docs/insights-archive-sample/cluster-scoped-resources/rbac.authorization.k8s.io/clusterroles/edit.json`
- `pkg/gatherers/clusterconfig/gather_cluster_roles_test.go`
No
https://issues.redhat.com/browse/OCPBUGS-43651
> OCPBUGS-43651: gather selected clusterroles

- docs/gathered-data.md
This PR is just fix of the documentation bug and fixes links to the OpenStackDataPlaneNodeSet and OpenStackDataPlaneVersion example CRs
No
> NO-JIRA: Fix links to the OpenStack related CRs in the gathered-data doc

- pkg/gatherers/conditional/validation.go
- pkg/gatherers/conditional/validation_test.go
This is adding sorting of the JSON schema validation errors (comming from the third party library) used when validating the remote configuration (originally conditional gathering conditions)
no new data
Yes
https://issues.redhat.com/browse/CCXDEV-14573
> CCXDEV-14573: sort the JSON schema validation errors

- docs/gathered-data.md
- pkg/gatherers/clusterconfig/gather_lokistack.go
The current implementation includes the same error several times. This improvement makes to only include one time the error, making it more clear
N/A
N/A
N/A
No
No
No
#1022 
[OCPBUGS-45047
](https://issues.redhat.com/browse/OCPBUGS-45047)
> OCPBUGS-45047: Avoid to send the same error repeated N times

- pkg/controller/status/datagather_status.go
- pkg/controller/status/datagather_status_test.go
- no new data
- 
- `pkg/controller/status/datagather_status_test.go` - extended to cover the problematic case
No
https://issues.redhat.com/browse/OCPBUGS-45479
> OCPBUGS-45479: avoid possible Go panic when searching existing conditions

- pkg/insights/prometheus_rules.go
This is bug fix for [OCPBUGS-44211](https://issues.redhat.com/browse/OCPBUGS-44211).
Ignoring the previous status, that can be unknown when starting the Insights Operator, as creating or removing a `PrometheusRule` is an idempotent operation.
The described problem is caused because when the Insights Operator starts it doesn't know if the `PrometheusRule` to enable the alert triggering is already existing or not, and it assumes by default that it doesn't exist, so it doesn't try to remove it.
With the new approach, the `PrometheusRule` will be removed in any case.
N/A
N/A
N/A
Yes. There is no new collected information.
No
No
https://issues.redhat.com/browse/OCPBUGS-44211
> OCPBUGS-44211: Ignore previous status when disabling alerts

- docs/gathered-data.md
- docs/insights-archive-sample/namespaces/openshift-logging/lokistack-sample.json
- manifests/03-clusterrole.yaml
- pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
- pkg/gatherers/clusterconfig/const.go
- pkg/gatherers/clusterconfig/gather_lokistack.go
- pkg/gatherers/clusterconfig/gather_lokistacks_test.go
This is a manual cherry-pick of #1022 and #1043
/assign openshift-ci-robot
> [release-4.16] OCPBUGS-45203: LokiStack gatherer

- manifests/10-insights-runtime-extractor.yaml
The extractor container relies on critctl to collect container information
If the crio.service is restarted on the worker nodes when the CA bundle has been updated by the proxy/cluster, the container would not be able to connect anymore on the restarted CRI-O service.
Adding a liveness probe that check that crictl works as expected ensure that the container will be killed and restarted with the correct TLS settings to connect to the CRI-O service.
This fixes https://issues.redhat.com/browse/OCPBUGS-48154.
No
https://issues.redhat.com/browse/OCPBUGS-48154
> OCPBUGS-48154: Add a liveness probe to the extractor container

- config/pod.yaml
- manifests/03-clusterrole.yaml
- pkg/insights/insightsclient/insightsclient.go
- pkg/insights/insightsclient/requests.go
- pkg/insights/insightsclient/requests_test.go
- pkg/ocm/sca/architectures_gather.go
- pkg/ocm/sca/architectures_gather_test.go
- pkg/ocm/sca/sca.go
- pkg/ocm/sca/sca_test.go
This PR implements the gathering of architectures used by nodes and the retrieval of entitlement certificates for each architecture in use. These certificates are then stored in secrets. 
If only one architecture is present, the secret is named etc-pki-entitlement. 
If multiple architectures are present, secrets are created with names like etc-pki-entitlement-ARCH, where ARCH represents the specific architecture.
The archive won't change with this feature
No documentation update
- pkg/ocm/sca/architectures_gather_test.go
- pkg/ocm/sca/sca_test.go
No
Yes/No
https://issues.redhat.com/browse/CCXDEV-12875
> CCXDEV-12875: Enable Insight Operator entitlements for multi arch clusters

- manifests/10-insights-runtime-extractor.yaml
- pkg/gatherers/workloads/gather_workloads_runtime_infos.go
Let the kube-rbac-proxy listens on `8443` (without specifying the IP address)
In the insights-operator, connect to this port to go through the kube-rbac-proxy
This fixes https://issues.redhat.com/browse/OCPBUGS-51109
> OCPBUGS-51109: Fix bad IPv6 address

- manifests/10-insights-runtime-extractor.yaml
The extractor container relies on critctl to collect container information
If the crio.service is restarted on the worker nodes when the CA bundle has been updated by the proxy/cluster, the container would not be able to connect anymore on the restarted CRI-O service.
Adding a liveness probe that check that crictl works as expected ensure that the container will be killed and restarted with the correct TLS settings to connect to the CRI-O service.
This fixes https://issues.redhat.com/browse/OCPBUGS-48790.
Upstream PR is #1067.
No
https://issues.redhat.com//browse/OCPBUGS-48790
> [release-4.18] OCPBUGS-48790: Add a liveness probe to the extractor container

- pkg/gather/gather.go
- pkg/gather/gather_test.go
This PR ensures that when a gatherer is disabled, users can still explicitly enable specific functions within that gatherer.
None
None
- pkg/gather/gather_test.go
No
No
https://issues.redhat.com/browse/CCXDEV-14934
> CCXDEV-14934: fix: allow running enabled functions from disabled gatherer

- manifests/10-insights-runtime-extractor.yaml
- pkg/gatherers/workloads/gather_workloads_runtime_infos.go
Let the kube-rbac-proxy listens on 8443 (without specifying the IP address)
In the insights-operator, connect to this port to go through the kube-rbac-proxy
This fixes https://issues.redhat.com/browse/OCPBUGS-51163
I've also cherry-picked a commit for https://issues.redhat.com/browse/OCPBUGS-51164 as it was fixed in `master` by [OCPBUGS-45926: use joinHostPort to fix IPv6](https://github.com/openshift/insights-operator/pull/1050/commits/a94cacd7c4fbe725333a06072224c8b37483a08c) but is also necessary on `4.18` to connect on an IPv6 cluster
https://issues.redhat.com/browse/OCPBUGS-51163
https://issues.redhat.com/browse/OCPBUGS-51164
Upstream PR is https://github.com/openshift/insights-operator/pull/1073
> [release-4.18] OCPBUGS-51163: Fix bad IPv6 address

- pkg/controller/status/controller.go
- pkg/controller/status/controller_test.go
This PR removes the Upgradeable condition from the Insights Operator so that it does not block cluster-version operator updates.
None
None
None
None
No
https://issues.redhat.com/browse/CCXDEV-14944
> CCXDEV-14944: remove the upgradeable condition

- pkg/controller/status/conditions.go
- pkg/controller/status/conditions_test.go
- pkg/controller/status/controller.go
- pkg/controller/status/controller_test.go
This PR adds a new condition to IO, which is set when gathering is disabled via the API. To disable gathering in the API, set `disabledGatherers` to `all` in the `InsightsDataGather` spec.
- None
- None
- None
No
https://issues.redhat.com/browse/CCXDEV-9968
> CCXDEV-9968: add disabledWithApi condition

- pkg/controller/gather_commands.go
- pkg/controller/periodic/periodic.go
- pkg/controller/status/datagather_status.go
This PR updates the UploadData condition to store the HTTP status code in the condition.Message instead of condition.Reason.
None
None
None
No
https://issues.redhat.com/browse/CCXDEV-15070
> CCXDEV-15070: move HTTP status code from condition.Reason to condition.Message

- pkg/ocm/sca/architectures_gather.go
- pkg/ocm/sca/architectures_gather_test.go
- pkg/ocm/sca/sca.go
- pkg/ocm/sca/sca_test.go
This PR ensures that default etc-entitlement-pki secret is created and updated, including multi-architecture clusters where the architecture specific secrets are created as well.
- None
- None
- pkg/ocm/sca/architectures_gather_test.go
- pkg/ocm/sca/sca_test.go
None
No
https://issues.redhat.com/browse/CCXDEV-15026
> CCXDEV-15026: ensure the etc-entitlement-pki secret exists

- pkg/controller/gather_commands.go
- pkg/controller/periodic/periodic.go
- pkg/controller/status/controller.go
- pkg/controller/status/datagather_status.go
- pkg/controller/status/datagather_status_test.go
- pkg/gatherers/conditional/conditional_gatherer.go
- pkg/gatherers/conditional/conditional_gatherer_test.go
- pkg/gatherers/conditional/types.go
This PR is changing the DataGather condition reasons based on the changes introduced in the v1alpha2 version of DataGather. Main change is from AsExpected reason to Succeeded or Failed reason.
- None
- None
- `pkg/controller/status/datagather_status_test.go`
- `pkg/gatherers/conditional/conditional_gatherer_test.go`
None
No
https://issues.redhat.com/browse/CCXDEV-15113
> CCXDEV-15113: update DataGather condition reasons

- pkg/gatherers/workloads/gather_workloads_runtime_infos.go
- pkg/gatherers/workloads/gather_workloads_runtime_infos_test.go
Provide meaningful error message with the URL of the insights-runtime-extractor URLs when the extraction of runtime data fails.
This fixes https://issues.redhat.com/browse/OCPBUGS-55805.
No
https://issues.redhat.com/browse/OCPBUGS-55805.
> OCPBUGS-55805: Enhance insights-runtime-extractor errors

- pkg/controller/periodic/job.go
- pkg/controller/periodic/job_test.go
This PR adds functionality to copy the cluster-wide proxy environment variables from the IO pod to the gathering pod, ensuring the proxy is used for uploads from gathering pods as well.
- None
- None
- `pkg/controller/periodic/job_test.go`
- None
No
[OCPBUGS-56259](https://issues.redhat.com/browse/OCPBUGS-56259)
> OCPBUGS-56259: copy proxy envs from IO pod to gathering pods

- .openshiftci/install-golangci-lint.sh
This PR is fixing the OOM issue that the lint job run into after updating the image golang version to 1.24.
- None
- None
- None
No
> NO-JIRA: chore: bump golang-ci version

- pkg/gatherers/workloads/gather_workloads_runtime_infos.go
- pkg/gatherers/workloads/gather_workloads_runtime_infos_test.go
Provide meaningful error message with the URL of the insights-runtime-extractor URLs when the extraction of runtime data fails.
No
This fixes https://issues.redhat.com/browse/OCPBUGS-56781.
Upstream issue: https://issues.redhat.com/browse/OCPBUGS-55805
Upstream PR: #1085
> [release-4.19] OCPBUGS-56781: Enhance insights-runtime-extractor errors

- manifests/06-deployment-ibm-cloud-managed.yaml
Bug: `make update` should have been run at this point
Yes/No
> OCPBUGS-61073: Rerun missed `make update` after read-only filesystem security context added

- pkg/ocm/sca/sca.go
This PR implements a better error message for missing SCA certificates in processing.
None
None
None
No
No
https://issues.redhat.com/browse/OCPBUGS-52838
> OCPBUGS-52838: Update error message for missing SCA certificates

- pkg/controller/status/datagather_status.go
- pkg/controller/status/datagather_status_test.go
This is an manual cherry-pick of https://github.com/openshift/insights-operator/pull/1046
> [release-4.16] OCPBUGS-61108: avoid possible Go panic when searching existing conditions

- pkg/controller/gather_commands.go
- pkg/controller/periodic/job.go
- pkg/controller/periodic/periodic.go
- pkg/controller/status/datagather_status.go
This PR adds functionality to update DataGather progressing condition to GatheringFailed when the
gathering job fails.
- `None`
- `None`
- `None`
- `None`
No
[OCPBUGS-60931](https://issues.redhat.com/browse/OCPBUGS-60931)
> OCPBUGS-60931: update DataGather condition when gathering job fails
